// Code generated by schema-gen; DO NOT EDIT.

package acp

import (
	"encoding/json"
	"fmt"
)

// Predefined error codes for common JSON-RPC and ACP-specific errors.
//
// These codes follow the JSON-RPC 2.0 specification for standard errors
// and use the reserved range (-32000 to -32099) for protocol-specific errors.
type ErrorCode int

const (
	// **Parse error**: Invalid JSON was received by the server.
	// An error occurred on the server while parsing the JSON text.
	ErrorCodeParseError ErrorCode = -32700
	// **Invalid request**: The JSON sent is not a valid Request object.
	ErrorCodeInvalidRequest ErrorCode = -32600
	// **Method not found**: The method does not exist or is not available.
	ErrorCodeMethodNotFound ErrorCode = -32601
	// **Invalid params**: Invalid method parameter(s).
	ErrorCodeInvalidParams ErrorCode = -32602
	// **Internal error**: Internal JSON-RPC error.
	// Reserved for implementation-defined server errors.
	ErrorCodeInternalError ErrorCode = -32603
	// **Authentication required**: Authentication is required before this operation can be performed.
	ErrorCodeAuthenticationRequired ErrorCode = -32000
	// **Resource not found**: A given resource, such as a file, was not found.
	ErrorCodeResourceNotFound ErrorCode = -32002
)

// The type of permission option being presented to the user.
//
// Helps clients choose appropriate icons and UI treatment.
type PermissionOptionKind string

const (
	// Allow this operation only this time.
	PermissionOptionKindAllowOnce PermissionOptionKind = "allow_once"
	// Allow this operation and remember the choice.
	PermissionOptionKindAllowAlways PermissionOptionKind = "allow_always"
	// Reject this operation only this time.
	PermissionOptionKindRejectOnce PermissionOptionKind = "reject_once"
	// Reject this operation and remember the choice.
	PermissionOptionKindRejectAlways PermissionOptionKind = "reject_always"
)

// Priority levels for plan entries.
//
// Used to indicate the relative importance or urgency of different
// tasks in the execution plan.
// See protocol docs: [Plan Entries](https://agentclientprotocol.com/protocol/agent-plan#plan-entries)
type PlanEntryPriority string

const (
	// High priority task - critical to the overall goal.
	PlanEntryPriorityHigh PlanEntryPriority = "high"
	// Medium priority task - important but not critical.
	PlanEntryPriorityMedium PlanEntryPriority = "medium"
	// Low priority task - nice to have but not essential.
	PlanEntryPriorityLow PlanEntryPriority = "low"
)

// Status of a plan entry in the execution flow.
//
// Tracks the lifecycle of each task from planning through completion.
// See protocol docs: [Plan Entries](https://agentclientprotocol.com/protocol/agent-plan#plan-entries)
type PlanEntryStatus string

const (
	// The task has not started yet.
	PlanEntryStatusPending PlanEntryStatus = "pending"
	// The task is currently being worked on.
	PlanEntryStatusInProgress PlanEntryStatus = "in_progress"
	// The task has been successfully completed.
	PlanEntryStatusCompleted PlanEntryStatus = "completed"
)

// The sender or recipient of messages and data in a conversation.
type Role string

const (
	RoleAssistant Role = "assistant"
	RoleUser      Role = "user"
)

// Semantic category for a session configuration option.
//
// This is intended to help Clients distinguish broadly common selectors (e.g. model selector vs
// session mode selector vs thought/reasoning level) for UX purposes (keyboard shortcuts, icons,
// placement). It MUST NOT be required for correctness. Clients MUST handle missing or unknown
// categories gracefully.
//
// Category names beginning with `_` are free for custom use, like other ACP extension methods.
// Category names that do not begin with `_` are reserved for the ACP spec.
type SessionConfigOptionCategory string

const (
	// Session mode selector.
	SessionConfigOptionCategoryMode SessionConfigOptionCategory = "mode"
	// Model selector.
	SessionConfigOptionCategoryModel SessionConfigOptionCategory = "model"
	// Thought/reasoning level selector.
	SessionConfigOptionCategoryThoughtLevel SessionConfigOptionCategory = "thought_level"
)

// Reasons why an agent stops processing a prompt turn.
//
// See protocol docs: [Stop Reasons](https://agentclientprotocol.com/protocol/prompt-turn#stop-reasons)
type StopReason string

const (
	// The turn ended successfully.
	StopReasonEndTurn StopReason = "end_turn"
	// The turn ended because the agent reached the maximum number of tokens.
	StopReasonMaxTokens StopReason = "max_tokens"
	// The turn ended because the agent reached the maximum number of allowed
	// agent requests between user turns.
	StopReasonMaxTurnRequests StopReason = "max_turn_requests"
	// The turn ended because the agent refused to continue. The user prompt
	// and everything that comes after it won't be included in the next
	// prompt, so this should be reflected in the UI.
	StopReasonRefusal StopReason = "refusal"
	// The turn was cancelled by the client via `session/cancel`.
	//
	// This stop reason MUST be returned when the client sends a `session/cancel`
	// notification, even if the cancellation causes exceptions in underlying operations.
	// Agents should catch these exceptions and return this semantically meaningful
	// response to confirm successful cancellation.
	StopReasonCancelled StopReason = "cancelled"
)

// Execution status of a tool call.
//
// Tool calls progress through different statuses during their lifecycle.
//
// See protocol docs: [Status](https://agentclientprotocol.com/protocol/tool-calls#status)
type ToolCallStatus string

const (
	// The tool call hasn't started running yet because the input is either
	// streaming or we're awaiting approval.
	ToolCallStatusPending ToolCallStatus = "pending"
	// The tool call is currently running.
	ToolCallStatusInProgress ToolCallStatus = "in_progress"
	// The tool call completed successfully.
	ToolCallStatusCompleted ToolCallStatus = "completed"
	// The tool call failed with an error.
	ToolCallStatusFailed ToolCallStatus = "failed"
)

// Categories of tools that can be invoked.
//
// Tool kinds help clients choose appropriate icons and optimize how they
// display tool execution progress.
//
// See protocol docs: [Creating](https://agentclientprotocol.com/protocol/tool-calls#creating)
type ToolKind string

const (
	// Reading files or data.
	ToolKindRead ToolKind = "read"
	// Modifying files or content.
	ToolKindEdit ToolKind = "edit"
	// Removing files or data.
	ToolKindDelete ToolKind = "delete"
	// Moving or renaming files.
	ToolKindMove ToolKind = "move"
	// Searching for information.
	ToolKindSearch ToolKind = "search"
	// Running commands or code.
	ToolKindExecute ToolKind = "execute"
	// Internal reasoning or planning.
	ToolKindThink ToolKind = "think"
	// Retrieving external data.
	ToolKindFetch ToolKind = "fetch"
	// Switching the current session mode.
	ToolKindSwitchMode ToolKind = "switch_mode"
	// Other tool types (default).
	ToolKindOther ToolKind = "other"
)

type AgentResponse any
type ClientResponse any

// Text content. May be plain text or formatted with Markdown.
//
// All agents MUST support text content blocks in prompts.
// Clients SHOULD render this text as Markdown.
type ContentBlockText struct {
	TextContent
	Type string `json:"type"`
}

// Images for visual context or analysis.
//
// Requires the `image` prompt capability when included in prompts.
type ContentBlockImage struct {
	ImageContent
	Type string `json:"type"`
}

// Audio data for transcription or analysis.
//
// Requires the `audio` prompt capability when included in prompts.
type ContentBlockAudio struct {
	AudioContent
	Type string `json:"type"`
}

// References to resources that the agent can access.
//
// All agents MUST support resource links in prompts.
type ContentBlockResourceLink struct {
	ResourceLink
	Type string `json:"type"`
}

// Complete resource contents embedded directly in the message.
//
// Preferred for including context as it avoids extra round-trips.
//
// Requires the `embeddedContext` prompt capability when included in prompts.
type ContentBlockResource struct {
	EmbeddedResource
	Type string `json:"type"`
}

func (ContentBlockText) isContentBlockVariant() string {
	return "text"
}
func (ContentBlockImage) isContentBlockVariant() string {
	return "image"
}
func (ContentBlockAudio) isContentBlockVariant() string {
	return "audio"
}
func (ContentBlockResourceLink) isContentBlockVariant() string {
	return "resource_link"
}
func (ContentBlockResource) isContentBlockVariant() string {
	return "resource"
}

type contentBlockVariant interface{ isContentBlockVariant() string }

// Content blocks represent displayable information in the Agent Client Protocol.
//
// They provide a structured way to handle various types of user-facing content—whether
// it's text from language models, images for analysis, or embedded resources for context.
//
// Content blocks appear in:
// - User prompts sent via `session/prompt`
// - Language model output streamed through `session/update` notifications
// - Progress updates and results from tool calls
//
// This structure is compatible with the Model Context Protocol (MCP), enabling
// agents to seamlessly forward content from MCP tool outputs without transformation.
//
// See protocol docs: [Content](https://agentclientprotocol.com/protocol/content)
type ContentBlock struct {
	variant contentBlockVariant
}

func (c ContentBlock) MarshalJSON() ([]byte, error) {
	if c.variant == nil {
		return nil, fmt.Errorf("no variant is set for ContentBlock")
	}
	return json.Marshal(c.variant)
}

// ContentBlockVariantFactory is a factory function that deserializes a variant from JSON.
type ContentBlockVariantFactory func(data []byte) (contentBlockVariant, error)

var contentBlockExtVariants = map[string]ContentBlockVariantFactory{}

// RegisterContentBlockVariant registers a new variant factory for the ContentBlock union.
// Call this from init() to extend the union with additional variants.
func RegisterContentBlockVariant(discriminator string, factory ContentBlockVariantFactory) {
	contentBlockExtVariants[discriminator] = factory
}
func tryContentBlockExtension(discriminator string) (ContentBlockVariantFactory, bool) {
	fn, ok := contentBlockExtVariants[discriminator]
	return fn, ok
}
func (c *ContentBlock) UnmarshalJSON(data []byte) error {
	var disc struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return err
	}
	switch disc.Type {
	case "text":
		var v ContentBlockText
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		c.variant = v
		return nil
	case "image":
		var v ContentBlockImage
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		c.variant = v
		return nil
	case "audio":
		var v ContentBlockAudio
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		c.variant = v
		return nil
	case "resource_link":
		var v ContentBlockResourceLink
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		c.variant = v
		return nil
	case "resource":
		var v ContentBlockResource
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		c.variant = v
		return nil
	default:
		if fn, ok := tryContentBlockExtension(disc.Type); ok {
			v, err := fn(data)
			if err != nil {
				return err
			}
			c.variant = v
			return nil
		}
		return fmt.Errorf("unknown discriminator value: %s", disc.Type)
	}
}
func (c *ContentBlock) AsText() (ContentBlockText, bool) {
	v, ok := c.variant.(ContentBlockText)
	return v, ok
}
func (c *ContentBlock) AsImage() (ContentBlockImage, bool) {
	v, ok := c.variant.(ContentBlockImage)
	return v, ok
}
func (c *ContentBlock) AsAudio() (ContentBlockAudio, bool) {
	v, ok := c.variant.(ContentBlockAudio)
	return v, ok
}
func (c *ContentBlock) AsResourceLink() (ContentBlockResourceLink, bool) {
	v, ok := c.variant.(ContentBlockResourceLink)
	return v, ok
}
func (c *ContentBlock) AsResource() (ContentBlockResource, bool) {
	v, ok := c.variant.(ContentBlockResource)
	return v, ok
}
func (MCPServerHTTP) isMCPServerVariant() string {
	return "http"
}
func (MCPServerSSE) isMCPServerVariant() string {
	return "sse"
}
func (MCPServerStdio) isMCPServerVariant() string {
	return ""
}

type mCPServerVariant interface{ isMCPServerVariant() string }

// Configuration for connecting to an MCP (Model Context Protocol) server.
//
// MCP servers provide tools and context that the agent can use when
// processing prompts.
//
// See protocol docs: [MCP Servers](https://agentclientprotocol.com/protocol/session-setup#mcp-servers)
type MCPServer struct {
	variant mCPServerVariant
}

func (m MCPServer) MarshalJSON() ([]byte, error) {
	if m.variant == nil {
		return nil, fmt.Errorf("no variant is set for MCPServer")
	}
	data, err := json.Marshal(m.variant)
	if err != nil {
		return nil, err
	}
	disc := m.variant.isMCPServerVariant()
	if disc == "" {
		return data, nil
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	obj["type"], _ = json.Marshal(disc)
	return json.Marshal(obj)
}
func (m *MCPServer) UnmarshalJSON(data []byte) error {
	var disc struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return err
	}
	switch disc.Type {
	case "http":
		var v MCPServerHTTP
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		m.variant = v
		return nil
	case "sse":
		var v MCPServerSSE
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		m.variant = v
		return nil
	default:
		var v MCPServerStdio
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		m.variant = v
		return nil
	}
}
func (m *MCPServer) AsHTTP() (MCPServerHTTP, bool) {
	v, ok := m.variant.(MCPServerHTTP)
	return v, ok
}
func (m *MCPServer) AsSSE() (MCPServerSSE, bool) {
	v, ok := m.variant.(MCPServerSSE)
	return v, ok
}
func (m *MCPServer) AsStdio() (MCPServerStdio, bool) {
	v, ok := m.variant.(MCPServerStdio)
	return v, ok
}

// The prompt turn was cancelled before the user responded.
//
// When a client sends a `session/cancel` notification to cancel an ongoing
// prompt turn, it MUST respond to all pending `session/request_permission`
// requests with this `Cancelled` outcome.
//
// See protocol docs: [Cancellation](https://agentclientprotocol.com/protocol/prompt-turn#cancellation)
type RequestPermissionOutcomeCancelled struct {
	Outcome string `json:"outcome"`
}

// The user selected one of the provided options.
type RequestPermissionOutcomeSelected struct {
	SelectedPermissionOutcome
	Outcome string `json:"outcome"`
}

func (RequestPermissionOutcomeCancelled) isRequestPermissionOutcomeVariant() string {
	return "cancelled"
}
func (RequestPermissionOutcomeSelected) isRequestPermissionOutcomeVariant() string {
	return "selected"
}

type requestPermissionOutcomeVariant interface{ isRequestPermissionOutcomeVariant() string }

// The outcome of a permission request.
type RequestPermissionOutcome struct {
	variant requestPermissionOutcomeVariant
}

func (r RequestPermissionOutcome) MarshalJSON() ([]byte, error) {
	if r.variant == nil {
		return nil, fmt.Errorf("no variant is set for RequestPermissionOutcome")
	}
	return json.Marshal(r.variant)
}

// RequestPermissionOutcomeVariantFactory is a factory function that deserializes a variant from JSON.
type RequestPermissionOutcomeVariantFactory func(data []byte) (requestPermissionOutcomeVariant, error)

var requestPermissionOutcomeExtVariants = map[string]RequestPermissionOutcomeVariantFactory{}

// RegisterRequestPermissionOutcomeVariant registers a new variant factory for the RequestPermissionOutcome union.
// Call this from init() to extend the union with additional variants.
func RegisterRequestPermissionOutcomeVariant(discriminator string, factory RequestPermissionOutcomeVariantFactory) {
	requestPermissionOutcomeExtVariants[discriminator] = factory
}
func tryRequestPermissionOutcomeExtension(discriminator string) (RequestPermissionOutcomeVariantFactory, bool) {
	fn, ok := requestPermissionOutcomeExtVariants[discriminator]
	return fn, ok
}
func (r *RequestPermissionOutcome) UnmarshalJSON(data []byte) error {
	var disc struct {
		Outcome string `json:"outcome"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return err
	}
	switch disc.Outcome {
	case "cancelled":
		var v RequestPermissionOutcomeCancelled
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		r.variant = v
		return nil
	case "selected":
		var v RequestPermissionOutcomeSelected
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		r.variant = v
		return nil
	default:
		if fn, ok := tryRequestPermissionOutcomeExtension(disc.Outcome); ok {
			v, err := fn(data)
			if err != nil {
				return err
			}
			r.variant = v
			return nil
		}
		return fmt.Errorf("unknown discriminator value: %s", disc.Outcome)
	}
}
func (r *RequestPermissionOutcome) AsCancelled() (RequestPermissionOutcomeCancelled, bool) {
	v, ok := r.variant.(RequestPermissionOutcomeCancelled)
	return v, ok
}
func (r *RequestPermissionOutcome) AsSelected() (RequestPermissionOutcomeSelected, bool) {
	v, ok := r.variant.(RequestPermissionOutcomeSelected)
	return v, ok
}

// Single-value selector (dropdown).
type SessionConfigOptionSelect struct {
	SessionConfigSelect
	Type        string                       `json:"type"`
	Description string                       `json:"description,omitempty"`
	ID          SessionConfigID              `json:"id"`
	Name        string                       `json:"name"`
	Meta        map[string]any               `json:"_meta,omitempty"`
	Category    *SessionConfigOptionCategory `json:"category,omitempty"`
}

func (SessionConfigOptionSelect) isSessionConfigOptionVariant() string {
	return "select"
}

type sessionConfigOptionVariant interface{ isSessionConfigOptionVariant() string }

// A session configuration option selector and its current state.
type SessionConfigOption struct {
	variant sessionConfigOptionVariant
}

func (s SessionConfigOption) MarshalJSON() ([]byte, error) {
	if s.variant == nil {
		return nil, fmt.Errorf("no variant is set for SessionConfigOption")
	}
	return json.Marshal(s.variant)
}

// SessionConfigOptionVariantFactory is a factory function that deserializes a variant from JSON.
type SessionConfigOptionVariantFactory func(data []byte) (sessionConfigOptionVariant, error)

var sessionConfigOptionExtVariants = map[string]SessionConfigOptionVariantFactory{}

// RegisterSessionConfigOptionVariant registers a new variant factory for the SessionConfigOption union.
// Call this from init() to extend the union with additional variants.
func RegisterSessionConfigOptionVariant(discriminator string, factory SessionConfigOptionVariantFactory) {
	sessionConfigOptionExtVariants[discriminator] = factory
}
func trySessionConfigOptionExtension(discriminator string) (SessionConfigOptionVariantFactory, bool) {
	fn, ok := sessionConfigOptionExtVariants[discriminator]
	return fn, ok
}
func (s *SessionConfigOption) UnmarshalJSON(data []byte) error {
	var disc struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return err
	}
	switch disc.Type {
	case "select":
		var v SessionConfigOptionSelect
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		s.variant = v
		return nil
	default:
		if fn, ok := trySessionConfigOptionExtension(disc.Type); ok {
			v, err := fn(data)
			if err != nil {
				return err
			}
			s.variant = v
			return nil
		}
		return fmt.Errorf("unknown discriminator value: %s", disc.Type)
	}
}
func (s *SessionConfigOption) AsSelect() (SessionConfigOptionSelect, bool) {
	v, ok := s.variant.(SessionConfigOptionSelect)
	return v, ok
}

// Possible values for a session configuration option.
type SessionConfigSelectOptions any

// A chunk of the user's message being streamed.
type SessionUpdateUserMessageChunk struct {
	ContentChunk
	SessionUpdate string `json:"sessionUpdate"`
}

// A chunk of the agent's response being streamed.
type SessionUpdateAgentMessageChunk struct {
	ContentChunk
	SessionUpdate string `json:"sessionUpdate"`
}

// A chunk of the agent's internal reasoning being streamed.
type SessionUpdateAgentThoughtChunk struct {
	ContentChunk
	SessionUpdate string `json:"sessionUpdate"`
}

// Notification that a new tool call has been initiated.
type SessionUpdateToolCall struct {
	ToolCall
	SessionUpdate string `json:"sessionUpdate"`
}

// Update on the status or results of a tool call.
type SessionUpdateToolCallUpdate struct {
	ToolCallUpdate
	SessionUpdate string `json:"sessionUpdate"`
}

// The agent's execution plan for complex tasks.
// See protocol docs: [Agent Plan](https://agentclientprotocol.com/protocol/agent-plan)
type SessionUpdatePlan struct {
	Plan
	SessionUpdate string `json:"sessionUpdate"`
}

// Available commands are ready or have changed
type SessionUpdateAvailableCommandsUpdate struct {
	AvailableCommandsUpdate
	SessionUpdate string `json:"sessionUpdate"`
}

// The current mode of the session has changed
//
// See protocol docs: [Session Modes](https://agentclientprotocol.com/protocol/session-modes)
type SessionUpdateCurrentModeUpdate struct {
	CurrentModeUpdate
	SessionUpdate string `json:"sessionUpdate"`
}

// Session configuration options have been updated.
type SessionUpdateConfigOptionUpdate struct {
	ConfigOptionUpdate
	SessionUpdate string `json:"sessionUpdate"`
}

// Session metadata has been updated (title, timestamps, custom metadata)
type SessionUpdateSessionInfoUpdate struct {
	SessionInfoUpdate
	SessionUpdate string `json:"sessionUpdate"`
}

func (SessionUpdateUserMessageChunk) isSessionUpdateVariant() string {
	return "user_message_chunk"
}
func (SessionUpdateAgentMessageChunk) isSessionUpdateVariant() string {
	return "agent_message_chunk"
}
func (SessionUpdateAgentThoughtChunk) isSessionUpdateVariant() string {
	return "agent_thought_chunk"
}
func (SessionUpdateToolCall) isSessionUpdateVariant() string {
	return "tool_call"
}
func (SessionUpdateToolCallUpdate) isSessionUpdateVariant() string {
	return "tool_call_update"
}
func (SessionUpdatePlan) isSessionUpdateVariant() string {
	return "plan"
}
func (SessionUpdateAvailableCommandsUpdate) isSessionUpdateVariant() string {
	return "available_commands_update"
}
func (SessionUpdateCurrentModeUpdate) isSessionUpdateVariant() string {
	return "current_mode_update"
}
func (SessionUpdateConfigOptionUpdate) isSessionUpdateVariant() string {
	return "config_option_update"
}
func (SessionUpdateSessionInfoUpdate) isSessionUpdateVariant() string {
	return "session_info_update"
}

type sessionUpdateVariant interface{ isSessionUpdateVariant() string }

// Different types of updates that can be sent during session processing.
//
// These updates provide real-time feedback about the agent's progress.
//
// See protocol docs: [Agent Reports Output](https://agentclientprotocol.com/protocol/prompt-turn#3-agent-reports-output)
type SessionUpdate struct {
	variant sessionUpdateVariant
}

func (s SessionUpdate) MarshalJSON() ([]byte, error) {
	if s.variant == nil {
		return nil, fmt.Errorf("no variant is set for SessionUpdate")
	}
	return json.Marshal(s.variant)
}

// SessionUpdateVariantFactory is a factory function that deserializes a variant from JSON.
type SessionUpdateVariantFactory func(data []byte) (sessionUpdateVariant, error)

var sessionUpdateExtVariants = map[string]SessionUpdateVariantFactory{}

// RegisterSessionUpdateVariant registers a new variant factory for the SessionUpdate union.
// Call this from init() to extend the union with additional variants.
func RegisterSessionUpdateVariant(discriminator string, factory SessionUpdateVariantFactory) {
	sessionUpdateExtVariants[discriminator] = factory
}
func trySessionUpdateExtension(discriminator string) (SessionUpdateVariantFactory, bool) {
	fn, ok := sessionUpdateExtVariants[discriminator]
	return fn, ok
}
func (s *SessionUpdate) UnmarshalJSON(data []byte) error {
	var disc struct {
		SessionUpdate string `json:"sessionUpdate"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return err
	}
	switch disc.SessionUpdate {
	case "user_message_chunk":
		var v SessionUpdateUserMessageChunk
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		s.variant = v
		return nil
	case "agent_message_chunk":
		var v SessionUpdateAgentMessageChunk
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		s.variant = v
		return nil
	case "agent_thought_chunk":
		var v SessionUpdateAgentThoughtChunk
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		s.variant = v
		return nil
	case "tool_call":
		var v SessionUpdateToolCall
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		s.variant = v
		return nil
	case "tool_call_update":
		var v SessionUpdateToolCallUpdate
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		s.variant = v
		return nil
	case "plan":
		var v SessionUpdatePlan
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		s.variant = v
		return nil
	case "available_commands_update":
		var v SessionUpdateAvailableCommandsUpdate
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		s.variant = v
		return nil
	case "current_mode_update":
		var v SessionUpdateCurrentModeUpdate
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		s.variant = v
		return nil
	case "config_option_update":
		var v SessionUpdateConfigOptionUpdate
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		s.variant = v
		return nil
	case "session_info_update":
		var v SessionUpdateSessionInfoUpdate
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		s.variant = v
		return nil
	default:
		if fn, ok := trySessionUpdateExtension(disc.SessionUpdate); ok {
			v, err := fn(data)
			if err != nil {
				return err
			}
			s.variant = v
			return nil
		}
		return fmt.Errorf("unknown discriminator value: %s", disc.SessionUpdate)
	}
}
func (s *SessionUpdate) AsUserMessageChunk() (SessionUpdateUserMessageChunk, bool) {
	v, ok := s.variant.(SessionUpdateUserMessageChunk)
	return v, ok
}
func (s *SessionUpdate) AsAgentMessageChunk() (SessionUpdateAgentMessageChunk, bool) {
	v, ok := s.variant.(SessionUpdateAgentMessageChunk)
	return v, ok
}
func (s *SessionUpdate) AsAgentThoughtChunk() (SessionUpdateAgentThoughtChunk, bool) {
	v, ok := s.variant.(SessionUpdateAgentThoughtChunk)
	return v, ok
}
func (s *SessionUpdate) AsToolCall() (SessionUpdateToolCall, bool) {
	v, ok := s.variant.(SessionUpdateToolCall)
	return v, ok
}
func (s *SessionUpdate) AsToolCallUpdate() (SessionUpdateToolCallUpdate, bool) {
	v, ok := s.variant.(SessionUpdateToolCallUpdate)
	return v, ok
}
func (s *SessionUpdate) AsPlan() (SessionUpdatePlan, bool) {
	v, ok := s.variant.(SessionUpdatePlan)
	return v, ok
}
func (s *SessionUpdate) AsAvailableCommandsUpdate() (SessionUpdateAvailableCommandsUpdate, bool) {
	v, ok := s.variant.(SessionUpdateAvailableCommandsUpdate)
	return v, ok
}
func (s *SessionUpdate) AsCurrentModeUpdate() (SessionUpdateCurrentModeUpdate, bool) {
	v, ok := s.variant.(SessionUpdateCurrentModeUpdate)
	return v, ok
}
func (s *SessionUpdate) AsConfigOptionUpdate() (SessionUpdateConfigOptionUpdate, bool) {
	v, ok := s.variant.(SessionUpdateConfigOptionUpdate)
	return v, ok
}
func (s *SessionUpdate) AsSessionInfoUpdate() (SessionUpdateSessionInfoUpdate, bool) {
	v, ok := s.variant.(SessionUpdateSessionInfoUpdate)
	return v, ok
}

// Standard content block (text, images, resources).
type ToolCallContentContent struct {
	Content
	Type string `json:"type"`
}

// File modification shown as a diff.
type ToolCallContentDiff struct {
	Diff
	Type string `json:"type"`
}

// Embed a terminal created with `terminal/create` by its id.
//
// The terminal must be added before calling `terminal/release`.
//
// See protocol docs: [Terminal](https://agentclientprotocol.com/protocol/terminals)
type ToolCallContentTerminal struct {
	Terminal
	Type string `json:"type"`
}

func (ToolCallContentContent) isToolCallContentVariant() string {
	return "content"
}
func (ToolCallContentDiff) isToolCallContentVariant() string {
	return "diff"
}
func (ToolCallContentTerminal) isToolCallContentVariant() string {
	return "terminal"
}

type toolCallContentVariant interface{ isToolCallContentVariant() string }

// Content produced by a tool call.
//
// Tool calls can produce different types of content including
// standard content blocks (text, images) or file diffs.
//
// See protocol docs: [Content](https://agentclientprotocol.com/protocol/tool-calls#content)
type ToolCallContent struct {
	variant toolCallContentVariant
}

func (t ToolCallContent) MarshalJSON() ([]byte, error) {
	if t.variant == nil {
		return nil, fmt.Errorf("no variant is set for ToolCallContent")
	}
	return json.Marshal(t.variant)
}

// ToolCallContentVariantFactory is a factory function that deserializes a variant from JSON.
type ToolCallContentVariantFactory func(data []byte) (toolCallContentVariant, error)

var toolCallContentExtVariants = map[string]ToolCallContentVariantFactory{}

// RegisterToolCallContentVariant registers a new variant factory for the ToolCallContent union.
// Call this from init() to extend the union with additional variants.
func RegisterToolCallContentVariant(discriminator string, factory ToolCallContentVariantFactory) {
	toolCallContentExtVariants[discriminator] = factory
}
func tryToolCallContentExtension(discriminator string) (ToolCallContentVariantFactory, bool) {
	fn, ok := toolCallContentExtVariants[discriminator]
	return fn, ok
}
func (t *ToolCallContent) UnmarshalJSON(data []byte) error {
	var disc struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return err
	}
	switch disc.Type {
	case "content":
		var v ToolCallContentContent
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		t.variant = v
		return nil
	case "diff":
		var v ToolCallContentDiff
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		t.variant = v
		return nil
	case "terminal":
		var v ToolCallContentTerminal
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		t.variant = v
		return nil
	default:
		if fn, ok := tryToolCallContentExtension(disc.Type); ok {
			v, err := fn(data)
			if err != nil {
				return err
			}
			t.variant = v
			return nil
		}
		return fmt.Errorf("unknown discriminator value: %s", disc.Type)
	}
}
func (t *ToolCallContent) AsContent() (ToolCallContentContent, bool) {
	v, ok := t.variant.(ToolCallContentContent)
	return v, ok
}
func (t *ToolCallContent) AsDiff() (ToolCallContentDiff, bool) {
	v, ok := t.variant.(ToolCallContentDiff)
	return v, ok
}
func (t *ToolCallContent) AsTerminal() (ToolCallContentTerminal, bool) {
	v, ok := t.variant.(ToolCallContentTerminal)
	return v, ok
}

// Capabilities supported by the agent.
//
// Advertised during initialization to inform the client about
// available features and content types.
//
// See protocol docs: [Agent Capabilities](https://agentclientprotocol.com/protocol/initialization#agent-capabilities)
type AgentCapabilities struct {
	Meta                map[string]any       `json:"_meta,omitempty"`
	LoadSession         bool                 `json:"loadSession,omitempty"`
	MCPCapabilities     *MCPCapabilities     `json:"mcpCapabilities,omitempty"`
	PromptCapabilities  *PromptCapabilities  `json:"promptCapabilities,omitempty"`
	SessionCapabilities *SessionCapabilities `json:"sessionCapabilities,omitempty"`
}

// Optional annotations for the client. The client can use annotations to inform how objects are used or displayed
type Annotations struct {
	Meta         map[string]any `json:"_meta,omitempty"`
	Audience     []Role         `json:"audience,omitempty"`
	LastModified string         `json:"lastModified,omitempty"`
	Priority     *float64       `json:"priority,omitempty"`
}

// Audio provided to or from an LLM.
type AudioContent struct {
	Meta        map[string]any `json:"_meta,omitempty"`
	Annotations *Annotations   `json:"annotations,omitempty"`
	Data        string         `json:"data"`
	MimeType    string         `json:"mimeType"`
}

// Agent handles authentication itself.
//
// This is the default authentication method type.
type AuthMethodAgent struct {
	Meta        map[string]any `json:"_meta,omitempty"`
	Description string         `json:"description,omitempty"`
	ID          string         `json:"id"`
	Name        string         `json:"name"`
}

// Request parameters for the authenticate method.
//
// Specifies which authentication method to use.
type AuthenticateRequest struct {
	Meta     map[string]any `json:"_meta,omitempty"`
	MethodID string         `json:"methodId"`
}

// Response to the `authenticate` method.
type AuthenticateResponse struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

// Information about a command.
type AvailableCommand struct {
	Meta        map[string]any         `json:"_meta,omitempty"`
	Description string                 `json:"description"`
	Input       *AvailableCommandInput `json:"input,omitempty"`
	Name        string                 `json:"name"`
}

// Available commands are ready or have changed
type AvailableCommandsUpdate struct {
	Meta              map[string]any     `json:"_meta,omitempty"`
	AvailableCommands []AvailableCommand `json:"availableCommands"`
}

// Binary resource contents.
type BlobResourceContents struct {
	Meta     map[string]any `json:"_meta,omitempty"`
	Blob     string         `json:"blob"`
	MimeType string         `json:"mimeType,omitempty"`
	URI      string         `json:"uri"`
}

// Notification to cancel ongoing operations for a session.
//
// See protocol docs: [Cancellation](https://agentclientprotocol.com/protocol/prompt-turn#cancellation)
type CancelNotification struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	SessionID SessionID      `json:"sessionId"`
}

// Capabilities supported by the client.
//
// Advertised during initialization to inform the agent about
// available features and methods.
//
// See protocol docs: [Client Capabilities](https://agentclientprotocol.com/protocol/initialization#client-capabilities)
type ClientCapabilities struct {
	Meta     map[string]any          `json:"_meta,omitempty"`
	Auth     *AuthCapabilities       `json:"auth,omitempty"`
	FS       *FileSystemCapabilities `json:"fs,omitempty"`
	Terminal bool                    `json:"terminal,omitempty"`
}

// Session configuration options have been updated.
type ConfigOptionUpdate struct {
	Meta          map[string]any        `json:"_meta,omitempty"`
	ConfigOptions []SessionConfigOption `json:"configOptions"`
}

// Standard content block (text, images, resources).
type Content struct {
	Meta    map[string]any `json:"_meta,omitempty"`
	Content ContentBlock   `json:"content"`
}

// A streamed item of content
type ContentChunk struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	Content   ContentBlock   `json:"content"`
	MessageID string         `json:"messageId,omitempty"`
}

// Request to create a new terminal and execute a command.
type CreateTerminalRequest struct {
	Meta            map[string]any `json:"_meta,omitempty"`
	Args            []string       `json:"args,omitempty"`
	Command         string         `json:"command"`
	Cwd             string         `json:"cwd,omitempty"`
	Env             []EnvVariable  `json:"env,omitempty"`
	OutputByteLimit *int64         `json:"outputByteLimit,omitempty"`
	SessionID       SessionID      `json:"sessionId"`
}

// Response containing the ID of the created terminal.
type CreateTerminalResponse struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	TerminalID string         `json:"terminalId"`
}

// The current mode of the session has changed
//
// See protocol docs: [Session Modes](https://agentclientprotocol.com/protocol/session-modes)
type CurrentModeUpdate struct {
	Meta          map[string]any `json:"_meta,omitempty"`
	CurrentModeID SessionModeID  `json:"currentModeId"`
}

// A diff representing file modifications.
//
// Shows changes to files in a format suitable for display in the client UI.
//
// See protocol docs: [Content](https://agentclientprotocol.com/protocol/tool-calls#content)
type Diff struct {
	Meta    map[string]any `json:"_meta,omitempty"`
	NewText string         `json:"newText"`
	OldText string         `json:"oldText,omitempty"`
	Path    string         `json:"path"`
}

// The contents of a resource, embedded into a prompt or tool call result.
type EmbeddedResource struct {
	Meta        map[string]any           `json:"_meta,omitempty"`
	Annotations *Annotations             `json:"annotations,omitempty"`
	Resource    EmbeddedResourceResource `json:"resource"`
}

// An environment variable to set when launching an MCP server.
type EnvVariable struct {
	Meta  map[string]any `json:"_meta,omitempty"`
	Name  string         `json:"name"`
	Value string         `json:"value"`
}

// JSON-RPC error object.
//
// Represents an error that occurred during method execution, following the
// JSON-RPC 2.0 error object specification with optional additional data.
//
// See protocol docs: [JSON-RPC Error Object](https://www.jsonrpc.org/specification#error_object)
type Error struct {
	Code    ErrorCode       `json:"code"`
	Data    json.RawMessage `json:"data,omitempty"`
	Message string          `json:"message"`
}

// File system capabilities that a client may support.
//
// See protocol docs: [FileSystem](https://agentclientprotocol.com/protocol/initialization#filesystem)
type FileSystemCapabilities struct {
	Meta          map[string]any `json:"_meta,omitempty"`
	ReadTextFile  bool           `json:"readTextFile,omitempty"`
	WriteTextFile bool           `json:"writeTextFile,omitempty"`
}

// An HTTP header to set when making requests to the MCP server.
type HTTPHeader struct {
	Meta  map[string]any `json:"_meta,omitempty"`
	Name  string         `json:"name"`
	Value string         `json:"value"`
}

// An image provided to or from an LLM.
type ImageContent struct {
	Meta        map[string]any `json:"_meta,omitempty"`
	Annotations *Annotations   `json:"annotations,omitempty"`
	Data        string         `json:"data"`
	MimeType    string         `json:"mimeType"`
	URI         string         `json:"uri,omitempty"`
}

// Metadata about the implementation of the client or agent.
// Describes the name and version of an MCP implementation, with an optional
// title for UI representation.
type Implementation struct {
	Meta    map[string]any `json:"_meta,omitempty"`
	Name    string         `json:"name"`
	Title   string         `json:"title,omitempty"`
	Version string         `json:"version"`
}

// Request parameters for the initialize method.
//
// Sent by the client to establish connection and negotiate capabilities.
//
// See protocol docs: [Initialization](https://agentclientprotocol.com/protocol/initialization)
type InitializeRequest struct {
	Meta               map[string]any      `json:"_meta,omitempty"`
	ClientCapabilities *ClientCapabilities `json:"clientCapabilities,omitempty"`
	ClientInfo         *Implementation     `json:"clientInfo,omitempty"`
	ProtocolVersion    ProtocolVersion     `json:"protocolVersion"`
}

// Response to the `initialize` method.
//
// Contains the negotiated protocol version and agent capabilities.
//
// See protocol docs: [Initialization](https://agentclientprotocol.com/protocol/initialization)
type InitializeResponse struct {
	Meta              map[string]any     `json:"_meta,omitempty"`
	AgentCapabilities *AgentCapabilities `json:"agentCapabilities,omitempty"`
	AgentInfo         *Implementation    `json:"agentInfo,omitempty"`
	AuthMethods       []AuthMethod       `json:"authMethods,omitempty"`
	ProtocolVersion   ProtocolVersion    `json:"protocolVersion"`
}

// Request to kill a terminal without releasing it.
type KillTerminalRequest struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	SessionID  SessionID      `json:"sessionId"`
	TerminalID string         `json:"terminalId"`
}

// Response to `terminal/kill` method
type KillTerminalResponse struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

// Request parameters for listing existing sessions.
//
// Only available if the Agent supports the `sessionCapabilities.list` capability.
type ListSessionsRequest struct {
	Meta   map[string]any `json:"_meta,omitempty"`
	Cursor string         `json:"cursor,omitempty"`
	Cwd    string         `json:"cwd,omitempty"`
}

// Response from listing sessions.
type ListSessionsResponse struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	NextCursor string         `json:"nextCursor,omitempty"`
	Sessions   []SessionInfo  `json:"sessions"`
}

// Request parameters for loading an existing session.
//
// Only available if the Agent supports the `loadSession` capability.
//
// See protocol docs: [Loading Sessions](https://agentclientprotocol.com/protocol/session-setup#loading-sessions)
type LoadSessionRequest struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	Cwd        string         `json:"cwd"`
	MCPServers []MCPServer    `json:"mcpServers"`
	SessionID  SessionID      `json:"sessionId"`
}

// Response from loading an existing session.
type LoadSessionResponse struct {
	Meta          map[string]any        `json:"_meta,omitempty"`
	ConfigOptions []SessionConfigOption `json:"configOptions,omitempty"`
	Models        *SessionModelState    `json:"models,omitempty"`
	Modes         *SessionModeState     `json:"modes,omitempty"`
}

// MCP capabilities supported by the agent
type MCPCapabilities struct {
	Meta map[string]any `json:"_meta,omitempty"`
	HTTP bool           `json:"http,omitempty"`
	SSE  bool           `json:"sse,omitempty"`
}

// HTTP transport configuration for MCP.
type MCPServerHTTP struct {
	Meta    map[string]any `json:"_meta,omitempty"`
	Headers []HTTPHeader   `json:"headers"`
	Name    string         `json:"name"`
	URL     string         `json:"url"`
}

// SSE transport configuration for MCP.
type MCPServerSSE struct {
	Meta    map[string]any `json:"_meta,omitempty"`
	Headers []HTTPHeader   `json:"headers"`
	Name    string         `json:"name"`
	URL     string         `json:"url"`
}

// Stdio transport configuration for MCP.
type MCPServerStdio struct {
	Meta    map[string]any `json:"_meta,omitempty"`
	Args    []string       `json:"args"`
	Command string         `json:"command"`
	Env     []EnvVariable  `json:"env"`
	Name    string         `json:"name"`
}

// Request parameters for creating a new session.
//
// See protocol docs: [Creating a Session](https://agentclientprotocol.com/protocol/session-setup#creating-a-session)
type NewSessionRequest struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	Cwd        string         `json:"cwd"`
	MCPServers []MCPServer    `json:"mcpServers"`
}

// Response from creating a new session.
//
// See protocol docs: [Creating a Session](https://agentclientprotocol.com/protocol/session-setup#creating-a-session)
type NewSessionResponse struct {
	Meta          map[string]any        `json:"_meta,omitempty"`
	ConfigOptions []SessionConfigOption `json:"configOptions,omitempty"`
	Models        *SessionModelState    `json:"models,omitempty"`
	Modes         *SessionModeState     `json:"modes,omitempty"`
	SessionID     SessionID             `json:"sessionId"`
}

// An option presented to the user when requesting permission.
type PermissionOption struct {
	Meta     map[string]any       `json:"_meta,omitempty"`
	Kind     PermissionOptionKind `json:"kind"`
	Name     string               `json:"name"`
	OptionID PermissionOptionID   `json:"optionId"`
}

// An execution plan for accomplishing complex tasks.
//
// Plans consist of multiple entries representing individual tasks or goals.
// Agents report plans to clients to provide visibility into their execution strategy.
// Plans can evolve during execution as the agent discovers new requirements or completes tasks.
//
// See protocol docs: [Agent Plan](https://agentclientprotocol.com/protocol/agent-plan)
type Plan struct {
	Meta    map[string]any `json:"_meta,omitempty"`
	Entries []PlanEntry    `json:"entries"`
}

// A single entry in the execution plan.
//
// Represents a task or goal that the assistant intends to accomplish
// as part of fulfilling the user's request.
// See protocol docs: [Plan Entries](https://agentclientprotocol.com/protocol/agent-plan#plan-entries)
type PlanEntry struct {
	Meta     map[string]any    `json:"_meta,omitempty"`
	Content  string            `json:"content"`
	Priority PlanEntryPriority `json:"priority"`
	Status   PlanEntryStatus   `json:"status"`
}

// Prompt capabilities supported by the agent in `session/prompt` requests.
//
// Baseline agent functionality requires support for [`ContentBlock::Text`]
// and [`ContentBlock::ResourceLink`] in prompt requests.
//
// Other variants must be explicitly opted in to.
// Capabilities for different types of content in prompt requests.
//
// Indicates which content types beyond the baseline (text and resource links)
// the agent can process.
//
// See protocol docs: [Prompt Capabilities](https://agentclientprotocol.com/protocol/initialization#prompt-capabilities)
type PromptCapabilities struct {
	Meta            map[string]any `json:"_meta,omitempty"`
	Audio           bool           `json:"audio,omitempty"`
	EmbeddedContext bool           `json:"embeddedContext,omitempty"`
	Image           bool           `json:"image,omitempty"`
}

// Request parameters for sending a user prompt to the agent.
//
// Contains the user's message and any additional context.
//
// See protocol docs: [User Message](https://agentclientprotocol.com/protocol/prompt-turn#1-user-message)
type PromptRequest struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	MessageID string         `json:"messageId,omitempty"`
	Prompt    []ContentBlock `json:"prompt"`
	SessionID SessionID      `json:"sessionId"`
}

// Response from processing a user prompt.
//
// See protocol docs: [Check for Completion](https://agentclientprotocol.com/protocol/prompt-turn#4-check-for-completion)
type PromptResponse struct {
	Meta          map[string]any `json:"_meta,omitempty"`
	StopReason    StopReason     `json:"stopReason"`
	Usage         *Usage         `json:"usage,omitempty"`
	UserMessageID string         `json:"userMessageId,omitempty"`
}

// Request to read content from a text file.
//
// Only available if the client supports the `fs.readTextFile` capability.
type ReadTextFileRequest struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	Limit     *int64         `json:"limit,omitempty"`
	Line      *int64         `json:"line,omitempty"`
	Path      string         `json:"path"`
	SessionID SessionID      `json:"sessionId"`
}

// Response containing the contents of a text file.
type ReadTextFileResponse struct {
	Meta    map[string]any `json:"_meta,omitempty"`
	Content string         `json:"content"`
}

// Request to release a terminal and free its resources.
type ReleaseTerminalRequest struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	SessionID  SessionID      `json:"sessionId"`
	TerminalID string         `json:"terminalId"`
}

// Response to terminal/release method
type ReleaseTerminalResponse struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

// Request for user permission to execute a tool call.
//
// Sent when the agent needs authorization before performing a sensitive operation.
//
// See protocol docs: [Requesting Permission](https://agentclientprotocol.com/protocol/tool-calls#requesting-permission)
type RequestPermissionRequest struct {
	Meta      map[string]any     `json:"_meta,omitempty"`
	Options   []PermissionOption `json:"options"`
	SessionID SessionID          `json:"sessionId"`
	ToolCall  ToolCallUpdate     `json:"toolCall"`
}

// Response to a permission request.
type RequestPermissionResponse struct {
	Meta    map[string]any           `json:"_meta,omitempty"`
	Outcome RequestPermissionOutcome `json:"outcome"`
}

// A resource that the server is capable of reading, included in a prompt or tool call result.
type ResourceLink struct {
	Meta        map[string]any `json:"_meta,omitempty"`
	Annotations *Annotations   `json:"annotations,omitempty"`
	Description string         `json:"description,omitempty"`
	MimeType    string         `json:"mimeType,omitempty"`
	Name        string         `json:"name"`
	Size        *int64         `json:"size,omitempty"`
	Title       string         `json:"title,omitempty"`
	URI         string         `json:"uri"`
}

// The user selected one of the provided options.
type SelectedPermissionOutcome struct {
	Meta     map[string]any     `json:"_meta,omitempty"`
	OptionID PermissionOptionID `json:"optionId"`
}

// Session capabilities supported by the agent.
//
// As a baseline, all Agents **MUST** support `session/new`, `session/prompt`, `session/cancel`, and `session/update`.
//
// Optionally, they **MAY** support other session methods and notifications by specifying additional capabilities.
//
// Note: `session/load` is still handled by the top-level `load_session` capability. This will be unified in future versions of the protocol.
//
// See protocol docs: [Session Capabilities](https://agentclientprotocol.com/protocol/initialization#session-capabilities)
type SessionCapabilities struct {
	Meta   map[string]any             `json:"_meta,omitempty"`
	Close  *SessionCloseCapabilities  `json:"close,omitempty"`
	Fork   *SessionForkCapabilities   `json:"fork,omitempty"`
	List   *SessionListCapabilities   `json:"list,omitempty"`
	Resume *SessionResumeCapabilities `json:"resume,omitempty"`
}

// A single-value selector (dropdown) session configuration option payload.
type SessionConfigSelect struct {
	CurrentValue SessionConfigValueID       `json:"currentValue"`
	Options      SessionConfigSelectOptions `json:"options"`
}

// A group of possible values for a session configuration option.
type SessionConfigSelectGroup struct {
	Meta    map[string]any              `json:"_meta,omitempty"`
	Group   SessionConfigGroupID        `json:"group"`
	Name    string                      `json:"name"`
	Options []SessionConfigSelectOption `json:"options"`
}

// A possible value for a session configuration option.
type SessionConfigSelectOption struct {
	Meta        map[string]any       `json:"_meta,omitempty"`
	Description string               `json:"description,omitempty"`
	Name        string               `json:"name"`
	Value       SessionConfigValueID `json:"value"`
}

// Information about a session returned by session/list
type SessionInfo struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	Cwd       string         `json:"cwd"`
	SessionID SessionID      `json:"sessionId"`
	Title     string         `json:"title,omitempty"`
	UpdatedAt string         `json:"updatedAt,omitempty"`
}

// Update to session metadata. All fields are optional to support partial updates.
//
// Agents send this notification to update session information like title or custom metadata.
// This allows clients to display dynamic session names and track session state changes.
type SessionInfoUpdate struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	Title     string         `json:"title,omitempty"`
	UpdatedAt string         `json:"updatedAt,omitempty"`
}

// Capabilities for the `session/list` method.
//
// By supplying `{}` it means that the agent supports listing of sessions.
type SessionListCapabilities struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

// A mode the agent can operate in.
//
// See protocol docs: [Session Modes](https://agentclientprotocol.com/protocol/session-modes)
type SessionMode struct {
	Meta        map[string]any `json:"_meta,omitempty"`
	Description string         `json:"description,omitempty"`
	ID          SessionModeID  `json:"id"`
	Name        string         `json:"name"`
}

// The set of modes and the one currently active.
type SessionModeState struct {
	Meta           map[string]any `json:"_meta,omitempty"`
	AvailableModes []SessionMode  `json:"availableModes"`
	CurrentModeID  SessionModeID  `json:"currentModeId"`
}

// Notification containing a session update from the agent.
//
// Used to stream real-time progress and results during prompt processing.
//
// See protocol docs: [Agent Reports Output](https://agentclientprotocol.com/protocol/prompt-turn#3-agent-reports-output)
type SessionNotification struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	SessionID SessionID      `json:"sessionId"`
	Update    SessionUpdate  `json:"update"`
}

// Request parameters for setting a session configuration option.
type SetSessionConfigOptionRequest struct {
	Meta      map[string]any       `json:"_meta,omitempty"`
	ConfigID  SessionConfigID      `json:"configId"`
	SessionID SessionID            `json:"sessionId"`
	Value     SessionConfigValueID `json:"value"`
}

// Response to `session/set_config_option` method.
type SetSessionConfigOptionResponse struct {
	Meta          map[string]any        `json:"_meta,omitempty"`
	ConfigOptions []SessionConfigOption `json:"configOptions"`
}

// Request parameters for setting a session mode.
type SetSessionModeRequest struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	ModeID    SessionModeID  `json:"modeId"`
	SessionID SessionID      `json:"sessionId"`
}

// Response to `session/set_mode` method.
type SetSessionModeResponse struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

// Embed a terminal created with `terminal/create` by its id.
//
// The terminal must be added before calling `terminal/release`.
//
// See protocol docs: [Terminal](https://agentclientprotocol.com/protocol/terminals)
type Terminal struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	TerminalID string         `json:"terminalId"`
}

// Exit status of a terminal command.
type TerminalExitStatus struct {
	Meta     map[string]any `json:"_meta,omitempty"`
	ExitCode *int64         `json:"exitCode,omitempty"`
	Signal   string         `json:"signal,omitempty"`
}

// Request to get the current output and status of a terminal.
type TerminalOutputRequest struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	SessionID  SessionID      `json:"sessionId"`
	TerminalID string         `json:"terminalId"`
}

// Response containing the terminal output and exit status.
type TerminalOutputResponse struct {
	Meta       map[string]any      `json:"_meta,omitempty"`
	ExitStatus *TerminalExitStatus `json:"exitStatus,omitempty"`
	Output     string              `json:"output"`
	Truncated  bool                `json:"truncated"`
}

// Text provided to or from an LLM.
type TextContent struct {
	Meta        map[string]any `json:"_meta,omitempty"`
	Annotations *Annotations   `json:"annotations,omitempty"`
	Text        string         `json:"text"`
}

// Text-based resource contents.
type TextResourceContents struct {
	Meta     map[string]any `json:"_meta,omitempty"`
	MimeType string         `json:"mimeType,omitempty"`
	Text     string         `json:"text"`
	URI      string         `json:"uri"`
}

// Represents a tool call that the language model has requested.
//
// Tool calls are actions that the agent executes on behalf of the language model,
// such as reading files, executing code, or fetching data from external sources.
//
// See protocol docs: [Tool Calls](https://agentclientprotocol.com/protocol/tool-calls)
type ToolCall struct {
	Meta       map[string]any     `json:"_meta,omitempty"`
	Content    []ToolCallContent  `json:"content,omitempty"`
	Kind       *ToolKind          `json:"kind,omitempty"`
	Locations  []ToolCallLocation `json:"locations,omitempty"`
	RawInput   json.RawMessage    `json:"rawInput,omitempty"`
	RawOutput  json.RawMessage    `json:"rawOutput,omitempty"`
	Status     *ToolCallStatus    `json:"status,omitempty"`
	Title      string             `json:"title"`
	ToolCallID ToolCallID         `json:"toolCallId"`
}

// A file location being accessed or modified by a tool.
//
// Enables clients to implement "follow-along" features that track
// which files the agent is working with in real-time.
//
// See protocol docs: [Following the Agent](https://agentclientprotocol.com/protocol/tool-calls#following-the-agent)
type ToolCallLocation struct {
	Meta map[string]any `json:"_meta,omitempty"`
	Line *int64         `json:"line,omitempty"`
	Path string         `json:"path"`
}

// An update to an existing tool call.
//
// Used to report progress and results as tools execute. All fields except
// the tool call ID are optional - only changed fields need to be included.
//
// See protocol docs: [Updating](https://agentclientprotocol.com/protocol/tool-calls#updating)
type ToolCallUpdate struct {
	Meta       map[string]any     `json:"_meta,omitempty"`
	Content    []ToolCallContent  `json:"content,omitempty"`
	Kind       *ToolKind          `json:"kind,omitempty"`
	Locations  []ToolCallLocation `json:"locations,omitempty"`
	RawInput   json.RawMessage    `json:"rawInput,omitempty"`
	RawOutput  json.RawMessage    `json:"rawOutput,omitempty"`
	Status     *ToolCallStatus    `json:"status,omitempty"`
	Title      string             `json:"title,omitempty"`
	ToolCallID ToolCallID         `json:"toolCallId"`
}

// All text that was typed after the command name is provided as input.
type UnstructuredCommandInput struct {
	Meta map[string]any `json:"_meta,omitempty"`
	Hint string         `json:"hint"`
}

// Request to wait for a terminal command to exit.
type WaitForTerminalExitRequest struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	SessionID  SessionID      `json:"sessionId"`
	TerminalID string         `json:"terminalId"`
}

// Response containing the exit status of a terminal command.
type WaitForTerminalExitResponse struct {
	Meta     map[string]any `json:"_meta,omitempty"`
	ExitCode *int64         `json:"exitCode,omitempty"`
	Signal   string         `json:"signal,omitempty"`
}

// Request to write content to a text file.
//
// Only available if the client supports the `fs.writeTextFile` capability.
type WriteTextFileRequest struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	Content   string         `json:"content"`
	Path      string         `json:"path"`
	SessionID SessionID      `json:"sessionId"`
}

// Response to `fs/write_text_file`
type WriteTextFileResponse struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

// Unique identifier for a permission option.
type PermissionOptionID string

// Protocol version identifier.
//
// This version is only bumped for breaking changes.
// Non-breaking changes should be introduced via capabilities.
type ProtocolVersion int64

// JSON RPC Request Id
//
// An identifier established by the Client that MUST contain a String, Number, or NULL value if included. If it is not included it is assumed to be a notification. The value SHOULD normally not be Null [1] and Numbers SHOULD NOT contain fractional parts [2]
//
// The Server MUST reply with the same value in the Response object if included. This member is used to correlate the context between the two objects.
//
// [1] The use of Null as a value for the id member in a Request object is discouraged, because this specification uses a value of Null for Responses with an unknown id. Also, because JSON-RPC 1.0 uses an id value of Null for Notifications this could cause confusion in handling.
//
// [2] Fractional parts may be problematic, since many decimal fractions cannot be represented exactly as binary fractions.
type RequestID any

// Unique identifier for a session configuration option value group.
type SessionConfigGroupID string

// Unique identifier for a session configuration option.
type SessionConfigID string

// Unique identifier for a session configuration option value.
type SessionConfigValueID string

// A unique identifier for a conversation session between a client and agent.
//
// Sessions maintain their own context, conversation history, and state,
// allowing multiple independent interactions with the same agent.
//
// See protocol docs: [Session ID](https://agentclientprotocol.com/protocol/session-setup#session-id)
type SessionID string

// Unique identifier for a Session Mode.
type SessionModeID string

// Unique identifier for a tool call within a session.
type ToolCallID string

// Describes an available authentication method.
//
// The `type` field acts as the discriminator in the serialized JSON form.
// When no `type` is present, the method is treated as `agent`.
type AuthMethod = AuthMethodAgent

// The input specification for a command.
type AvailableCommandInput = UnstructuredCommandInput

// Resource content that can be embedded in a message.
type EmbeddedResourceResource any

const (
	// Current protocol version from metadata
	CurrentProtocolVersion int = 1
)

// Agent method names (unstable)
var AgentMethods = struct {
	Authenticate           string
	Initialize             string
	SessionCancel          string
	SessionList            string
	SessionLoad            string
	SessionNew             string
	SessionPrompt          string
	SessionSetConfigOption string
	SessionSetMode         string
}{Authenticate: "authenticate", Initialize: "initialize", SessionCancel: "session/cancel", SessionList: "session/list", SessionLoad: "session/load", SessionNew: "session/new", SessionPrompt: "session/prompt", SessionSetConfigOption: "session/set_config_option", SessionSetMode: "session/set_mode"}

// Client method names (unstable)
var ClientMethods = struct {
	FSReadTextFile           string
	FSWriteTextFile          string
	SessionRequestPermission string
	SessionUpdate            string
	TerminalCreate           string
	TerminalKill             string
	TerminalOutput           string
	TerminalRelease          string
	TerminalWaitForExit      string
}{FSReadTextFile: "fs/read_text_file", FSWriteTextFile: "fs/write_text_file", SessionRequestPermission: "session/request_permission", SessionUpdate: "session/update", TerminalCreate: "terminal/create", TerminalKill: "terminal/kill", TerminalOutput: "terminal/output", TerminalRelease: "terminal/release", TerminalWaitForExit: "terminal/wait_for_exit"}
