// Code generated by acp-schema from the method table; DO NOT EDIT.

package acp2

// The hand-written half of each façade provides AgentSideConnection and
// ClientSideConnection with a conn *jsonrpc.Connection field and an agent or
// client field holding the served interface; the lifecycle and extension
// methods every connection shares, and everything routed by method name, are
// generated here.

import (
	"context"
	"encoding/json/jsontext"

	acp "github.com/ironpark/acp-go"
	"github.com/ironpark/acp-go/internal/acpconn"
	"github.com/ironpark/acp-go/internal/jsonrpc"
	schema "github.com/ironpark/acp-go/schema/v2"
)

// Agent is the set of methods every ACP v2 agent must handle. Implement the
// optional interfaces for the rest; unimplemented methods are answered with
// "method not found".
type Agent interface {
	// Initialize negotiates the protocol version and exchanges capabilities.
	Initialize(ctx context.Context, params *InitializeRequest) (*InitializeResponse, error)

	// NewSession creates a conversation session with its own context.
	NewSession(ctx context.Context, params *NewSessionRequest) (*NewSessionResponse, error)

	// Prompt runs one prompt turn and returns once it stops.
	Prompt(ctx context.Context, params *PromptRequest) (*PromptResponse, error)

	// CancelSession is a notification asking the agent to abort the current
	// turn. The pending Prompt call should return with the cancelled outcome.
	CancelSession(ctx context.Context, params *CancelSessionNotification) error
}

// AuthHandler handles auth/login and auth/logout. Advertise it with the
// `capabilities.auth` agent capability.
type AuthHandler interface {
	Login(ctx context.Context, params *LoginAuthRequest) (*LoginAuthResponse, error)

	Logout(ctx context.Context, params *LogoutAuthRequest) (*LogoutAuthResponse, error)
}

// SessionLister handles session/list.
type SessionLister interface {
	ListSessions(ctx context.Context, params *ListSessionsRequest) (*ListSessionsResponse, error)
}

// SessionDeleter handles session/delete. Advertise it with the
// `capabilities.session.delete` agent capability.
type SessionDeleter interface {
	DeleteSession(ctx context.Context, params *DeleteSessionRequest) (*DeleteSessionResponse, error)
}

// SessionForker handles session/fork. Advertise it with the
// `capabilities.session.fork` agent capability.
//
// Experimental: not part of the spec yet; it may change or be removed.
type SessionForker interface {
	ForkSession(ctx context.Context, params *ForkSessionRequest) (*ForkSessionResponse, error)
}

// SessionResumer handles session/resume, continuing a session. v2 has no
// session/load: when the request's ReplayFrom asks for it, the agent replays
// the history it retains before answering.
type SessionResumer interface {
	ResumeSession(ctx context.Context, params *ResumeSessionRequest) (*ResumeSessionResponse, error)
}

// SessionCloser handles session/close.
type SessionCloser interface {
	CloseSession(ctx context.Context, params *CloseSessionRequest) (*CloseSessionResponse, error)
}

// SessionConfigOptionSetter handles session/set_config_option. The response
// carries every option and its current value, since changing one option may
// change the others.
type SessionConfigOptionSetter interface {
	SetSessionConfigOption(ctx context.Context, params *SetSessionConfigOptionRequest) (*SetSessionConfigOptionResponse, error)
}

// ProviderManager handles the providers/* methods. Advertise them with the
// `capabilities.providers` agent capability.
//
// Experimental: not part of the spec yet; it may change or be removed.
type ProviderManager interface {
	ListProviders(ctx context.Context, params *ListProvidersRequest) (*ListProvidersResponse, error)

	SetProvider(ctx context.Context, params *SetProviderRequest) (*SetProviderResponse, error)

	DisableProvider(ctx context.Context, params *DisableProviderRequest) (*DisableProviderResponse, error)
}

// NesHandler handles the nes/* methods for Next Edit Suggestions. Advertise
// them with the `capabilities.nes` agent capability. AcceptNes and RejectNes
// are notifications.
//
// Experimental: not part of the spec yet; it may change or be removed.
type NesHandler interface {
	StartNes(ctx context.Context, params *StartNesRequest) (*StartNesResponse, error)

	SuggestNes(ctx context.Context, params *SuggestNesRequest) (*SuggestNesResponse, error)

	CloseNes(ctx context.Context, params *CloseNesRequest) (*CloseNesResponse, error)

	AcceptNes(ctx context.Context, params *AcceptNesNotification) error

	RejectNes(ctx context.Context, params *RejectNesNotification) error
}

// DocumentHandler receives the document/did* notifications that mirror the
// client's open editors.
//
// Experimental: not part of the spec yet; it may change or be removed.
type DocumentHandler interface {
	DidOpenDocument(ctx context.Context, params *DidOpenDocumentNotification) error

	DidChangeDocument(ctx context.Context, params *DidChangeDocumentNotification) error

	DidCloseDocument(ctx context.Context, params *DidCloseDocumentNotification) error

	DidSaveDocument(ctx context.Context, params *DidSaveDocumentNotification) error

	DidFocusDocument(ctx context.Context, params *DidFocusDocumentNotification) error
}

// MCPMessageHandler receives the request-scoped MCP notifications, such as
// progress, that an MCP server the client provides sends over mcp/message
// while it works on a request the agent made.
//
// Experimental: not part of the spec yet; it may change or be removed.
type MCPMessageHandler interface {
	NotifyMCP(ctx context.Context, params *MessageMCPNotification) error
}

// Client is the set of methods every ACP v2 client must handle. MCP and
// elicitation support are optional; implement the matching interface and
// advertise the capability from `InitializeRequest.Capabilities`.
type Client interface {
	// SessionUpdate is a notification streaming turn progress to the user.
	//
	// Notifications are handled one at a time, in order, off the loop that reads
	// the connection, so a slow handler holds back neither the agent's messages
	// nor $/cancel_request. Updates stay ahead of the prompt response, and a
	// request from the agent is handled only after the updates sent before it.
	// A handler may call the agent and wait for the answer, unless answering needs
	// a request back to the client: that request waits for the handler to return.
	// Hand such calls to a goroutine.
	SessionUpdate(ctx context.Context, params *UpdateSessionNotification) error

	// RequestPermission asks the user to authorize a tool call. When the turn
	// is cancelled the client MUST answer with the cancelled outcome rather
	// than leaving the request pending.
	RequestPermission(ctx context.Context, params *RequestPermissionRequest) (*RequestPermissionResponse, error)
}

// MCPProvider serves the MCP servers the client lists with the "acp"
// transport in session setup. Each mcp/message request is one MCP operation for
// the server its serverId names, identified by its own requestId; there is no
// MCP connection or initialization handshake. In v2 this replaces the v1 fs/*
// and terminal/* methods.
//
// Experimental: not part of the spec yet; it may change or be removed.
type MCPProvider interface {
	MessageMCP(ctx context.Context, params *MessageMCPRequest) (*MessageMCPResponse, error)
}

// ElicitationHandler handles elicitation/create and the elicitation/complete
// notification. Advertise it with the `capabilities.elicitation` client
// capability.
type ElicitationHandler interface {
	CreateElicitation(ctx context.Context, params *CreateElicitationRequest) (*CreateElicitationResponse, error)

	CompleteElicitation(ctx context.Context, params *CompleteElicitationNotification) error
}

var _ acp.Conn = (*AgentSideConnection)(nil)

// Start processes messages until the peer disconnects or ctx is cancelled.
func (c *AgentSideConnection) Start(ctx context.Context) error { return c.conn.Start(ctx) }

// Close shuts the connection down, waiting for in-flight handlers.
func (c *AgentSideConnection) Close() error { return c.conn.Close() }

// Done is closed once the connection stops.
func (c *AgentSideConnection) Done() <-chan struct{} { return c.conn.Done() }

// ExtMethod sends a request outside the spec and returns its raw result.
func (c *AgentSideConnection) ExtMethod(ctx context.Context, method string, params any) (jsontext.Value, error) {
	return c.conn.SendRequest(ctx, method, params)
}

// ExtNotification sends a notification outside the spec.
func (c *AgentSideConnection) ExtNotification(ctx context.Context, method string, params any) error {
	return c.conn.SendNotification(ctx, method, params)
}

var _ acp.Conn = (*ClientSideConnection)(nil)

// Start processes messages until the peer disconnects or ctx is cancelled.
func (c *ClientSideConnection) Start(ctx context.Context) error { return c.conn.Start(ctx) }

// Close shuts the connection down, waiting for in-flight handlers.
func (c *ClientSideConnection) Close() error { return c.conn.Close() }

// Done is closed once the connection stops.
func (c *ClientSideConnection) Done() <-chan struct{} { return c.conn.Done() }

// ExtMethod sends a request outside the spec and returns its raw result.
func (c *ClientSideConnection) ExtMethod(ctx context.Context, method string, params any) (jsontext.Value, error) {
	return c.conn.SendRequest(ctx, method, params)
}

// ExtNotification sends a notification outside the spec.
func (c *ClientSideConnection) ExtNotification(ctx context.Context, method string, params any) error {
	return c.conn.SendNotification(ctx, method, params)
}

// --- Outgoing calls from ClientSideConnection to the peer ---

// Initialize negotiates the protocol version and exchanges capabilities. It is
// the first call on every connection. A zero ProtocolVersion, or nil params, sends
// [ProtocolVersion]. An agent that only speaks v1 answers
// with ProtocolVersion 1 and a v1-shaped response; reconnect with the v1
// package in that case.
func (c *ClientSideConnection) Initialize(ctx context.Context, params *InitializeRequest) (*InitializeResponse, error) {
	return c.initialize(ctx, params)
}

// NewSession creates a session. It may fail with an auth-required error.
func (c *ClientSideConnection) NewSession(ctx context.Context, params *NewSessionRequest) (*NewSessionResponse, error) {
	return acpconn.Call[NewSessionResponse](ctx, c.conn, schema.AgentMethodsSessionNew, params)
}

// Prompt runs one prompt turn and returns once the agent stops. Cancelling
// ctx cancels the JSON-RPC request; to cancel the turn itself with the
// protocol's own semantics, send [ClientSideConnection.CancelSession].
func (c *ClientSideConnection) Prompt(ctx context.Context, params *PromptRequest) (*PromptResponse, error) {
	return acpconn.Call[PromptResponse](ctx, c.conn, schema.AgentMethodsSessionPrompt, params)
}

// CancelSession asks the agent to end the current turn.
func (c *ClientSideConnection) CancelSession(ctx context.Context, params *CancelSessionNotification) error {
	return c.conn.SendNotification(ctx, schema.AgentMethodsSessionCancel, params)
}

// Login authenticates with one of the methods the agent advertised.
func (c *ClientSideConnection) Login(ctx context.Context, params *LoginAuthRequest) (*LoginAuthResponse, error) {
	return acpconn.Call[LoginAuthResponse](ctx, c.conn, schema.AgentMethodsAuthLogin, params)
}

// Logout clears the credentials the agent holds.
func (c *ClientSideConnection) Logout(ctx context.Context, params *LogoutAuthRequest) (*LogoutAuthResponse, error) {
	return acpconn.Call[LogoutAuthResponse](ctx, c.conn, schema.AgentMethodsAuthLogout, params)
}

// ListSessions lists sessions, optionally filtered and paginated.
func (c *ClientSideConnection) ListSessions(ctx context.Context, params *ListSessionsRequest) (*ListSessionsResponse, error) {
	return acpconn.Call[ListSessionsResponse](ctx, c.conn, schema.AgentMethodsSessionList, params)
}

// DeleteSession deletes a session and its stored history.
func (c *ClientSideConnection) DeleteSession(ctx context.Context, params *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return acpconn.Call[DeleteSessionResponse](ctx, c.conn, schema.AgentMethodsSessionDelete, params)
}

// ForkSession branches a session so work continues without touching the
// original history.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) ForkSession(ctx context.Context, params *ForkSessionRequest) (*ForkSessionResponse, error) {
	return acpconn.Call[ForkSessionResponse](ctx, c.conn, schema.AgentMethodsSessionFork, params)
}

// ResumeSession continues a session, replaying its history first when
// ReplayFrom asks for it.
func (c *ClientSideConnection) ResumeSession(ctx context.Context, params *ResumeSessionRequest) (*ResumeSessionResponse, error) {
	return acpconn.Call[ResumeSessionResponse](ctx, c.conn, schema.AgentMethodsSessionResume, params)
}

// CloseSession cancels any ongoing work and frees the session's resources.
func (c *ClientSideConnection) CloseSession(ctx context.Context, params *CloseSessionRequest) (*CloseSessionResponse, error) {
	return acpconn.Call[CloseSessionResponse](ctx, c.conn, schema.AgentMethodsSessionClose, params)
}

// SetSessionConfigOption sets one configuration option. The response returns
// every option, since one change may affect the others.
func (c *ClientSideConnection) SetSessionConfigOption(ctx context.Context, params *SetSessionConfigOptionRequest) (*SetSessionConfigOptionResponse, error) {
	return acpconn.Call[SetSessionConfigOptionResponse](ctx, c.conn, schema.AgentMethodsSessionSetConfigOption, params)
}

// ListProviders lists the model providers the agent can use.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) ListProviders(ctx context.Context, params *ListProvidersRequest) (*ListProvidersResponse, error) {
	return acpconn.Call[ListProvidersResponse](ctx, c.conn, schema.AgentMethodsProvidersList, params)
}

// SetProvider configures one provider.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) SetProvider(ctx context.Context, params *SetProviderRequest) (*SetProviderResponse, error) {
	return acpconn.Call[SetProviderResponse](ctx, c.conn, schema.AgentMethodsProvidersSet, params)
}

// DisableProvider turns one provider off.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) DisableProvider(ctx context.Context, params *DisableProviderRequest) (*DisableProviderResponse, error) {
	return acpconn.Call[DisableProviderResponse](ctx, c.conn, schema.AgentMethodsProvidersDisable, params)
}

// StartNes starts a Next Edit Suggestions stream.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) StartNes(ctx context.Context, params *StartNesRequest) (*StartNesResponse, error) {
	return acpconn.Call[StartNesResponse](ctx, c.conn, schema.AgentMethodsNesStart, params)
}

// SuggestNes asks for the next edit suggestion.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) SuggestNes(ctx context.Context, params *SuggestNesRequest) (*SuggestNesResponse, error) {
	return acpconn.Call[SuggestNesResponse](ctx, c.conn, schema.AgentMethodsNesSuggest, params)
}

// CloseNes ends a Next Edit Suggestions stream.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) CloseNes(ctx context.Context, params *CloseNesRequest) (*CloseNesResponse, error) {
	return acpconn.Call[CloseNesResponse](ctx, c.conn, schema.AgentMethodsNesClose, params)
}

// AcceptNes reports that the user accepted a suggestion.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) AcceptNes(ctx context.Context, params *AcceptNesNotification) error {
	return c.conn.SendNotification(ctx, schema.AgentMethodsNesAccept, params)
}

// RejectNes reports that the user rejected a suggestion.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) RejectNes(ctx context.Context, params *RejectNesNotification) error {
	return c.conn.SendNotification(ctx, schema.AgentMethodsNesReject, params)
}

// DidOpenDocument tells the agent a document was opened.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) DidOpenDocument(ctx context.Context, params *DidOpenDocumentNotification) error {
	return c.conn.SendNotification(ctx, schema.AgentMethodsDocumentDidOpen, params)
}

// DidChangeDocument tells the agent a document changed.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) DidChangeDocument(ctx context.Context, params *DidChangeDocumentNotification) error {
	return c.conn.SendNotification(ctx, schema.AgentMethodsDocumentDidChange, params)
}

// DidCloseDocument tells the agent a document was closed.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) DidCloseDocument(ctx context.Context, params *DidCloseDocumentNotification) error {
	return c.conn.SendNotification(ctx, schema.AgentMethodsDocumentDidClose, params)
}

// DidSaveDocument tells the agent a document was saved.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) DidSaveDocument(ctx context.Context, params *DidSaveDocumentNotification) error {
	return c.conn.SendNotification(ctx, schema.AgentMethodsDocumentDidSave, params)
}

// DidFocusDocument tells the agent a document was focused.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) DidFocusDocument(ctx context.Context, params *DidFocusDocumentNotification) error {
	return c.conn.SendNotification(ctx, schema.AgentMethodsDocumentDidFocus, params)
}

// NotifyMCP sends the agent a notification belonging to one of its MCP requests.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) NotifyMCP(ctx context.Context, params *MessageMCPNotification) error {
	return c.conn.SendNotification(ctx, schema.AgentMethodsMCPMessage, params)
}

// --- Outgoing calls from AgentSideConnection to the peer ---

// SessionUpdate streams turn progress to the client.
func (c *AgentSideConnection) SessionUpdate(ctx context.Context, params *UpdateSessionNotification) error {
	return c.conn.SendNotification(ctx, schema.ClientMethodsSessionUpdate, params)
}

// RequestPermission asks the user to authorize a tool call.
func (c *AgentSideConnection) RequestPermission(ctx context.Context, params *RequestPermissionRequest) (*RequestPermissionResponse, error) {
	return acpconn.Call[RequestPermissionResponse](ctx, c.conn, schema.ClientMethodsSessionRequestPermission, params)
}

// MessageMCP sends one MCP request to a server the client provides and returns
// its outcome: the MCP result, or the MCP error, which is not an ACP error.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *AgentSideConnection) MessageMCP(ctx context.Context, params *MessageMCPRequest) (*MessageMCPResponse, error) {
	return acpconn.Call[MessageMCPResponse](ctx, c.conn, schema.ClientMethodsMCPMessage, params)
}

// CreateElicitation asks the client to collect input from the user. Requires
// the client's `capabilities.elicitation` capability.
func (c *AgentSideConnection) CreateElicitation(ctx context.Context, params *CreateElicitationRequest) (*CreateElicitationResponse, error) {
	return acpconn.Call[CreateElicitationResponse](ctx, c.conn, schema.ClientMethodsElicitationCreate, params)
}

// CompleteElicitation tells the client an elicitation no longer needs an answer.
func (c *AgentSideConnection) CompleteElicitation(ctx context.Context, params *CompleteElicitationNotification) error {
	return c.conn.SendNotification(ctx, schema.ClientMethodsElicitationComplete, params)
}

func (c *AgentSideConnection) handleRequest(ctx context.Context, method string, params jsontext.Value) (any, error) {
	switch method {
	case schema.AgentMethodsInitialize:
		return acpconn.Request(ctx, schema.Validated(), params, c.agent.Initialize)
	case schema.AgentMethodsSessionNew:
		return acpconn.Request(ctx, schema.Validated(), params, c.agent.NewSession)
	case schema.AgentMethodsSessionPrompt:
		return acpconn.Request(ctx, schema.Validated(), params, c.agent.Prompt)
	case schema.AgentMethodsAuthLogin:
		if h, ok := c.agent.(AuthHandler); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.Login)
		}
	case schema.AgentMethodsAuthLogout:
		if h, ok := c.agent.(AuthHandler); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.Logout)
		}
	case schema.AgentMethodsSessionList:
		if h, ok := c.agent.(SessionLister); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.ListSessions)
		}
	case schema.AgentMethodsSessionDelete:
		if h, ok := c.agent.(SessionDeleter); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.DeleteSession)
		}
	case schema.AgentMethodsSessionFork:
		if h, ok := c.agent.(SessionForker); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.ForkSession)
		}
	case schema.AgentMethodsSessionResume:
		if h, ok := c.agent.(SessionResumer); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.ResumeSession)
		}
	case schema.AgentMethodsSessionClose:
		if h, ok := c.agent.(SessionCloser); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.CloseSession)
		}
	case schema.AgentMethodsSessionSetConfigOption:
		if h, ok := c.agent.(SessionConfigOptionSetter); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.SetSessionConfigOption)
		}
	case schema.AgentMethodsProvidersList:
		if h, ok := c.agent.(ProviderManager); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.ListProviders)
		}
	case schema.AgentMethodsProvidersSet:
		if h, ok := c.agent.(ProviderManager); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.SetProvider)
		}
	case schema.AgentMethodsProvidersDisable:
		if h, ok := c.agent.(ProviderManager); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.DisableProvider)
		}
	case schema.AgentMethodsNesStart:
		if h, ok := c.agent.(NesHandler); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.StartNes)
		}
	case schema.AgentMethodsNesSuggest:
		if h, ok := c.agent.(NesHandler); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.SuggestNes)
		}
	case schema.AgentMethodsNesClose:
		if h, ok := c.agent.(NesHandler); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.CloseNes)
		}
	default:
		if h, ok := c.agent.(ExtMethodHandler); ok {
			return h.ServeExtMethod(ctx, method, params)
		}
	}
	return nil, jsonrpc.MethodNotFound(method)
}

func (c *AgentSideConnection) handleNotification(ctx context.Context, method string, params jsontext.Value) error {
	switch method {
	case schema.AgentMethodsSessionCancel:
		return acpconn.Notify(ctx, schema.Validated(), params, c.agent.CancelSession)
	case schema.AgentMethodsNesAccept:
		if h, ok := c.agent.(NesHandler); ok {
			return acpconn.Notify(ctx, schema.Validated(), params, h.AcceptNes)
		}
	case schema.AgentMethodsNesReject:
		if h, ok := c.agent.(NesHandler); ok {
			return acpconn.Notify(ctx, schema.Validated(), params, h.RejectNes)
		}
	case schema.AgentMethodsDocumentDidOpen:
		if h, ok := c.agent.(DocumentHandler); ok {
			return acpconn.Notify(ctx, schema.Validated(), params, h.DidOpenDocument)
		}
	case schema.AgentMethodsDocumentDidChange:
		if h, ok := c.agent.(DocumentHandler); ok {
			return acpconn.Notify(ctx, schema.Validated(), params, h.DidChangeDocument)
		}
	case schema.AgentMethodsDocumentDidClose:
		if h, ok := c.agent.(DocumentHandler); ok {
			return acpconn.Notify(ctx, schema.Validated(), params, h.DidCloseDocument)
		}
	case schema.AgentMethodsDocumentDidSave:
		if h, ok := c.agent.(DocumentHandler); ok {
			return acpconn.Notify(ctx, schema.Validated(), params, h.DidSaveDocument)
		}
	case schema.AgentMethodsDocumentDidFocus:
		if h, ok := c.agent.(DocumentHandler); ok {
			return acpconn.Notify(ctx, schema.Validated(), params, h.DidFocusDocument)
		}
	case schema.AgentMethodsMCPMessage:
		if h, ok := c.agent.(MCPMessageHandler); ok {
			return acpconn.Notify(ctx, schema.Validated(), params, h.NotifyMCP)
		}
	default:
		if h, ok := c.agent.(ExtNotificationHandler); ok {
			return h.ServeExtNotification(ctx, method, params)
		}
	}
	return jsonrpc.MethodNotFound(method)
}

func (c *ClientSideConnection) handleRequest(ctx context.Context, method string, params jsontext.Value) (any, error) {
	switch method {
	case schema.ClientMethodsSessionRequestPermission:
		return acpconn.Request(ctx, schema.Validated(), params, c.client.RequestPermission)
	case schema.ClientMethodsMCPMessage:
		if h, ok := c.client.(MCPProvider); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.MessageMCP)
		}
	case schema.ClientMethodsElicitationCreate:
		if h, ok := c.client.(ElicitationHandler); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.CreateElicitation)
		}
	default:
		if h, ok := c.client.(ExtMethodHandler); ok {
			return h.ServeExtMethod(ctx, method, params)
		}
	}
	return nil, jsonrpc.MethodNotFound(method)
}

func (c *ClientSideConnection) handleNotification(ctx context.Context, method string, params jsontext.Value) error {
	switch method {
	case schema.ClientMethodsSessionUpdate:
		return acpconn.Notify(ctx, schema.Validated(), params, c.sessionUpdate)
	case schema.ClientMethodsElicitationComplete:
		if h, ok := c.client.(ElicitationHandler); ok {
			return acpconn.Notify(ctx, schema.Validated(), params, h.CompleteElicitation)
		}
	default:
		if h, ok := c.client.(ExtNotificationHandler); ok {
			return h.ServeExtNotification(ctx, method, params)
		}
	}
	return jsonrpc.MethodNotFound(method)
}
