// Code generated by acp-schema from the TypeScript SDK; DO NOT EDIT.

package schema

// GetSession returns Session, or nil if x is nil.
func (x *AgentCapabilities) GetSession() *SessionCapabilities {
	if x == nil {
		return nil
	}
	return x.Session
}

// GetAuth returns Auth, or nil if x is nil.
func (x *AgentCapabilities) GetAuth() *AgentAuthCapabilities {
	if x == nil {
		return nil
	}
	return x.Auth
}

// GetProviders returns Providers, or nil if x is nil.
func (x *AgentCapabilities) GetProviders() *ProvidersCapabilities {
	if x == nil {
		return nil
	}
	return x.Providers
}

// GetNes returns Nes, or nil if x is nil.
func (x *AgentCapabilities) GetNes() *NesCapabilities {
	if x == nil {
		return nil
	}
	return x.Nes
}

// GetPositionEncoding returns the value of PositionEncoding, or the zero value if x or PositionEncoding is nil.
func (x *AgentCapabilities) GetPositionEncoding() PositionEncodingKind {
	if x != nil && x.PositionEncoding != nil {
		return *x.PositionEncoding
	}
	var zero PositionEncodingKind
	return zero
}

// GetLastModified returns the value of LastModified, or the zero value if x or LastModified is nil.
func (x *Annotations) GetLastModified() string {
	if x != nil && x.LastModified != nil {
		return *x.LastModified
	}
	var zero string
	return zero
}

// GetPriority returns the value of Priority, or the zero value if x or Priority is nil.
func (x *Annotations) GetPriority() float64 {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	var zero float64
	return zero
}

// GetTerminal returns Terminal, or nil if x is nil.
func (x *AuthCapabilities) GetTerminal() *TerminalAuthCapabilities {
	if x == nil {
		return nil
	}
	return x.Terminal
}

// GetDescription returns the value of Description, or the zero value if x or Description is nil.
func (x *AuthMethodAgent) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	var zero string
	return zero
}

// GetDescription returns the value of Description, or the zero value if x or Description is nil.
func (x *AuthMethodCustom) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	var zero string
	return zero
}

// GetDescription returns the value of Description, or the zero value if x or Description is nil.
func (x *AuthMethodTerminal) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	var zero string
	return zero
}

// GetMIMEType returns the value of MIMEType, or the zero value if x or MIMEType is nil.
func (x *BlobResourceContents) GetMIMEType() MediaType {
	if x != nil && x.MIMEType != nil {
		return *x.MIMEType
	}
	var zero MediaType
	return zero
}

// GetAuth returns Auth, or nil if x is nil.
func (x *ClientCapabilities) GetAuth() *AuthCapabilities {
	if x == nil {
		return nil
	}
	return x.Auth
}

// GetElicitation returns Elicitation, or nil if x is nil.
func (x *ClientCapabilities) GetElicitation() *ElicitationCapabilities {
	if x == nil {
		return nil
	}
	return x.Elicitation
}

// GetNes returns Nes, or nil if x is nil.
func (x *ClientCapabilities) GetNes() *ClientNesCapabilities {
	if x == nil {
		return nil
	}
	return x.Nes
}

// GetJump returns Jump, or nil if x is nil.
func (x *ClientNesCapabilities) GetJump() *NesJumpCapabilities {
	if x == nil {
		return nil
	}
	return x.Jump
}

// GetRename returns Rename, or nil if x is nil.
func (x *ClientNesCapabilities) GetRename() *NesRenameCapabilities {
	if x == nil {
		return nil
	}
	return x.Rename
}

// GetSearchAndReplace returns SearchAndReplace, or nil if x is nil.
func (x *ClientNesCapabilities) GetSearchAndReplace() *NesSearchAndReplaceCapabilities {
	if x == nil {
		return nil
	}
	return x.SearchAndReplace
}

// GetAnnotations returns Annotations, or nil if x is nil.
func (x *ContentBlockAudio) GetAnnotations() *Annotations {
	if x == nil {
		return nil
	}
	return x.Annotations
}

// GetURI returns the value of URI, or the zero value if x or URI is nil.
func (x *ContentBlockImage) GetURI() string {
	if x != nil && x.URI != nil {
		return *x.URI
	}
	var zero string
	return zero
}

// GetAnnotations returns Annotations, or nil if x is nil.
func (x *ContentBlockImage) GetAnnotations() *Annotations {
	if x == nil {
		return nil
	}
	return x.Annotations
}

// GetAnnotations returns Annotations, or nil if x is nil.
func (x *ContentBlockResource) GetAnnotations() *Annotations {
	if x == nil {
		return nil
	}
	return x.Annotations
}

// GetTitle returns the value of Title, or the zero value if x or Title is nil.
func (x *ContentBlockResourceLink) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	var zero string
	return zero
}

// GetDescription returns the value of Description, or the zero value if x or Description is nil.
func (x *ContentBlockResourceLink) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	var zero string
	return zero
}

// GetMIMEType returns the value of MIMEType, or the zero value if x or MIMEType is nil.
func (x *ContentBlockResourceLink) GetMIMEType() MediaType {
	if x != nil && x.MIMEType != nil {
		return *x.MIMEType
	}
	var zero MediaType
	return zero
}

// GetSize returns the value of Size, or the zero value if x or Size is nil.
func (x *ContentBlockResourceLink) GetSize() int64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	var zero int64
	return zero
}

// GetAnnotations returns Annotations, or nil if x is nil.
func (x *ContentBlockResourceLink) GetAnnotations() *Annotations {
	if x == nil {
		return nil
	}
	return x.Annotations
}

// GetAnnotations returns Annotations, or nil if x is nil.
func (x *ContentBlockText) GetAnnotations() *Annotations {
	if x == nil {
		return nil
	}
	return x.Annotations
}

// GetToolCallID returns the value of ToolCallID, or the zero value if x or ToolCallID is nil.
func (x *CreateElicitationRequestCustomSession) GetToolCallID() ToolCallID {
	if x != nil && x.ToolCallID != nil {
		return *x.ToolCallID
	}
	var zero ToolCallID
	return zero
}

// GetToolCallID returns the value of ToolCallID, or the zero value if x or ToolCallID is nil.
func (x *CreateElicitationRequestFormSession) GetToolCallID() ToolCallID {
	if x != nil && x.ToolCallID != nil {
		return *x.ToolCallID
	}
	var zero ToolCallID
	return zero
}

// GetToolCallID returns the value of ToolCallID, or the zero value if x or ToolCallID is nil.
func (x *CreateElicitationRequestURLSession) GetToolCallID() ToolCallID {
	if x != nil && x.ToolCallID != nil {
		return *x.ToolCallID
	}
	var zero ToolCallID
	return zero
}

// GetFileType returns the value of FileType, or the zero value if x or FileType is nil.
func (x *DiffChangeAdd) GetFileType() DiffFileType {
	if x != nil && x.FileType != nil {
		return *x.FileType
	}
	var zero DiffFileType
	return zero
}

// GetMIMEType returns the value of MIMEType, or the zero value if x or MIMEType is nil.
func (x *DiffChangeAdd) GetMIMEType() MediaType {
	if x != nil && x.MIMEType != nil {
		return *x.MIMEType
	}
	var zero MediaType
	return zero
}

// GetFileType returns the value of FileType, or the zero value if x or FileType is nil.
func (x *DiffChangeCopy) GetFileType() DiffFileType {
	if x != nil && x.FileType != nil {
		return *x.FileType
	}
	var zero DiffFileType
	return zero
}

// GetMIMEType returns the value of MIMEType, or the zero value if x or MIMEType is nil.
func (x *DiffChangeCopy) GetMIMEType() MediaType {
	if x != nil && x.MIMEType != nil {
		return *x.MIMEType
	}
	var zero MediaType
	return zero
}

// GetFileType returns the value of FileType, or the zero value if x or FileType is nil.
func (x *DiffChangeCustom) GetFileType() DiffFileType {
	if x != nil && x.FileType != nil {
		return *x.FileType
	}
	var zero DiffFileType
	return zero
}

// GetMIMEType returns the value of MIMEType, or the zero value if x or MIMEType is nil.
func (x *DiffChangeCustom) GetMIMEType() MediaType {
	if x != nil && x.MIMEType != nil {
		return *x.MIMEType
	}
	var zero MediaType
	return zero
}

// GetFileType returns the value of FileType, or the zero value if x or FileType is nil.
func (x *DiffChangeDelete) GetFileType() DiffFileType {
	if x != nil && x.FileType != nil {
		return *x.FileType
	}
	var zero DiffFileType
	return zero
}

// GetMIMEType returns the value of MIMEType, or the zero value if x or MIMEType is nil.
func (x *DiffChangeDelete) GetMIMEType() MediaType {
	if x != nil && x.MIMEType != nil {
		return *x.MIMEType
	}
	var zero MediaType
	return zero
}

// GetFileType returns the value of FileType, or the zero value if x or FileType is nil.
func (x *DiffChangeModify) GetFileType() DiffFileType {
	if x != nil && x.FileType != nil {
		return *x.FileType
	}
	var zero DiffFileType
	return zero
}

// GetMIMEType returns the value of MIMEType, or the zero value if x or MIMEType is nil.
func (x *DiffChangeModify) GetMIMEType() MediaType {
	if x != nil && x.MIMEType != nil {
		return *x.MIMEType
	}
	var zero MediaType
	return zero
}

// GetFileType returns the value of FileType, or the zero value if x or FileType is nil.
func (x *DiffChangeMove) GetFileType() DiffFileType {
	if x != nil && x.FileType != nil {
		return *x.FileType
	}
	var zero DiffFileType
	return zero
}

// GetMIMEType returns the value of MIMEType, or the zero value if x or MIMEType is nil.
func (x *DiffChangeMove) GetMIMEType() MediaType {
	if x != nil && x.MIMEType != nil {
		return *x.MIMEType
	}
	var zero MediaType
	return zero
}

// GetForm returns Form, or nil if x is nil.
func (x *ElicitationCapabilities) GetForm() *ElicitationFormCapabilities {
	if x == nil {
		return nil
	}
	return x.Form
}

// GetURL returns URL, or nil if x is nil.
func (x *ElicitationCapabilities) GetURL() *ElicitationURLCapabilities {
	if x == nil {
		return nil
	}
	return x.URL
}

// GetToolCallID returns the value of ToolCallID, or the zero value if x or ToolCallID is nil.
func (x *ElicitationFormModeSession) GetToolCallID() ToolCallID {
	if x != nil && x.ToolCallID != nil {
		return *x.ToolCallID
	}
	var zero ToolCallID
	return zero
}

// GetTitle returns the value of Title, or the zero value if x or Title is nil.
func (x *ElicitationPropertySchemaArray) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	var zero string
	return zero
}

// GetDescription returns the value of Description, or the zero value if x or Description is nil.
func (x *ElicitationPropertySchemaArray) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	var zero string
	return zero
}

// GetMinItems returns the value of MinItems, or the zero value if x or MinItems is nil.
func (x *ElicitationPropertySchemaArray) GetMinItems() uint64 {
	if x != nil && x.MinItems != nil {
		return *x.MinItems
	}
	var zero uint64
	return zero
}

// GetMaxItems returns the value of MaxItems, or the zero value if x or MaxItems is nil.
func (x *ElicitationPropertySchemaArray) GetMaxItems() uint64 {
	if x != nil && x.MaxItems != nil {
		return *x.MaxItems
	}
	var zero uint64
	return zero
}

// GetTitle returns the value of Title, or the zero value if x or Title is nil.
func (x *ElicitationPropertySchemaBoolean) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	var zero string
	return zero
}

// GetDescription returns the value of Description, or the zero value if x or Description is nil.
func (x *ElicitationPropertySchemaBoolean) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	var zero string
	return zero
}

// GetDefault returns the value of Default, or the zero value if x or Default is nil.
func (x *ElicitationPropertySchemaBoolean) GetDefault() bool {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	var zero bool
	return zero
}

// GetTitle returns the value of Title, or the zero value if x or Title is nil.
func (x *ElicitationPropertySchemaInteger) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	var zero string
	return zero
}

// GetDescription returns the value of Description, or the zero value if x or Description is nil.
func (x *ElicitationPropertySchemaInteger) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	var zero string
	return zero
}

// GetMinimum returns the value of Minimum, or the zero value if x or Minimum is nil.
func (x *ElicitationPropertySchemaInteger) GetMinimum() int64 {
	if x != nil && x.Minimum != nil {
		return *x.Minimum
	}
	var zero int64
	return zero
}

// GetMaximum returns the value of Maximum, or the zero value if x or Maximum is nil.
func (x *ElicitationPropertySchemaInteger) GetMaximum() int64 {
	if x != nil && x.Maximum != nil {
		return *x.Maximum
	}
	var zero int64
	return zero
}

// GetDefault returns the value of Default, or the zero value if x or Default is nil.
func (x *ElicitationPropertySchemaInteger) GetDefault() int64 {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	var zero int64
	return zero
}

// GetTitle returns the value of Title, or the zero value if x or Title is nil.
func (x *ElicitationPropertySchemaNumber) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	var zero string
	return zero
}

// GetDescription returns the value of Description, or the zero value if x or Description is nil.
func (x *ElicitationPropertySchemaNumber) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	var zero string
	return zero
}

// GetMinimum returns the value of Minimum, or the zero value if x or Minimum is nil.
func (x *ElicitationPropertySchemaNumber) GetMinimum() float64 {
	if x != nil && x.Minimum != nil {
		return *x.Minimum
	}
	var zero float64
	return zero
}

// GetMaximum returns the value of Maximum, or the zero value if x or Maximum is nil.
func (x *ElicitationPropertySchemaNumber) GetMaximum() float64 {
	if x != nil && x.Maximum != nil {
		return *x.Maximum
	}
	var zero float64
	return zero
}

// GetDefault returns the value of Default, or the zero value if x or Default is nil.
func (x *ElicitationPropertySchemaNumber) GetDefault() float64 {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	var zero float64
	return zero
}

// GetTitle returns the value of Title, or the zero value if x or Title is nil.
func (x *ElicitationPropertySchemaString) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	var zero string
	return zero
}

// GetDescription returns the value of Description, or the zero value if x or Description is nil.
func (x *ElicitationPropertySchemaString) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	var zero string
	return zero
}

// GetMinLength returns the value of MinLength, or the zero value if x or MinLength is nil.
func (x *ElicitationPropertySchemaString) GetMinLength() uint32 {
	if x != nil && x.MinLength != nil {
		return *x.MinLength
	}
	var zero uint32
	return zero
}

// GetMaxLength returns the value of MaxLength, or the zero value if x or MaxLength is nil.
func (x *ElicitationPropertySchemaString) GetMaxLength() uint32 {
	if x != nil && x.MaxLength != nil {
		return *x.MaxLength
	}
	var zero uint32
	return zero
}

// GetPattern returns the value of Pattern, or the zero value if x or Pattern is nil.
func (x *ElicitationPropertySchemaString) GetPattern() string {
	if x != nil && x.Pattern != nil {
		return *x.Pattern
	}
	var zero string
	return zero
}

// GetFormat returns the value of Format, or the zero value if x or Format is nil.
func (x *ElicitationPropertySchemaString) GetFormat() StringFormat {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	var zero StringFormat
	return zero
}

// GetDefault returns the value of Default, or the zero value if x or Default is nil.
func (x *ElicitationPropertySchemaString) GetDefault() string {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	var zero string
	return zero
}

// GetType returns the value of Type, or the zero value if x or Type is nil.
func (x *ElicitationSchema) GetType() ElicitationSchemaType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	var zero ElicitationSchemaType
	return zero
}

// GetTitle returns the value of Title, or the zero value if x or Title is nil.
func (x *ElicitationSchema) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	var zero string
	return zero
}

// GetDescription returns the value of Description, or the zero value if x or Description is nil.
func (x *ElicitationSchema) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	var zero string
	return zero
}

// GetToolCallID returns the value of ToolCallID, or the zero value if x or ToolCallID is nil.
func (x *ElicitationSessionScope) GetToolCallID() ToolCallID {
	if x != nil && x.ToolCallID != nil {
		return *x.ToolCallID
	}
	var zero ToolCallID
	return zero
}

// GetToolCallID returns the value of ToolCallID, or the zero value if x or ToolCallID is nil.
func (x *ElicitationURLModeSession) GetToolCallID() ToolCallID {
	if x != nil && x.ToolCallID != nil {
		return *x.ToolCallID
	}
	var zero ToolCallID
	return zero
}

// GetDescription returns the value of Description, or the zero value if x or Description is nil.
func (x *EnumOption) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	var zero string
	return zero
}

// GetMIMEType returns the value of MIMEType, or the zero value if x or MIMEType is nil.
func (x *Icon) GetMIMEType() MediaType {
	if x != nil && x.MIMEType != nil {
		return *x.MIMEType
	}
	var zero MediaType
	return zero
}

// GetTheme returns the value of Theme, or the zero value if x or Theme is nil.
func (x *Icon) GetTheme() IconTheme {
	if x != nil && x.Theme != nil {
		return *x.Theme
	}
	var zero IconTheme
	return zero
}

// GetTitle returns the value of Title, or the zero value if x or Title is nil.
func (x *Implementation) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	var zero string
	return zero
}

// GetCapabilities returns Capabilities, or nil if x is nil.
func (x *InitializeRequest) GetCapabilities() *ClientCapabilities {
	if x == nil {
		return nil
	}
	return x.Capabilities
}

// GetCapabilities returns Capabilities, or nil if x is nil.
func (x *InitializeResponse) GetCapabilities() *AgentCapabilities {
	if x == nil {
		return nil
	}
	return x.Capabilities
}

// GetCwd returns the value of Cwd, or the zero value if x or Cwd is nil.
func (x *ListSessionsRequest) GetCwd() AbsolutePath {
	if x != nil && x.Cwd != nil {
		return *x.Cwd
	}
	var zero AbsolutePath
	return zero
}

// GetCursor returns the value of Cursor, or the zero value if x or Cursor is nil.
func (x *ListSessionsRequest) GetCursor() SessionListCursor {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	var zero SessionListCursor
	return zero
}

// GetNextCursor returns the value of NextCursor, or the zero value if x or NextCursor is nil.
func (x *ListSessionsResponse) GetNextCursor() SessionListCursor {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	var zero SessionListCursor
	return zero
}

// GetStdio returns Stdio, or nil if x is nil.
func (x *MCPCapabilities) GetStdio() *MCPStdioCapabilities {
	if x == nil {
		return nil
	}
	return x.Stdio
}

// GetHTTP returns HTTP, or nil if x is nil.
func (x *MCPCapabilities) GetHTTP() *MCPHTTPCapabilities {
	if x == nil {
		return nil
	}
	return x.HTTP
}

// GetACP returns ACP, or nil if x is nil.
func (x *MCPCapabilities) GetACP() *MCPACPCapabilities {
	if x == nil {
		return nil
	}
	return x.ACP
}

// GetEvents returns Events, or nil if x is nil.
func (x *NesCapabilities) GetEvents() *NesEventCapabilities {
	if x == nil {
		return nil
	}
	return x.Events
}

// GetContext returns Context, or nil if x is nil.
func (x *NesCapabilities) GetContext() *NesContextCapabilities {
	if x == nil {
		return nil
	}
	return x.Context
}

// GetRecentFiles returns RecentFiles, or nil if x is nil.
func (x *NesContextCapabilities) GetRecentFiles() *NesRecentFilesCapabilities {
	if x == nil {
		return nil
	}
	return x.RecentFiles
}

// GetRelatedSnippets returns RelatedSnippets, or nil if x is nil.
func (x *NesContextCapabilities) GetRelatedSnippets() *NesRelatedSnippetsCapabilities {
	if x == nil {
		return nil
	}
	return x.RelatedSnippets
}

// GetEditHistory returns EditHistory, or nil if x is nil.
func (x *NesContextCapabilities) GetEditHistory() *NesEditHistoryCapabilities {
	if x == nil {
		return nil
	}
	return x.EditHistory
}

// GetUserActions returns UserActions, or nil if x is nil.
func (x *NesContextCapabilities) GetUserActions() *NesUserActionsCapabilities {
	if x == nil {
		return nil
	}
	return x.UserActions
}

// GetOpenFiles returns OpenFiles, or nil if x is nil.
func (x *NesContextCapabilities) GetOpenFiles() *NesOpenFilesCapabilities {
	if x == nil {
		return nil
	}
	return x.OpenFiles
}

// GetDiagnostics returns Diagnostics, or nil if x is nil.
func (x *NesContextCapabilities) GetDiagnostics() *NesDiagnosticsCapabilities {
	if x == nil {
		return nil
	}
	return x.Diagnostics
}

// GetDidOpen returns DidOpen, or nil if x is nil.
func (x *NesDocumentEventCapabilities) GetDidOpen() *NesDocumentDidOpenCapabilities {
	if x == nil {
		return nil
	}
	return x.DidOpen
}

// GetDidChange returns DidChange, or nil if x is nil.
func (x *NesDocumentEventCapabilities) GetDidChange() *NesDocumentDidChangeCapabilities {
	if x == nil {
		return nil
	}
	return x.DidChange
}

// GetDidClose returns DidClose, or nil if x is nil.
func (x *NesDocumentEventCapabilities) GetDidClose() *NesDocumentDidCloseCapabilities {
	if x == nil {
		return nil
	}
	return x.DidClose
}

// GetDidSave returns DidSave, or nil if x is nil.
func (x *NesDocumentEventCapabilities) GetDidSave() *NesDocumentDidSaveCapabilities {
	if x == nil {
		return nil
	}
	return x.DidSave
}

// GetDidFocus returns DidFocus, or nil if x is nil.
func (x *NesDocumentEventCapabilities) GetDidFocus() *NesDocumentDidFocusCapabilities {
	if x == nil {
		return nil
	}
	return x.DidFocus
}

// GetMaxCount returns the value of MaxCount, or the zero value if x or MaxCount is nil.
func (x *NesEditHistoryCapabilities) GetMaxCount() uint32 {
	if x != nil && x.MaxCount != nil {
		return *x.MaxCount
	}
	var zero uint32
	return zero
}

// GetDocument returns Document, or nil if x is nil.
func (x *NesEventCapabilities) GetDocument() *NesDocumentEventCapabilities {
	if x == nil {
		return nil
	}
	return x.Document
}

// GetVisibleRange returns VisibleRange, or nil if x is nil.
func (x *NesOpenFile) GetVisibleRange() *Range {
	if x == nil {
		return nil
	}
	return x.VisibleRange
}

// GetLastFocusedMs returns the value of LastFocusedMs, or the zero value if x or LastFocusedMs is nil.
func (x *NesOpenFile) GetLastFocusedMs() uint64 {
	if x != nil && x.LastFocusedMs != nil {
		return *x.LastFocusedMs
	}
	var zero uint64
	return zero
}

// GetMaxCount returns the value of MaxCount, or the zero value if x or MaxCount is nil.
func (x *NesRecentFilesCapabilities) GetMaxCount() uint32 {
	if x != nil && x.MaxCount != nil {
		return *x.MaxCount
	}
	var zero uint32
	return zero
}

// GetCursorPosition returns CursorPosition, or nil if x is nil.
func (x *NesSuggestionEdit) GetCursorPosition() *Position {
	if x == nil {
		return nil
	}
	return x.CursorPosition
}

// GetIsRegex returns the value of IsRegex, or the zero value if x or IsRegex is nil.
func (x *NesSuggestionSearchAndReplace) GetIsRegex() bool {
	if x != nil && x.IsRegex != nil {
		return *x.IsRegex
	}
	var zero bool
	return zero
}

// GetMaxCount returns the value of MaxCount, or the zero value if x or MaxCount is nil.
func (x *NesUserActionsCapabilities) GetMaxCount() uint32 {
	if x != nil && x.MaxCount != nil {
		return *x.MaxCount
	}
	var zero uint32
	return zero
}

// GetImage returns Image, or nil if x is nil.
func (x *PromptCapabilities) GetImage() *PromptImageCapabilities {
	if x == nil {
		return nil
	}
	return x.Image
}

// GetAudio returns Audio, or nil if x is nil.
func (x *PromptCapabilities) GetAudio() *PromptAudioCapabilities {
	if x == nil {
		return nil
	}
	return x.Audio
}

// GetEmbeddedContext returns EmbeddedContext, or nil if x is nil.
func (x *PromptCapabilities) GetEmbeddedContext() *PromptEmbeddedContextCapabilities {
	if x == nil {
		return nil
	}
	return x.EmbeddedContext
}

// GetCurrent returns Current, or nil if x is nil.
func (x *ProviderInfo) GetCurrent() *ProviderCurrentConfig {
	if x == nil {
		return nil
	}
	return x.Current
}

// GetReason returns the value of Reason, or the zero value if x or Reason is nil.
func (x *RejectNesNotification) GetReason() NesRejectReason {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	var zero NesRejectReason
	return zero
}

// GetDescription returns the value of Description, or the zero value if x or Description is nil.
func (x *RequestPermissionRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	var zero string
	return zero
}

// GetToolCallID returns the value of ToolCallID, or the zero value if x or ToolCallID is nil.
func (x *RequestPermissionSubjectCommand) GetToolCallID() ToolCallID {
	if x != nil && x.ToolCallID != nil {
		return *x.ToolCallID
	}
	var zero ToolCallID
	return zero
}

// GetTerminalID returns the value of TerminalID, or the zero value if x or TerminalID is nil.
func (x *RequestPermissionSubjectCommand) GetTerminalID() TerminalID {
	if x != nil && x.TerminalID != nil {
		return *x.TerminalID
	}
	var zero TerminalID
	return zero
}

// GetPrompt returns Prompt, or nil if x is nil.
func (x *SessionCapabilities) GetPrompt() *PromptCapabilities {
	if x == nil {
		return nil
	}
	return x.Prompt
}

// GetMCP returns MCP, or nil if x is nil.
func (x *SessionCapabilities) GetMCP() *MCPCapabilities {
	if x == nil {
		return nil
	}
	return x.MCP
}

// GetDelete returns Delete, or nil if x is nil.
func (x *SessionCapabilities) GetDelete() *SessionDeleteCapabilities {
	if x == nil {
		return nil
	}
	return x.Delete
}

// GetAdditionalDirectories returns AdditionalDirectories, or nil if x is nil.
func (x *SessionCapabilities) GetAdditionalDirectories() *SessionAdditionalDirectoriesCapabilities {
	if x == nil {
		return nil
	}
	return x.AdditionalDirectories
}

// GetFork returns Fork, or nil if x is nil.
func (x *SessionCapabilities) GetFork() *SessionForkCapabilities {
	if x == nil {
		return nil
	}
	return x.Fork
}

// GetDescription returns the value of Description, or the zero value if x or Description is nil.
func (x *SessionConfigOptionBoolean) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	var zero string
	return zero
}

// GetCategory returns the value of Category, or the zero value if x or Category is nil.
func (x *SessionConfigOptionBoolean) GetCategory() SessionConfigOptionCategory {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	var zero SessionConfigOptionCategory
	return zero
}

// GetDescription returns the value of Description, or the zero value if x or Description is nil.
func (x *SessionConfigOptionCustom) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	var zero string
	return zero
}

// GetCategory returns the value of Category, or the zero value if x or Category is nil.
func (x *SessionConfigOptionCustom) GetCategory() SessionConfigOptionCategory {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	var zero SessionConfigOptionCategory
	return zero
}

// GetDescription returns the value of Description, or the zero value if x or Description is nil.
func (x *SessionConfigOptionSelect) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	var zero string
	return zero
}

// GetCategory returns the value of Category, or the zero value if x or Category is nil.
func (x *SessionConfigOptionSelect) GetCategory() SessionConfigOptionCategory {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	var zero SessionConfigOptionCategory
	return zero
}

// GetDescription returns the value of Description, or the zero value if x or Description is nil.
func (x *SessionConfigSelectOption) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	var zero string
	return zero
}

// GetTitle returns the value of Title, or the zero value if x or Title is nil.
func (x *SessionInfo) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	var zero string
	return zero
}

// GetUpdatedAt returns the value of UpdatedAt, or the zero value if x or UpdatedAt is nil.
func (x *SessionInfo) GetUpdatedAt() string {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	var zero string
	return zero
}

// GetError returns the value of Error, or the zero value if x or Error is nil.
func (x *SessionUpdateCompactionUpdate) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	var zero string
	return zero
}

// GetDescription returns the value of Description, or the zero value if x or Description is nil.
func (x *SessionUpdateNotice) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	var zero string
	return zero
}

// GetTitle returns the value of Title, or the zero value if x or Title is nil.
func (x *SessionUpdateSessionInfoUpdate) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	var zero string
	return zero
}

// GetUpdatedAt returns the value of UpdatedAt, or the zero value if x or UpdatedAt is nil.
func (x *SessionUpdateSessionInfoUpdate) GetUpdatedAt() string {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	var zero string
	return zero
}

// GetSenderSessionID returns the value of SenderSessionID, or the zero value if x or SenderSessionID is nil.
func (x *SessionUpdateSessionMessage) GetSenderSessionID() SessionID {
	if x != nil && x.SenderSessionID != nil {
		return *x.SenderSessionID
	}
	var zero SessionID
	return zero
}

// GetRecipientSessionID returns the value of RecipientSessionID, or the zero value if x or RecipientSessionID is nil.
func (x *SessionUpdateSessionMessage) GetRecipientSessionID() SessionID {
	if x != nil && x.RecipientSessionID != nil {
		return *x.RecipientSessionID
	}
	var zero SessionID
	return zero
}

// GetSenderSessionID returns the value of SenderSessionID, or the zero value if x or SenderSessionID is nil.
func (x *SessionUpdateSessionMessageChunk) GetSenderSessionID() SessionID {
	if x != nil && x.SenderSessionID != nil {
		return *x.SenderSessionID
	}
	var zero SessionID
	return zero
}

// GetRecipientSessionID returns the value of RecipientSessionID, or the zero value if x or RecipientSessionID is nil.
func (x *SessionUpdateSessionMessageChunk) GetRecipientSessionID() SessionID {
	if x != nil && x.RecipientSessionID != nil {
		return *x.RecipientSessionID
	}
	var zero SessionID
	return zero
}

// GetTitle returns the value of Title, or the zero value if x or Title is nil.
func (x *SessionUpdateSubagentUpdate) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	var zero string
	return zero
}

// GetDescription returns the value of Description, or the zero value if x or Description is nil.
func (x *SessionUpdateSubagentUpdate) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	var zero string
	return zero
}

// GetCapabilities returns Capabilities, or nil if x is nil.
func (x *SessionUpdateSubagentUpdate) GetCapabilities() *SubagentSessionCapabilities {
	if x == nil {
		return nil
	}
	return x.Capabilities
}

// GetCommand returns the value of Command, or the zero value if x or Command is nil.
func (x *SessionUpdateTerminalUpdate) GetCommand() string {
	if x != nil && x.Command != nil {
		return *x.Command
	}
	var zero string
	return zero
}

// GetCwd returns the value of Cwd, or the zero value if x or Cwd is nil.
func (x *SessionUpdateTerminalUpdate) GetCwd() AbsolutePath {
	if x != nil && x.Cwd != nil {
		return *x.Cwd
	}
	var zero AbsolutePath
	return zero
}

// GetOutput returns Output, or nil if x is nil.
func (x *SessionUpdateTerminalUpdate) GetOutput() *TerminalOutput {
	if x == nil {
		return nil
	}
	return x.Output
}

// GetExitStatus returns ExitStatus, or nil if x is nil.
func (x *SessionUpdateTerminalUpdate) GetExitStatus() *TerminalExitStatus {
	if x == nil {
		return nil
	}
	return x.ExitStatus
}

// GetName returns the value of Name, or the zero value if x or Name is nil.
func (x *SessionUpdateToolCallUpdate) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	var zero string
	return zero
}

// GetTitle returns the value of Title, or the zero value if x or Title is nil.
func (x *SessionUpdateToolCallUpdate) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	var zero string
	return zero
}

// GetKind returns the value of Kind, or the zero value if x or Kind is nil.
func (x *SessionUpdateToolCallUpdate) GetKind() ToolKind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	var zero ToolKind
	return zero
}

// GetStatus returns the value of Status, or the zero value if x or Status is nil.
func (x *SessionUpdateToolCallUpdate) GetStatus() ToolCallStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	var zero ToolCallStatus
	return zero
}

// GetCost returns Cost, or nil if x is nil.
func (x *SessionUpdateUsageUpdate) GetCost() *Cost {
	if x == nil {
		return nil
	}
	return x.Cost
}

// GetWorkspaceURI returns the value of WorkspaceURI, or the zero value if x or WorkspaceURI is nil.
func (x *StartNesRequest) GetWorkspaceURI() string {
	if x != nil && x.WorkspaceURI != nil {
		return *x.WorkspaceURI
	}
	var zero string
	return zero
}

// GetRepository returns Repository, or nil if x is nil.
func (x *StartNesRequest) GetRepository() *NesRepository {
	if x == nil {
		return nil
	}
	return x.Repository
}

// GetStopReason returns the value of StopReason, or the zero value if x or StopReason is nil.
func (x *StateUpdateIdle) GetStopReason() StopReason {
	if x != nil && x.StopReason != nil {
		return *x.StopReason
	}
	var zero StopReason
	return zero
}

// GetUsage returns Usage, or nil if x is nil.
func (x *StateUpdateIdle) GetUsage() *Usage {
	if x == nil {
		return nil
	}
	return x.Usage
}

// GetCancel returns Cancel, or nil if x is nil.
func (x *SubagentSessionCapabilities) GetCancel() *SessionCancelCapabilities {
	if x == nil {
		return nil
	}
	return x.Cancel
}

// GetSelection returns Selection, or nil if x is nil.
func (x *SuggestNesRequest) GetSelection() *Range {
	if x == nil {
		return nil
	}
	return x.Selection
}

// GetContext returns Context, or nil if x is nil.
func (x *SuggestNesRequest) GetContext() *NesSuggestContext {
	if x == nil {
		return nil
	}
	return x.Context
}

// GetExitCode returns the value of ExitCode, or the zero value if x or ExitCode is nil.
func (x *TerminalExitStatus) GetExitCode() uint32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	var zero uint32
	return zero
}

// GetSignal returns the value of Signal, or the zero value if x or Signal is nil.
func (x *TerminalExitStatus) GetSignal() string {
	if x != nil && x.Signal != nil {
		return *x.Signal
	}
	var zero string
	return zero
}

// GetRange returns Range, or nil if x is nil.
func (x *TextDocumentContentChangeEvent) GetRange() *Range {
	if x == nil {
		return nil
	}
	return x.Range
}

// GetMIMEType returns the value of MIMEType, or the zero value if x or MIMEType is nil.
func (x *TextResourceContents) GetMIMEType() MediaType {
	if x != nil && x.MIMEType != nil {
		return *x.MIMEType
	}
	var zero MediaType
	return zero
}

// GetPatch returns Patch, or nil if x is nil.
func (x *ToolCallContentDiff) GetPatch() *DiffPatch {
	if x == nil {
		return nil
	}
	return x.Patch
}

// GetLine returns the value of Line, or the zero value if x or Line is nil.
func (x *ToolCallLocation) GetLine() uint32 {
	if x != nil && x.Line != nil {
		return *x.Line
	}
	var zero uint32
	return zero
}

// GetName returns the value of Name, or the zero value if x or Name is nil.
func (x *ToolCallUpdate) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	var zero string
	return zero
}

// GetTitle returns the value of Title, or the zero value if x or Title is nil.
func (x *ToolCallUpdate) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	var zero string
	return zero
}

// GetKind returns the value of Kind, or the zero value if x or Kind is nil.
func (x *ToolCallUpdate) GetKind() ToolKind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	var zero ToolKind
	return zero
}

// GetStatus returns the value of Status, or the zero value if x or Status is nil.
func (x *ToolCallUpdate) GetStatus() ToolCallStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	var zero ToolCallStatus
	return zero
}

// GetThoughtTokens returns the value of ThoughtTokens, or the zero value if x or ThoughtTokens is nil.
func (x *Usage) GetThoughtTokens() uint64 {
	if x != nil && x.ThoughtTokens != nil {
		return *x.ThoughtTokens
	}
	var zero uint64
	return zero
}

// GetCachedReadTokens returns the value of CachedReadTokens, or the zero value if x or CachedReadTokens is nil.
func (x *Usage) GetCachedReadTokens() uint64 {
	if x != nil && x.CachedReadTokens != nil {
		return *x.CachedReadTokens
	}
	var zero uint64
	return zero
}

// GetCachedWriteTokens returns the value of CachedWriteTokens, or the zero value if x or CachedWriteTokens is nil.
func (x *Usage) GetCachedWriteTokens() uint64 {
	if x != nil && x.CachedWriteTokens != nil {
		return *x.CachedWriteTokens
	}
	var zero uint64
	return zero
}
