// Code generated by acp-schema from the TypeScript SDK; DO NOT EDIT.

package schema

// The AgentMethods constants mirror the SDK's AGENT_METHODS table.
const (
	AgentMethodsInitialize             = "initialize"
	AgentMethodsAuthLogin              = "auth/login"
	AgentMethodsProvidersList          = "providers/list"
	AgentMethodsProvidersSet           = "providers/set"
	AgentMethodsProvidersDisable       = "providers/disable"
	AgentMethodsSessionNew             = "session/new"
	AgentMethodsSessionSetConfigOption = "session/set_config_option"
	AgentMethodsSessionPrompt          = "session/prompt"
	AgentMethodsSessionCancel          = "session/cancel"
	AgentMethodsMCPMessage             = "mcp/message"
	AgentMethodsSessionList            = "session/list"
	AgentMethodsSessionDelete          = "session/delete"
	AgentMethodsSessionFork            = "session/fork"
	AgentMethodsSessionResume          = "session/resume"
	AgentMethodsSessionClose           = "session/close"
	AgentMethodsAuthLogout             = "auth/logout"
	AgentMethodsNesStart               = "nes/start"
	AgentMethodsNesSuggest             = "nes/suggest"
	AgentMethodsNesAccept              = "nes/accept"
	AgentMethodsNesReject              = "nes/reject"
	AgentMethodsNesClose               = "nes/close"
	AgentMethodsDocumentDidOpen        = "document/didOpen"
	AgentMethodsDocumentDidChange      = "document/didChange"
	AgentMethodsDocumentDidClose       = "document/didClose"
	AgentMethodsDocumentDidSave        = "document/didSave"
	AgentMethodsDocumentDidFocus       = "document/didFocus"
)

// The ClientMethods constants mirror the SDK's CLIENT_METHODS table.
const (
	ClientMethodsSessionRequestPermission = "session/request_permission"
	ClientMethodsSessionUpdate            = "session/update"
	ClientMethodsMCPMessage               = "mcp/message"
	ClientMethodsElicitationCreate        = "elicitation/create"
	ClientMethodsElicitationComplete      = "elicitation/complete"
)

// The ProtocolMethods constants mirror the SDK's PROTOCOL_METHODS table.
const (
	ProtocolMethodsCancelRequest = "$/cancel_request"
)

// CurrentProtocolVersion is the SDK's PROTOCOL_VERSION constant.
const CurrentProtocolVersion = 2
