// Code generated by acp-schema from the TypeScript SDK; DO NOT EDIT.

package schema

import (
	"encoding/json/jsontext"
	"encoding/json/v2"

	"github.com/ironpark/acp-go/schema/meta"
	"github.com/ironpark/acp-go/schema/optional"
)

// RequestPermissionRequest is a request for user permission to proceed with an operation.
//
// Sent when the agent needs authorization before performing a sensitive operation.
//
// See protocol docs: [Requesting Permission]
//
// [Requesting Permission]: https://agentclientprotocol.com/protocol/v2/draft/tool-calls#requesting-permission
type RequestPermissionRequest struct {
	// The session ID for this request.
	SessionID SessionID `json:"sessionId"`
	// Human-readable title for the permission prompt.
	//
	// This title is specific to the permission prompt and does not update any
	// subject's displayed title.
	Title string `json:"title"`
	// Optional human-readable explanation of why permission is needed.
	//
	// This text is specific to the permission prompt and does not update any
	// subject's displayed content. Omitted or `null` both mean no separate
	// permission description was provided.
	Description *string `json:"description,omitzero"`
	// Optional structured context about the operation requiring permission.
	//
	// Omitted or `null` both mean no structured subject was provided.
	Subject RequestPermissionSubject `json:"subject,omitzero"`
	// Available permission options for the user to choose from.
	// Must contain at least one option.
	Options []PermissionOption `json:"options"`
	Meta    Meta               `json:"_meta,omitzero"`
}

// Represents an upsert for a tool call that the language model has requested.
//
// Tool calls are actions that the agent executes on behalf of the language model,
// such as reading files, executing code, or fetching data from external sources.
//
// Only [ToolCallUpdate.ToolCallID] is required. Other fields have patch semantics:
// omitted fields leave the existing tool call value unchanged, `null` clears or
// unsets the value, and concrete values replace the previous value. For
// collection fields, concrete arrays replace the previous collection, and both
// `null` and `[]` clear the collection. When a client receives a tool call ID it
// has not seen before, omitted fields use client defaults.
//
// See protocol docs: [Tool Calls]
//
// [Tool Calls]: https://agentclientprotocol.com/protocol/v2/draft/tool-calls
type ToolCallUpdate struct {
	// Unique identifier for this tool call within the session.
	ToolCallID ToolCallID `json:"toolCallId"`
	// Programmatic name of the tool being invoked.
	//
	// This field is optional and has patch semantics. Omission means no
	// change, `null` clears the name, and a string replaces it. For a tool
	// call ID the client has not seen before, omission or `null` means that no
	// tool name is available.
	Name optional.Value[string] `json:"name,omitzero"`
	// Human-readable title describing what the tool is doing.
	Title optional.Value[string] `json:"title,omitzero"`
	// The category of tool being invoked.
	// Helps clients choose appropriate icons and UI treatment.
	Kind optional.Value[ToolKind] `json:"kind,omitzero"`
	// Current execution status of the tool call.
	Status optional.Value[ToolCallStatus] `json:"status,omitzero"`
	// Content produced by the tool call.
	Content optional.Value[[]ToolCallContent] `json:"content,omitzero"`
	// File locations affected by this tool call.
	// Enables "follow-along" features in clients.
	Locations optional.Value[[]ToolCallLocation] `json:"locations,omitzero"`
	// Raw input parameters sent to the tool.
	RawInput jsontext.Value `json:"rawInput,omitzero"`
	// Raw output returned by the tool.
	RawOutput jsontext.Value `json:"rawOutput,omitzero"`
	// Omitted means no metadata update; `null` is an explicit clear signal.
	Meta optional.Value[Meta] `json:"_meta,omitzero"`
}

// Optional annotations for the client. The client can use annotations to inform how objects are used or displayed
type Annotations struct {
	// Intended recipients for this content, such as the user or assistant.
	Audience []Role `json:"audience,omitzero"`
	// Timestamp indicating when the underlying resource was last modified.
	//
	// Must be an RFC 3339 formatted string (e.g., "2025-01-12T15:00:58Z").
	LastModified *string `json:"lastModified,omitzero"`
	// Relative importance of this content when clients choose what to surface.
	Priority *float64 `json:"priority,omitzero"`
	Meta     Meta     `json:"_meta,omitzero"`
}

// An optionally-sized icon that can be displayed in a user interface.
type Icon struct {
	// A standard URI pointing to an icon resource.
	Src string `json:"src"`
	// Optional MIME type override if the source MIME type is missing or generic.
	MIMEType *MediaType `json:"mimeType,omitzero"`
	// Optional array of strings that specify sizes at which the icon can be used.
	// Each string should be in `WxH` format (e.g., `"48x48"`, `"96x96"`) or
	// `"any"` for scalable formats like SVG.
	//
	// If not provided, the client should assume that the icon can be used at any size.
	Sizes []string `json:"sizes,omitzero"`
	// Optional theme this icon is designed for.
	Theme *IconTheme `json:"theme,omitzero"`
}

// Text-based resource contents.
type TextResourceContents struct {
	// Text payload carried by this content block.
	Text string `json:"text"`
	// URI associated with this resource or media payload.
	URI string `json:"uri"`
	// MIME type describing the encoded media payload.
	MIMEType *MediaType `json:"mimeType,omitzero"`
	Meta     Meta       `json:"_meta,omitzero"`
}

// Binary resource contents.
type BlobResourceContents struct {
	// Base64-encoded bytes for a binary resource payload.
	Blob string `json:"blob"`
	// URI associated with this resource or media payload.
	URI string `json:"uri"`
	// MIME type describing the encoded media payload.
	MIMEType *MediaType `json:"mimeType,omitzero"`
	Meta     Meta       `json:"_meta,omitzero"`
}

// Operation metadata for add, delete, and modify changes.
type DiffPathChange struct {
	// Absolute path for the operation.
	Path AbsolutePath `json:"path"`
}

// Operation metadata for move and copy changes.
type DiffPathPairChange struct {
	// Absolute path before the operation.
	OldPath AbsolutePath `json:"oldPath"`
	// Absolute path after the operation.
	Path AbsolutePath `json:"path"`
}

// Renderable patch text and its format.
type DiffPatch struct {
	// Patch format. The only ACP-defined value is `git_patch`.
	Format DiffPatchFormat `json:"format"`
	// Patch text in the format named by `format`.
	Text string `json:"text"`
}

// ToolCallLocation is a file location being accessed or modified by a tool.
//
// Enables clients to implement "follow-along" features that track
// which files the agent is working with in real-time.
//
// See protocol docs: [Following the Agent]
//
// [Following the Agent]: https://agentclientprotocol.com/protocol/v2/draft/tool-calls#following-the-agent
type ToolCallLocation struct {
	// The absolute file path being accessed or modified.
	Path AbsolutePath `json:"path"`
	// Optional line number within the file.
	Line *uint32 `json:"line,omitzero"`
	Meta Meta    `json:"_meta,omitzero"`
}

// PermissionOption is an option presented to the user when requesting permission.
type PermissionOption struct {
	// Unique identifier for this permission option.
	OptionID PermissionOptionID `json:"optionId"`
	// Human-readable label to display to the user.
	Name string `json:"name"`
	// Hint about the nature of this permission option.
	Kind PermissionOptionKind `json:"kind"`
	Meta Meta                 `json:"_meta,omitzero"`
}

// Session-scoped elicitation, optionally tied to a specific tool call.
//
// When `tool_call_id` is set, the elicitation is tied to a specific tool call.
// This is useful when an agent receives an elicitation from an MCP server
// during a tool call and needs to redirect it to the user.
type ElicitationSessionScope struct {
	// The session this elicitation is tied to.
	SessionID SessionID `json:"sessionId"`
	// Optional tool call within the session.
	//
	// Optional. Omitted and `null` are equivalent and mean the elicitation is scoped to the
	// session without a specific tool call.
	ToolCallID *ToolCallID `json:"toolCallId,omitzero"`
}

// Request-scoped elicitation, tied to a specific JSON-RPC request outside of a session
// (e.g., during auth/configuration phases before any session is started).
type ElicitationRequestScope struct {
	// The request this elicitation is tied to.
	RequestID RequestID `json:"requestId"`
}

// Type-safe elicitation schema for requesting structured user input.
//
// This represents a JSON Schema object with primitive-typed properties,
// as required by the elicitation specification.
type ElicitationSchema struct {
	// Type discriminator. Always `"object"`.
	Type *ElicitationSchemaType `json:"type,omitzero"`
	// Optional title for the schema.
	//
	// Optional. Omitted and `null` are equivalent and mean no title is provided.
	Title *string `json:"title,omitzero"`
	// Property definitions (must be primitive types).
	Properties map[string]ElicitationPropertySchema `json:"properties,omitzero"`
	// List of required property names.
	//
	// Optional. Omitted and `null` are equivalent and mean no property names are required.
	Required []string `json:"required,omitzero"`
	// Optional description of what this schema represents.
	//
	// Optional. Omitted and `null` are equivalent and mean no schema description is provided.
	Description *string `json:"description,omitzero"`
	// Optional. Omitted and `null` are equivalent and mean no metadata.
	Meta Meta `json:"_meta,omitzero"`
}

// EnumOption is a titled enum option with a const value, human-readable title, and optional description.
type EnumOption struct {
	// The constant value for this option.
	Const string `json:"const"`
	// Human-readable title for this option.
	Title string `json:"title"`
	// Human-readable description.
	//
	// Optional. Omitted and `null` are equivalent and mean no description is provided.
	Description *string `json:"description,omitzero"`
	// Optional. Omitted and `null` are equivalent and mean no metadata.
	Meta Meta `json:"_meta,omitzero"`
}

// Items definition for titled multi-select enum properties.
type TitledMultiSelectItems struct {
	// Titled enum options. Must contain at least one option.
	AnyOf []EnumOption `json:"anyOf"`
	// Optional. Omitted and `null` are equivalent and mean no metadata.
	Meta Meta `json:"_meta,omitzero"`
}

// Request parameters for `mcp/message`, sent from consumer to provider.
//
// Experimental: not part of the spec yet; it may change or be removed.
type MessageMCPRequest struct {
	// The declared ACP MCP server receiving this request.
	ServerID MCPServerACPID `json:"serverId"`
	// The caller-generated identifier for the inner MCP request.
	RequestID MCPRequestID `json:"requestId"`
	// The inner MCP method name.
	Method string `json:"method"`
	// Optional inner MCP params; null is equivalent to omission.
	Params map[string]jsontext.Value `json:"params,omitzero"`
	// ACP extension metadata (not inner MCP params._meta); null is equivalent to omission.
	Meta Meta `json:"_meta,omitzero"`
}

// Allows for sending an arbitrary request that is not part of the ACP spec.
// Extension methods provide a way to add custom functionality while maintaining
// protocol compatibility.
//
// See protocol docs: [Extensibility]
//
// [Extensibility]: https://agentclientprotocol.com/protocol/v2/draft/extensibility
type ExtRequest = jsontext.Value

// InitializeResponse is a response to the `initialize` method.
//
// Contains the negotiated protocol version and agent capabilities.
//
// See protocol docs: [Initialization]
//
// [Initialization]: https://agentclientprotocol.com/protocol/v2/draft/initialization
type InitializeResponse struct {
	// The protocol version the client specified if supported by the agent,
	// or the latest protocol version supported by the agent.
	//
	// The client should disconnect, if it doesn't support this version.
	ProtocolVersion ProtocolVersion `json:"protocolVersion"`
	// Information about the implementation sending this initialize response.
	Info Implementation `json:"info"`
	// Capabilities supported by the agent.
	Capabilities *AgentCapabilities `json:"capabilities,omitzero"`
	// Authentication methods supported by the agent.
	//
	// Optional. Omitted or empty means the agent does not advertise the
	// authentication method surface. Supplying one or more valid methods means
	// the agent MUST support both `auth/login` and `auth/logout`.
	AuthMethods []AuthMethod `json:"authMethods,omitzero"`
	Meta        Meta         `json:"_meta,omitzero"`
}

// Metadata about the implementation of the client or agent.
// Describes the name and version of an ACP implementation, with an optional
// title for UI representation.
type Implementation struct {
	// Intended for programmatic or logical use, but can be used as a display
	// name fallback if title isn’t present.
	Name string `json:"name"`
	// Intended for UI and end-user contexts — optimized to be human-readable
	// and easily understood.
	//
	// If not provided, the name should be used for display.
	Title *string `json:"title,omitzero"`
	// Version of the implementation. Can be displayed to the user or used
	// for debugging or metrics purposes. (e.g. "1.0.0").
	Version string `json:"version"`
	Meta    Meta   `json:"_meta,omitzero"`
}

// Capabilities supported by the agent.
//
// Advertised during initialization to inform the client about
// available features and content types.
//
// See protocol docs: [Agent Capabilities]
//
// [Agent Capabilities]: https://agentclientprotocol.com/protocol/v2/draft/initialization#agent-capabilities
type AgentCapabilities struct {
	// Session capabilities supported by the agent.
	//
	// Optional. Omitted or `null` both mean the agent does not support the
	// `session*` method surface. Supplying `{}` means the agent supports the
	// baseline session methods: `session/new`, `session/prompt`,
	// `session/cancel`, and `session/update`.
	Session *SessionCapabilities `json:"session,omitzero"`
	// Authentication-related extension capabilities supported by the agent.
	//
	// Optional. Omitted or `null` both mean the agent does not advertise any
	// authentication-related extensions. This field does not advertise support
	// for `auth/login` or `auth/logout`; those methods are advertised by a
	// non-empty `authMethods` list in the `initialize` response.
	Auth *AgentAuthCapabilities `json:"auth,omitzero"`
	// Provider configuration capabilities supported by the agent.
	//
	// Optional. Omitted or `null` both mean the agent does not advertise support.
	// Supplying `{}` means the agent supports provider configuration methods.
	//
	// Experimental: not part of the spec yet; it may change or be removed.
	Providers *ProvidersCapabilities `json:"providers,omitzero"`
	// NES (Next Edit Suggestions) capabilities supported by the agent.
	//
	// Optional. Omitted or `null` both mean the agent does not advertise support
	// for NES methods.
	//
	// Experimental: not part of the spec yet; it may change or be removed.
	Nes *NesCapabilities `json:"nes,omitzero"`
	// The position encoding selected by the agent from the client's supported encodings.
	//
	// Experimental: not part of the spec yet; it may change or be removed.
	PositionEncoding *PositionEncodingKind `json:"positionEncoding,omitzero"`
	Meta             Meta                  `json:"_meta,omitzero"`
}

// Session capabilities supported by the agent.
//
// Supplying `{}` means the agent supports the baseline session methods:
// `session/new`, `session/list`, `session/resume`, `session/close`,
// `session/prompt`, `session/cancel`, and `session/update`.
//
// Agents that support sessions **MAY** support additional session methods,
// prompt content types, and MCP transports by specifying additional
// capabilities.
//
// See protocol docs: [Session Capabilities]
//
// [Session Capabilities]: https://agentclientprotocol.com/protocol/v2/draft/initialization#session-capabilities
type SessionCapabilities struct {
	// Prompt capabilities supported by the agent in `session/prompt` requests.
	//
	// Optional. Omitted or `null` both mean the agent does not advertise any
	// prompt extensions beyond the baseline text and resource-link content
	// required by `session/prompt`.
	Prompt *PromptCapabilities `json:"prompt,omitzero"`
	// MCP capabilities supported by the agent for session lifecycle requests.
	//
	// Optional. Omitted or `null` both mean the agent does not advertise MCP
	// server transport support for sessions.
	MCP *MCPCapabilities `json:"mcp,omitzero"`
	// Whether the agent supports `session/delete`.
	//
	// Optional. Omitted or `null` both mean the agent does not advertise support.
	// Supplying `{}` means the agent supports deleting sessions from `session/list`.
	Delete *SessionDeleteCapabilities `json:"delete,omitzero"`
	// Whether the agent supports `additionalDirectories` on supported session lifecycle requests.
	//
	// Optional. Omitted or `null` both mean the agent does not advertise support.
	// Supplying `{}` means the agent supports `additionalDirectories` on
	// supported session lifecycle requests.
	//
	// Agents may return `SessionInfo.additionalDirectories` to report the
	// complete ordered additional-root list associated with a listed session.
	AdditionalDirectories *SessionAdditionalDirectoriesCapabilities `json:"additionalDirectories,omitzero"`
	// Whether the agent supports `session/fork`.
	//
	// Optional. Omitted or `null` both mean the agent does not advertise support.
	// Supplying `{}` means the agent supports forking sessions.
	//
	// Experimental: not part of the spec yet; it may change or be removed.
	Fork *SessionForkCapabilities `json:"fork,omitzero"`
	Meta Meta                     `json:"_meta,omitzero"`
}

// Prompt capabilities supported by the agent in `session/prompt` requests.
//
// Baseline agent functionality requires support for [ContentBlockText]
// and [ContentBlockResourceLink] in prompt requests.
//
// Other variants must be explicitly opted in to.
// Capabilities for different types of content in prompt requests.
//
// Indicates which content types beyond the baseline (text and resource links)
// the agent can process.
//
// See protocol docs: [Prompt Capabilities]
//
// [Prompt Capabilities]: https://agentclientprotocol.com/protocol/v2/draft/initialization#prompt-capabilities
type PromptCapabilities struct {
	// Agent supports [ContentBlockImage].
	//
	// Optional. Omitted or `null` both mean the agent does not advertise support.
	// Supplying `{}` means the agent supports image content in prompts.
	Image *PromptImageCapabilities `json:"image,omitzero"`
	// Agent supports [ContentBlockAudio].
	//
	// Optional. Omitted or `null` both mean the agent does not advertise support.
	// Supplying `{}` means the agent supports audio content in prompts.
	Audio *PromptAudioCapabilities `json:"audio,omitzero"`
	// Agent supports embedded context in `session/prompt` requests.
	//
	// When enabled, the Client is allowed to include [ContentBlockResource]
	// in prompt requests for pieces of context that are referenced in the message.
	//
	// Optional. Omitted or `null` both mean the agent does not advertise support.
	// Supplying `{}` means the agent supports embedded context in prompts.
	EmbeddedContext *PromptEmbeddedContextCapabilities `json:"embeddedContext,omitzero"`
	Meta            Meta                               `json:"_meta,omitzero"`
}

// Capabilities for image content in prompt requests.
//
// Supplying `{}` means the agent supports image content in prompts.
type PromptImageCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Capabilities for audio content in prompt requests.
//
// Supplying `{}` means the agent supports audio content in prompts.
type PromptAudioCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Capabilities for embedded context in prompt requests.
//
// Supplying `{}` means the agent supports embedded context in prompts.
type PromptEmbeddedContextCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// MCP capabilities supported by the agent for session lifecycle requests.
type MCPCapabilities struct {
	// Agent supports [MCPServerStdio].
	//
	// Optional. Omitted or `null` both mean the agent does not advertise support.
	// Supplying `{}` means the agent supports stdio MCP server transports.
	Stdio *MCPStdioCapabilities `json:"stdio,omitzero"`
	// Agent supports [MCPServerHTTP].
	//
	// Optional. Omitted or `null` both mean the agent does not advertise support.
	// Supplying `{}` means the agent supports HTTP MCP server transports.
	HTTP *MCPHTTPCapabilities `json:"http,omitzero"`
	// Agent supports [MCPServerACP].
	//
	// Optional. Omitted or `null` both mean the agent does not advertise support.
	// Supplying `{}` means the agent supports ACP MCP server transports.
	//
	// Experimental: not part of the spec yet; it may change or be removed.
	ACP  *MCPACPCapabilities `json:"acp,omitzero"`
	Meta Meta                `json:"_meta,omitzero"`
}

// Capabilities for stdio MCP server transports.
//
// Supplying `{}` means the agent supports stdio MCP server transports.
type MCPStdioCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Capabilities for HTTP MCP server transports.
//
// Supplying `{}` means the agent supports HTTP MCP server transports.
type MCPHTTPCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Capabilities for ACP MCP server transports.
//
// Supplying `{}` means the agent supports ACP MCP server transports.
//
// Experimental: not part of the spec yet; it may change or be removed.
type MCPACPCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Capabilities for the `session/delete` method.
//
// Supplying `{}` means the agent supports deleting sessions from `session/list`.
type SessionDeleteCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Capabilities for additional session directories support.
//
// Supplying `{}` means the agent supports the `additionalDirectories` field on
// supported session lifecycle requests. Agents that also support
// `session/list` may return `SessionInfo.additionalDirectories` to report the
// complete ordered additional-root list associated with a listed session.
type SessionAdditionalDirectoriesCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Capabilities for the `session/fork` method.
//
// Supplying `{}` means the agent supports forking sessions.
//
// Experimental: not part of the spec yet; it may change or be removed.
type SessionForkCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Authentication-related extension capabilities supported by the agent.
//
// This object does not advertise support for `auth/login` or `auth/logout`.
// Those methods are advertised by a non-empty `authMethods` list in the
// `initialize` response.
type AgentAuthCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Provider configuration capabilities supported by the agent.
//
// Supplying `{}` means the agent supports provider configuration methods.
//
// Experimental: not part of the spec yet; it may change or be removed.
type ProvidersCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// NES capabilities advertised by the agent during initialization.
//
// Supplying `{}` means the agent supports the NES method surface. Omitted or
// `null` both mean the agent does not advertise support for `nes*` methods.
type NesCapabilities struct {
	// Events the agent wants to receive.
	Events *NesEventCapabilities `json:"events,omitzero"`
	// Context the agent wants attached to each suggestion request.
	Context *NesContextCapabilities `json:"context,omitzero"`
	Meta    Meta                    `json:"_meta,omitzero"`
}

// Event capabilities the agent can consume.
type NesEventCapabilities struct {
	// Document event capabilities.
	Document *NesDocumentEventCapabilities `json:"document,omitzero"`
	Meta     Meta                          `json:"_meta,omitzero"`
}

// Document event capabilities the agent wants to receive.
type NesDocumentEventCapabilities struct {
	// Whether the agent wants `document/didOpen` events.
	DidOpen *NesDocumentDidOpenCapabilities `json:"didOpen,omitzero"`
	// Whether the agent wants `document/didChange` events, and the sync kind.
	DidChange *NesDocumentDidChangeCapabilities `json:"didChange,omitzero"`
	// Whether the agent wants `document/didClose` events.
	DidClose *NesDocumentDidCloseCapabilities `json:"didClose,omitzero"`
	// Whether the agent wants `document/didSave` events.
	DidSave *NesDocumentDidSaveCapabilities `json:"didSave,omitzero"`
	// Whether the agent wants `document/didFocus` events.
	DidFocus *NesDocumentDidFocusCapabilities `json:"didFocus,omitzero"`
	Meta     Meta                             `json:"_meta,omitzero"`
}

// NesDocumentDidOpenCapabilities is a marker for `document/didOpen` capability support.
type NesDocumentDidOpenCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Capabilities for `document/didChange` events.
type NesDocumentDidChangeCapabilities struct {
	// The sync kind the agent wants: `"full"` or `"incremental"`.
	SyncKind TextDocumentSyncKind `json:"syncKind"`
	Meta     Meta                 `json:"_meta,omitzero"`
}

// NesDocumentDidCloseCapabilities is a marker for `document/didClose` capability support.
type NesDocumentDidCloseCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// NesDocumentDidSaveCapabilities is a marker for `document/didSave` capability support.
type NesDocumentDidSaveCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// NesDocumentDidFocusCapabilities is a marker for `document/didFocus` capability support.
type NesDocumentDidFocusCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Context capabilities the agent wants attached to each suggestion request.
type NesContextCapabilities struct {
	// Whether the agent wants recent files context.
	RecentFiles *NesRecentFilesCapabilities `json:"recentFiles,omitzero"`
	// Whether the agent wants related snippets context.
	RelatedSnippets *NesRelatedSnippetsCapabilities `json:"relatedSnippets,omitzero"`
	// Whether the agent wants edit history context.
	EditHistory *NesEditHistoryCapabilities `json:"editHistory,omitzero"`
	// Whether the agent wants user actions context.
	UserActions *NesUserActionsCapabilities `json:"userActions,omitzero"`
	// Whether the agent wants open files context.
	OpenFiles *NesOpenFilesCapabilities `json:"openFiles,omitzero"`
	// Whether the agent wants diagnostics context.
	Diagnostics *NesDiagnosticsCapabilities `json:"diagnostics,omitzero"`
	Meta        Meta                        `json:"_meta,omitzero"`
}

// Capabilities for recent files context.
type NesRecentFilesCapabilities struct {
	// Maximum number of recent files the agent can use.
	MaxCount *uint32 `json:"maxCount,omitzero"`
	Meta     Meta    `json:"_meta,omitzero"`
}

// Capabilities for related snippets context.
type NesRelatedSnippetsCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Capabilities for edit history context.
type NesEditHistoryCapabilities struct {
	// Maximum number of edit history entries the agent can use.
	MaxCount *uint32 `json:"maxCount,omitzero"`
	Meta     Meta    `json:"_meta,omitzero"`
}

// Capabilities for user actions context.
type NesUserActionsCapabilities struct {
	// Maximum number of user actions the agent can use.
	MaxCount *uint32 `json:"maxCount,omitzero"`
	Meta     Meta    `json:"_meta,omitzero"`
}

// Capabilities for open files context.
type NesOpenFilesCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Capabilities for diagnostics context.
type NesDiagnosticsCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// EnvVariable is an environment variable to set when launching a process.
type EnvVariable struct {
	// The name of the environment variable.
	Name string `json:"name"`
	// The value to set for the environment variable.
	Value string `json:"value"`
	Meta  Meta   `json:"_meta,omitzero"`
}

// LoginAuthResponse is a response to the `auth/login` method.
type LoginAuthResponse struct {
	Meta Meta `json:"_meta,omitzero"`
}

// ListProvidersResponse is a response to `providers/list`.
//
// Experimental: not part of the spec yet; it may change or be removed.
type ListProvidersResponse struct {
	// Configurable providers with current routing info suitable for UI display.
	Providers []ProviderInfo `json:"providers"`
	Meta      Meta           `json:"_meta,omitzero"`
}

// Information about a configurable LLM provider.
//
// Experimental: not part of the spec yet; it may change or be removed.
type ProviderInfo struct {
	// Provider identifier, for example "main" or "openai".
	ProviderID ProviderID `json:"providerId"`
	// Supported protocol types for this provider.
	Supported []LLMProtocol `json:"supported"`
	// Whether this provider is mandatory and cannot be disabled via `providers/disable`.
	// If true, clients must not call `providers/disable` for this provider ID.
	Required bool `json:"required"`
	// Current effective non-secret routing config.
	// Null or omitted means provider is disabled.
	Current *ProviderCurrentConfig `json:"current,omitzero"`
	Meta    Meta                   `json:"_meta,omitzero"`
}

// Current effective non-secret routing configuration for a provider.
//
// Experimental: not part of the spec yet; it may change or be removed.
type ProviderCurrentConfig struct {
	// Protocol currently used by this provider.
	APIType LLMProtocol `json:"apiType"`
	// Base URL currently used by this provider.
	BaseURL string `json:"baseUrl"`
	Meta    Meta   `json:"_meta,omitzero"`
}

// SetProviderResponse is a response to `providers/set`.
//
// Experimental: not part of the spec yet; it may change or be removed.
type SetProviderResponse struct {
	Meta Meta `json:"_meta,omitzero"`
}

// DisableProviderResponse is a response to `providers/disable`.
//
// Experimental: not part of the spec yet; it may change or be removed.
type DisableProviderResponse struct {
	Meta Meta `json:"_meta,omitzero"`
}

// LogoutAuthResponse is a response to the `auth/logout` method.
type LogoutAuthResponse struct {
	Meta Meta `json:"_meta,omitzero"`
}

// NewSessionResponse is a response from creating a new session.
//
// See protocol docs: [Creating a Session]
//
// [Creating a Session]: https://agentclientprotocol.com/protocol/v2/draft/session-setup#creating-a-session
type NewSessionResponse struct {
	// Unique identifier for the created session.
	//
	// Used in all subsequent requests for this conversation.
	SessionID SessionID `json:"sessionId"`
	// Initial session configuration options.
	ConfigOptions []SessionConfigOption `json:"configOptions,omitzero"`
	// Initial commands the agent can execute in this session.
	//
	// Optional. Omitted or empty means no initial commands are advertised.
	// Senders MUST use an array, not `null`; receivers treat `null` like omission.
	// Later `available_commands_update` notifications replace this list.
	AvailableCommands []AvailableCommand `json:"availableCommands,omitzero"`
	Meta              Meta               `json:"_meta,omitzero"`
}

// SessionConfigSelectOption is a possible value for a session configuration option.
type SessionConfigSelectOption struct {
	// Unique identifier for this option value.
	Value SessionConfigValueID `json:"value"`
	// Human-readable label for this option value.
	Name string `json:"name"`
	// Optional description for this option value.
	Description *string `json:"description,omitzero"`
	Meta        Meta    `json:"_meta,omitzero"`
}

// SessionConfigSelectGroup is a group of possible values for a session configuration option.
type SessionConfigSelectGroup struct {
	// Unique identifier for this group.
	GroupID SessionConfigGroupID `json:"groupId"`
	// Human-readable label for this group.
	Name string `json:"name"`
	// The set of option values in this group.
	Options []SessionConfigSelectOption `json:"options"`
	Meta    Meta                        `json:"_meta,omitzero"`
}

// SessionConfigSelect is a single-value selector (dropdown) session configuration option payload.
type SessionConfigSelect struct {
	// The currently selected value.
	CurrentValue SessionConfigValueID `json:"currentValue"`
	// The set of selectable options.
	Options SessionConfigSelectOptions `json:"options"`
}

// SessionConfigBoolean is a boolean on/off toggle session configuration option payload.
type SessionConfigBoolean struct {
	// The current value of the boolean option.
	CurrentValue bool `json:"currentValue"`
}

// Information about a command.
type AvailableCommand struct {
	// Command name (e.g., `create_plan`, `research_codebase`).
	Name string `json:"name"`
	// Human-readable description of what the command does.
	Description string `json:"description"`
	// Input for the command if required
	Input AvailableCommandInput `json:"input,omitzero"`
	Meta  Meta                  `json:"_meta,omitzero"`
}

// ListSessionsResponse is a response from listing sessions.
type ListSessionsResponse struct {
	// Array of session information objects.
	Sessions []SessionInfo `json:"sessions"`
	// Opaque cursor token. If present, pass this in the next request's cursor parameter
	// to fetch the next page. If absent, there are no more results.
	NextCursor *SessionListCursor `json:"nextCursor,omitzero"`
	Meta       Meta               `json:"_meta,omitzero"`
}

// Information about a session returned by session/list
type SessionInfo struct {
	// Unique identifier for the session
	SessionID SessionID `json:"sessionId"`
	// The working directory for this session. Must be an absolute path.
	Cwd AbsolutePath `json:"cwd"`
	// Additional workspace roots reported for this session. Each path must be absolute.
	//
	// When present, this is the complete ordered additional-root list reported
	// by the Agent. Omitted and empty values are equivalent: the response
	// reports no additional roots.
	AdditionalDirectories []AbsolutePath `json:"additionalDirectories,omitzero"`
	// Human-readable title for the session
	Title *string `json:"title,omitzero"`
	// RFC 3339 timestamp of last activity.
	UpdatedAt *string `json:"updatedAt,omitzero"`
	Meta      Meta    `json:"_meta,omitzero"`
}

// DeleteSessionResponse is a response from deleting a session.
type DeleteSessionResponse struct {
	Meta Meta `json:"_meta,omitzero"`
}

// ForkSessionResponse is a response from forking an existing session.
//
// Experimental: not part of the spec yet; it may change or be removed.
type ForkSessionResponse struct {
	// Unique identifier for the newly created forked session.
	SessionID SessionID `json:"sessionId"`
	// Initial session configuration options.
	ConfigOptions []SessionConfigOption `json:"configOptions,omitzero"`
	// Initial commands the agent can execute in this session.
	//
	// Optional. Omitted or empty means no initial commands are advertised.
	// Senders MUST use an array, not `null`; receivers treat `null` like omission.
	// Later `available_commands_update` notifications replace this list.
	AvailableCommands []AvailableCommand `json:"availableCommands,omitzero"`
	Meta              Meta               `json:"_meta,omitzero"`
}

// ResumeSessionResponse is a response from resuming an existing session.
type ResumeSessionResponse struct {
	// Initial session configuration options.
	ConfigOptions []SessionConfigOption `json:"configOptions,omitzero"`
	// Initial commands the agent can execute in this session.
	//
	// Optional. Omitted or empty means no initial commands are advertised.
	// Senders MUST use an array, not `null`; receivers treat `null` like omission.
	// Later `available_commands_update` notifications replace this list.
	AvailableCommands []AvailableCommand `json:"availableCommands,omitzero"`
	Meta              Meta               `json:"_meta,omitzero"`
}

// CloseSessionResponse is a response from closing a session.
type CloseSessionResponse struct {
	Meta Meta `json:"_meta,omitzero"`
}

// SetSessionConfigOptionResponse is a response to `session/set_config_option` method.
type SetSessionConfigOptionResponse struct {
	// The full set of configuration options and their current values.
	ConfigOptions []SessionConfigOption `json:"configOptions"`
	Meta          Meta                  `json:"_meta,omitzero"`
}

// Response acknowledging that a user prompt was inserted into the ACP conversation.
//
// This response does not indicate that the prompt was merely received or queued, nor that the
// agent has finished processing it.
// Processing and completion are reported through `state_update` session updates.
//
// See protocol docs: [Prompt Accepted]
//
// [Prompt Accepted]: https://agentclientprotocol.com/protocol/v2/draft/prompt-lifecycle#2-prompt-accepted
type PromptResponse struct {
	// Identifies the user message inserted into the ACP conversation.
	//
	// Required and non-null. Omission and explicit `null` are both invalid.
	//
	// The corresponding user-message session update carries this same identifier and may arrive
	// before or after this response. Agents must echo the message during the live session, but are
	// not required to retain it. If retained and replayed, the message keeps this identifier.
	MessageID MessageID `json:"messageId"`
	Meta      Meta      `json:"_meta,omitzero"`
}

// StartNesResponse is a response to `nes/start`.
type StartNesResponse struct {
	// The session ID for the newly started NES session.
	SessionID SessionID `json:"sessionId"`
	Meta      Meta      `json:"_meta,omitzero"`
}

// SuggestNesResponse is a response to `nes/suggest`.
type SuggestNesResponse struct {
	// The list of suggestions.
	Suggestions []NesSuggestion `json:"suggestions"`
	Meta        Meta            `json:"_meta,omitzero"`
}

// NesTextEdit is a text edit within a suggestion.
type NesTextEdit struct {
	// The range to replace.
	Range Range `json:"range"`
	// The replacement text.
	NewText string `json:"newText"`
	Meta    Meta   `json:"_meta,omitzero"`
}

// Range is a range in a text document, expressed as start and end positions.
type Range struct {
	// The start position (inclusive).
	Start Position `json:"start"`
	// The end position (exclusive).
	End  Position `json:"end"`
	Meta Meta     `json:"_meta,omitzero"`
}

// Position is a zero-based position in a text document.
//
// The meaning of `character` depends on the negotiated position encoding.
type Position struct {
	// Zero-based line number.
	Line uint32 `json:"line"`
	// Zero-based character offset (encoding-dependent).
	Character uint32 `json:"character"`
	Meta      Meta   `json:"_meta,omitzero"`
}

// CloseNesResponse is a response from closing an NES session.
type CloseNesResponse struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Allows for sending an arbitrary response to an [ExtRequest] that is not part of the ACP spec.
// Extension methods provide a way to add custom functionality while maintaining
// protocol compatibility.
//
// See protocol docs: [Extensibility]
//
// [Extensibility]: https://agentclientprotocol.com/protocol/v2/draft/extensibility
type ExtResponse = jsontext.Value

// Notification containing a session update from the agent.
//
// Agents can send session updates at any point while the session exists.
//
// See protocol docs: [Agent Reports Output]
//
// [Agent Reports Output]: https://agentclientprotocol.com/protocol/v2/draft/prompt-lifecycle#3-agent-reports-output
type UpdateSessionNotification struct {
	// The ID of the session this update pertains to.
	SessionID SessionID `json:"sessionId"`
	// The actual update content.
	Update SessionUpdate `json:"update"`
	Meta   Meta          `json:"_meta,omitzero"`
}

// ContentChunk is a streamed item of message content.
type ContentChunk struct {
	// A unique identifier for the message this chunk belongs to.
	//
	// All chunks belonging to the same message share the same `messageId`.
	// A change in `messageId` indicates a new message has started.
	MessageID MessageID `json:"messageId"`
	// A single item of content
	Content ContentBlock `json:"content"`
	// This field is chunk-scoped.
	Meta Meta `json:"_meta,omitzero"`
}

// Token usage information for completed session work.
//
// Experimental: not part of the spec yet; it may change or be removed.
type Usage struct {
	// Sum of all token types across session.
	TotalTokens uint64 `json:"totalTokens"`
	// Total input tokens.
	InputTokens uint64 `json:"inputTokens"`
	// Total output tokens.
	OutputTokens uint64 `json:"outputTokens"`
	// Total thought/reasoning tokens
	ThoughtTokens *uint64 `json:"thoughtTokens,omitzero"`
	// Total cache read tokens.
	CachedReadTokens *uint64 `json:"cachedReadTokens,omitzero"`
	// Total cache write tokens.
	CachedWriteTokens *uint64 `json:"cachedWriteTokens,omitzero"`
	Meta              Meta    `json:"_meta,omitzero"`
}

// TerminalOutput is an authoritative replacement snapshot of terminal output bytes.
type TerminalOutput struct {
	// Base64-encoded replacement terminal output bytes.
	Data string `json:"data"`
	// This metadata is scoped to the replacement snapshot. Omitted and `null` are equivalent and mean no snapshot metadata was provided.
	Meta Meta `json:"_meta,omitzero"`
}

// Exit information for an agent-owned terminal.
//
// The presence of this object marks the terminal as exited, even when neither
// an exit code nor a signal is known.
type TerminalExitStatus struct {
	// Process exit code, when known. Omitted and `null` are equivalent.
	ExitCode *uint32 `json:"exitCode,omitzero"`
	// Signal that terminated the process, when known.
	//
	// Agents should use the conventional platform signal name. POSIX examples
	// include `SIGTERM`, `SIGKILL`, and `SIGINT`. Other platforms may use a
	// platform-specific name. Omitted and `null` are equivalent.
	Signal *string `json:"signal,omitzero"`
	// This metadata is scoped to the exit information. Omitted and `null` are equivalent and mean no exit metadata was provided.
	Meta Meta `json:"_meta,omitzero"`
}

// PlanEntry is a single entry in the execution plan.
//
// Represents a task or goal that the assistant intends to accomplish
// as part of fulfilling the user's request.
// See protocol docs: [Plan Entries]
//
// [Plan Entries]: https://agentclientprotocol.com/protocol/v2/draft/agent-plan#plan-entries
type PlanEntry struct {
	// Human-readable description of what this task aims to accomplish.
	Content string `json:"content"`
	// The relative importance of this task.
	// Used to indicate which tasks are most critical to the overall goal.
	Priority PlanEntryPriority `json:"priority"`
	// Current execution status of this task.
	Status PlanEntryStatus `json:"status"`
	Meta   Meta            `json:"_meta,omitzero"`
}

// Cost information for a session.
type Cost struct {
	// Total cumulative cost for session.
	Amount float64 `json:"amount"`
	// ISO 4217 currency code (e.g., "USD", "EUR").
	Currency string `json:"currency"`
	Meta     Meta   `json:"_meta,omitzero"`
}

// Client-initiated session mutations permitted for a specific subagent session.
//
// A mutation requires an explicit per-child capability; support for the method
// on ordinary sessions does not grant support on a child.
//
// Experimental: not part of the spec yet; it may change or be removed.
type SubagentSessionCapabilities struct {
	// Permits the client to cancel this child's current work without ending
	// the session. Omitted or `null` means unsupported; an object (including
	// `{}`) means supported.
	Cancel *SessionCancelCapabilities `json:"cancel,omitzero"`
	Meta   Meta                       `json:"_meta,omitzero"`
}

// Capability to cancel work in a subagent session without ending that session.
//
// Supplying `{}` advertises support; an omitted or `null` `cancel` does not.
//
// Experimental: not part of the spec yet; it may change or be removed.
type SessionCancelCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Notification sent by the agent when a URL-based elicitation is complete.
type CompleteElicitationNotification struct {
	// The ID of the elicitation that completed.
	ElicitationID ElicitationID `json:"elicitationId"`
	// Optional. Omitted and `null` are equivalent and mean no metadata.
	Meta Meta `json:"_meta,omitzero"`
}

// Allows the Agent to send an arbitrary notification that is not part of the ACP spec.
// Extension notifications provide a way to send one-way messages for custom functionality
// while maintaining protocol compatibility.
//
// See protocol docs: [Extensibility]
//
// [Extensibility]: https://agentclientprotocol.com/protocol/v2/draft/extensibility
type ExtNotification = jsontext.Value

// Request parameters for the initialize method.
//
// Sent by the client to establish connection and negotiate capabilities.
//
// See protocol docs: [Initialization]
//
// [Initialization]: https://agentclientprotocol.com/protocol/v2/draft/initialization
type InitializeRequest struct {
	// The latest protocol version supported by the client.
	ProtocolVersion ProtocolVersion `json:"protocolVersion"`
	// Information about the implementation sending this initialize request.
	Info Implementation `json:"info"`
	// Capabilities supported by the client.
	Capabilities *ClientCapabilities `json:"capabilities,omitzero"`
	Meta         Meta                `json:"_meta,omitzero"`
}

// Capabilities supported by the client.
//
// Advertised during initialization to inform the agent about
// available features and methods.
//
// See protocol docs: [Client Capabilities]
//
// [Client Capabilities]: https://agentclientprotocol.com/protocol/v2/draft/initialization#client-capabilities
type ClientCapabilities struct {
	// Authentication capabilities supported by the client.
	// Determines which authentication method types the agent may include
	// in its `InitializeResponse`.
	//
	// Optional. Omitted or `null` both mean the client does not advertise any
	// authentication-method extensions.
	Auth *AuthCapabilities `json:"auth,omitzero"`
	// Elicitation capabilities supported by the client.
	// Determines which elicitation modes the agent may use.
	//
	// Optional. Omitted or `null` both mean the client does not advertise
	// elicitation support.
	Elicitation *ElicitationCapabilities `json:"elicitation,omitzero"`
	// NES (Next Edit Suggestions) capabilities supported by the client.
	//
	// Optional. Omitted or `null` both mean the client does not advertise any
	// NES suggestion-kind extensions.
	//
	// Experimental: not part of the spec yet; it may change or be removed.
	Nes *ClientNesCapabilities `json:"nes,omitzero"`
	// The position encodings supported by the client, in order of preference.
	//
	// Experimental: not part of the spec yet; it may change or be removed.
	PositionEncodings []PositionEncodingKind `json:"positionEncodings,omitzero"`
	Meta              Meta                   `json:"_meta,omitzero"`
}

// Authentication capabilities supported by the client.
//
// Advertised during initialization to inform the agent which authentication
// method types the client can handle. This governs opt-in types that require
// additional client-side support.
type AuthCapabilities struct {
	// Whether the client supports `terminal` authentication methods.
	//
	// Optional. Omitted or `null` both mean the client does not advertise support.
	// The client should supply `{}` only when it can reproduce the configured
	// agent invocation in an interactive terminal. Supplying `{}` means the
	// agent may include `terminal` entries in its authentication methods.
	Terminal *TerminalAuthCapabilities `json:"terminal,omitzero"`
	Meta     Meta                      `json:"_meta,omitzero"`
}

// Capabilities for terminal authentication methods.
//
// Supplying `{}` means the client can reproduce the configured agent
// invocation in an interactive terminal and supports terminal authentication
// methods.
type TerminalAuthCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Elicitation capabilities supported by the client.
type ElicitationCapabilities struct {
	// Whether the client supports form-based elicitation.
	//
	// Optional. Omitted and `null` are equivalent and mean form support is not advertised.
	// Supplying `{}` explicitly advertises form support.
	Form *ElicitationFormCapabilities `json:"form,omitzero"`
	// Whether the client supports URL-based elicitation.
	//
	// Optional. Omitted or `null` both mean the client does not advertise support.
	// Supplying `{}` means the client supports URL-based elicitation.
	URL *ElicitationURLCapabilities `json:"url,omitzero"`
	// Optional. Omitted and `null` are equivalent and mean no metadata.
	Meta Meta `json:"_meta,omitzero"`
}

// Form-based elicitation capabilities.
//
// Supplying `{}` means the client supports form-based elicitation.
type ElicitationFormCapabilities struct {
	// Optional. Omitted and `null` are equivalent and mean no metadata.
	Meta Meta `json:"_meta,omitzero"`
}

// URL-based elicitation capabilities.
//
// Supplying `{}` means the client supports URL-based elicitation.
type ElicitationURLCapabilities struct {
	// Optional. Omitted and `null` are equivalent and mean no metadata.
	Meta Meta `json:"_meta,omitzero"`
}

// NES capabilities advertised by the client during initialization.
type ClientNesCapabilities struct {
	// Whether the client supports the `jump` suggestion kind.
	Jump *NesJumpCapabilities `json:"jump,omitzero"`
	// Whether the client supports the `rename` suggestion kind.
	Rename *NesRenameCapabilities `json:"rename,omitzero"`
	// Whether the client supports the `searchAndReplace` suggestion kind.
	SearchAndReplace *NesSearchAndReplaceCapabilities `json:"searchAndReplace,omitzero"`
	Meta             Meta                             `json:"_meta,omitzero"`
}

// NesJumpCapabilities is a marker for jump suggestion support.
type NesJumpCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// NesRenameCapabilities is a marker for rename suggestion support.
type NesRenameCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// NesSearchAndReplaceCapabilities is a marker for search and replace suggestion support.
type NesSearchAndReplaceCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Request parameters for the `auth/login` method.
//
// Specifies which authentication method to use.
//
// Agents MUST support this method when their `initialize` response advertised
// at least one valid authentication method. Clients MUST NOT call this method
// when `authMethods` was omitted or empty.
type LoginAuthRequest struct {
	// The ID of the authentication method to use.
	// Must be one of the methods advertised in the initialize response.
	MethodID AuthMethodID `json:"methodId"`
	Meta     Meta         `json:"_meta,omitzero"`
}

// Request parameters for `providers/list`.
//
// Experimental: not part of the spec yet; it may change or be removed.
type ListProvidersRequest struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Request parameters for `providers/set`.
//
// Replaces the full configuration for one provider ID.
//
// Experimental: not part of the spec yet; it may change or be removed.
type SetProviderRequest struct {
	// Provider ID to configure.
	ProviderID ProviderID `json:"providerId"`
	// Protocol type for this provider.
	APIType LLMProtocol `json:"apiType"`
	// Base URL for requests sent through this provider.
	BaseURL string `json:"baseUrl"`
	// Full headers map for this provider.
	// May include authorization, routing, or other integration-specific headers.
	Headers map[string]string `json:"headers,omitzero"`
	Meta    Meta              `json:"_meta,omitzero"`
}

// Request parameters for `providers/disable`.
//
// Experimental: not part of the spec yet; it may change or be removed.
type DisableProviderRequest struct {
	// Provider ID to disable.
	ProviderID ProviderID `json:"providerId"`
	Meta       Meta       `json:"_meta,omitzero"`
}

// Request parameters for the `auth/logout` method.
//
// Terminates the current authenticated session.
//
// Agents MUST support this method when their `initialize` response advertised
// at least one valid authentication method. Clients MUST NOT call this method
// when `authMethods` was omitted or empty.
type LogoutAuthRequest struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Request parameters for creating a new session.
//
// See protocol docs: [Creating a Session]
//
// [Creating a Session]: https://agentclientprotocol.com/protocol/v2/draft/session-setup#creating-a-session
type NewSessionRequest struct {
	// The working directory for this session. Must be an absolute path.
	Cwd AbsolutePath `json:"cwd"`
	// Additional workspace roots for this session. Each path must be absolute.
	//
	// These expand the session's workspace scope without changing `cwd`, which
	// remains the base for relative paths. When omitted or empty, no
	// additional roots are activated for the new session.
	AdditionalDirectories []AbsolutePath `json:"additionalDirectories,omitzero"`
	// List of MCP (Model Context Protocol) servers the agent should connect to.
	MCPServers []MCPServer `json:"mcpServers,omitzero"`
	Meta       Meta        `json:"_meta,omitzero"`
}

// HTTPHeader is an HTTP header to set when making requests to the MCP server.
type HTTPHeader struct {
	// The name of the HTTP header.
	Name string `json:"name"`
	// The value to set for the HTTP header.
	Value string `json:"value"`
	Meta  Meta   `json:"_meta,omitzero"`
}

// Request parameters for listing existing sessions.
type ListSessionsRequest struct {
	// Filter sessions by working directory. Must be an absolute path.
	Cwd *AbsolutePath `json:"cwd,omitzero"`
	// Opaque cursor token from a previous response's nextCursor field for cursor-based pagination
	Cursor *SessionListCursor `json:"cursor,omitzero"`
	Meta   Meta               `json:"_meta,omitzero"`
}

// Request parameters for deleting an existing session from `session/list`.
//
// Only available if the Agent supports the `session.delete` capability.
type DeleteSessionRequest struct {
	// The ID of the session to delete.
	SessionID SessionID `json:"sessionId"`
	Meta      Meta      `json:"_meta,omitzero"`
}

// Request parameters for forking an existing session.
//
// Creates a new session based on the context of an existing one, allowing
// operations like generating summaries without affecting the original session's history.
//
// Only available if the Agent supports the `session.fork` capability.
//
// Experimental: not part of the spec yet; it may change or be removed.
type ForkSessionRequest struct {
	// The ID of the session to fork.
	SessionID SessionID `json:"sessionId"`
	// The working directory for this session. Must be an absolute path.
	Cwd AbsolutePath `json:"cwd"`
	// Additional workspace roots to activate for this session. Each path must be absolute.
	//
	// When omitted or empty, no additional roots are activated. When non-empty,
	// this is the complete resulting additional-root list for the forked
	// session.
	AdditionalDirectories []AbsolutePath `json:"additionalDirectories,omitzero"`
	// List of MCP servers to connect to for this session.
	MCPServers []MCPServer `json:"mcpServers,omitzero"`
	Meta       Meta        `json:"_meta,omitzero"`
}

// Request parameters for resuming an existing session.
//
// Resumes an existing session and optionally replays retained conversation
// history according to `replayFrom`.
type ResumeSessionRequest struct {
	// The ID of the session to resume.
	SessionID SessionID `json:"sessionId"`
	// The working directory for this session. Must be an absolute path.
	Cwd AbsolutePath `json:"cwd"`
	// Additional workspace roots to activate for this session. Each path must be absolute.
	//
	// When omitted or empty, no additional roots are activated. When non-empty,
	// this is the complete resulting additional-root list for the resumed
	// session. It may differ from any previously used or reported list as long as
	// the request `cwd` matches the session's `cwd`.
	AdditionalDirectories []AbsolutePath `json:"additionalDirectories,omitzero"`
	// List of MCP servers to connect to for this session.
	MCPServers []MCPServer `json:"mcpServers,omitzero"`
	// Inclusive cursor describing where conversation replay should begin.
	//
	// Optional. Omitted or `null` both mean the Agent should resume without
	// replaying previous conversation history. Replay cursors are inclusive:
	// replay includes the position identified by the cursor. Supplying
	// `{ "type": "start" }` means the Agent should replay all retained
	// conversation history before responding.
	ReplayFrom ReplayFrom `json:"replayFrom,omitzero"`
	Meta       Meta       `json:"_meta,omitzero"`
}

// Request parameters for closing an active session.
//
// The agent **must** cancel any ongoing work related to the session (treat it
// as if `session/cancel` was called) and then free up any resources associated
// with the session.
type CloseSessionRequest struct {
	// The ID of the session to close.
	SessionID SessionID `json:"sessionId"`
	Meta      Meta      `json:"_meta,omitzero"`
}

// Request parameters for sending a user prompt to the agent.
//
// Contains the user's message and any additional context.
//
// See protocol docs: [User Message]
//
// [User Message]: https://agentclientprotocol.com/protocol/v2/draft/prompt-lifecycle#1-user-message
type PromptRequest struct {
	// The ID of the session to send this user message to
	SessionID SessionID `json:"sessionId"`
	// The blocks of content that compose the user's message.
	//
	// As a baseline, the Agent MUST support [ContentBlockText] and [ContentBlockResourceLink],
	// while other variants are optionally enabled via [PromptCapabilities].
	//
	// The Client MUST adapt its interface according to [PromptCapabilities].
	//
	// The client MAY include referenced pieces of context as either
	// [ContentBlockResource] or [ContentBlockResourceLink].
	//
	// When available, [ContentBlockResource] is preferred
	// as it avoids extra round-trips and allows the message to include
	// pieces of context from sources the agent may not have access to.
	Prompt []ContentBlock `json:"prompt"`
	Meta   Meta           `json:"_meta,omitzero"`
}

// StartNesRequest is a request to start an NES session.
type StartNesRequest struct {
	// The root URI of the workspace.
	WorkspaceURI *string `json:"workspaceUri,omitzero"`
	// The workspace folders.
	WorkspaceFolders []WorkspaceFolder `json:"workspaceFolders,omitzero"`
	// Repository metadata, if the workspace is a git repository.
	Repository *NesRepository `json:"repository,omitzero"`
	Meta       Meta           `json:"_meta,omitzero"`
}

// WorkspaceFolder is a workspace folder.
type WorkspaceFolder struct {
	// The URI of the folder.
	URI string `json:"uri"`
	// The display name of the folder.
	Name string `json:"name"`
	Meta Meta   `json:"_meta,omitzero"`
}

// Repository metadata for an NES session.
type NesRepository struct {
	// The repository name.
	Name string `json:"name"`
	// The repository owner.
	Owner string `json:"owner"`
	// The remote URL of the repository.
	RemoteURL string `json:"remoteUrl"`
	Meta      Meta   `json:"_meta,omitzero"`
}

// SuggestNesRequest is a request for a code suggestion.
type SuggestNesRequest struct {
	// The session ID for this request.
	SessionID SessionID `json:"sessionId"`
	// The URI of the document to suggest for.
	URI string `json:"uri"`
	// The version number of the document.
	Version int64 `json:"version"`
	// The current cursor position.
	Position Position `json:"position"`
	// The current text selection range, if any.
	Selection *Range `json:"selection,omitzero"`
	// What triggered this suggestion request.
	TriggerKind NesTriggerKind `json:"triggerKind"`
	// Context for the suggestion, included based on agent capabilities.
	Context *NesSuggestContext `json:"context,omitzero"`
	Meta    Meta               `json:"_meta,omitzero"`
}

// Context attached to a suggestion request.
type NesSuggestContext struct {
	// Recently accessed files.
	RecentFiles []NesRecentFile `json:"recentFiles,omitzero"`
	// Related code snippets.
	RelatedSnippets []NesRelatedSnippet `json:"relatedSnippets,omitzero"`
	// Recent edit history.
	EditHistory []NesEditHistoryEntry `json:"editHistory,omitzero"`
	// Recent user actions (typing, navigation, etc.).
	UserActions []NesUserAction `json:"userActions,omitzero"`
	// Currently open files in the editor.
	OpenFiles []NesOpenFile `json:"openFiles,omitzero"`
	// Current diagnostics (errors, warnings).
	Diagnostics []NesDiagnostic `json:"diagnostics,omitzero"`
	Meta        Meta            `json:"_meta,omitzero"`
}

// NesRecentFile is a recently accessed file.
type NesRecentFile struct {
	// The URI of the file.
	URI string `json:"uri"`
	// The language identifier.
	LanguageID string `json:"languageId"`
	// The full text content of the file.
	Text string `json:"text"`
	Meta Meta   `json:"_meta,omitzero"`
}

// NesRelatedSnippet is a related code snippet from a file.
type NesRelatedSnippet struct {
	// The URI of the file containing the snippets.
	URI string `json:"uri"`
	// The code excerpts.
	Excerpts []NesExcerpt `json:"excerpts"`
	Meta     Meta         `json:"_meta,omitzero"`
}

// NesExcerpt is a code excerpt from a file.
type NesExcerpt struct {
	// The start line of the excerpt (zero-based).
	StartLine uint32 `json:"startLine"`
	// The end line of the excerpt (zero-based).
	EndLine uint32 `json:"endLine"`
	// The text content of the excerpt.
	Text string `json:"text"`
	Meta Meta   `json:"_meta,omitzero"`
}

// NesEditHistoryEntry is an entry in the edit history.
type NesEditHistoryEntry struct {
	// The URI of the edited file.
	URI string `json:"uri"`
	// A diff representing the edit.
	Diff string `json:"diff"`
	Meta Meta   `json:"_meta,omitzero"`
}

// NesUserAction is a user action (typing, cursor movement, etc.).
type NesUserAction struct {
	// The kind of action (e.g., "insertChar", "cursorMovement").
	Action string `json:"action"`
	// The URI of the file where the action occurred.
	URI string `json:"uri"`
	// The position where the action occurred.
	Position Position `json:"position"`
	// Timestamp in milliseconds since epoch.
	TimestampMs uint64 `json:"timestampMs"`
	Meta        Meta   `json:"_meta,omitzero"`
}

// NesOpenFile is an open file in the editor.
type NesOpenFile struct {
	// The URI of the file.
	URI string `json:"uri"`
	// The language identifier.
	LanguageID string `json:"languageId"`
	// The visible range in the editor, if any.
	VisibleRange *Range `json:"visibleRange,omitzero"`
	// Timestamp in milliseconds since epoch of when the file was last focused.
	LastFocusedMs *uint64 `json:"lastFocusedMs,omitzero"`
	Meta          Meta    `json:"_meta,omitzero"`
}

// NesDiagnostic is a diagnostic (error, warning, etc.).
type NesDiagnostic struct {
	// The URI of the file containing the diagnostic.
	URI string `json:"uri"`
	// The range of the diagnostic.
	Range Range `json:"range"`
	// The severity of the diagnostic.
	Severity NesDiagnosticSeverity `json:"severity"`
	// The diagnostic message.
	Message string `json:"message"`
	Meta    Meta   `json:"_meta,omitzero"`
}

// CloseNesRequest is a request to close an NES session.
//
// The agent **must** cancel any ongoing work related to the NES session
// and then free up any resources associated with the session.
type CloseNesRequest struct {
	// The ID of the NES session to close.
	SessionID SessionID `json:"sessionId"`
	Meta      Meta      `json:"_meta,omitzero"`
}

// RequestPermissionResponse is a response to a permission request.
type RequestPermissionResponse struct {
	// The user's decision on the permission request.
	Outcome RequestPermissionOutcome `json:"outcome"`
	Meta    Meta                     `json:"_meta,omitzero"`
}

// ElicitationAcceptAction is the user accepted the elicitation and provided content.
type ElicitationAcceptAction struct {
	// The user-provided content, if any, as an object matching the requested schema.
	Content map[string]ElicitationContentValue `json:"content,omitzero"`
}

// MCPError is an inner MCP error, distinct from an outer ACP binding or runtime error.
//
// `code` and `message` are required and non-null. `data` is optional;
// explicit `null` is preserved separately from an omitted key.
//
// Experimental: not part of the spec yet; it may change or be removed.
type MCPError struct {
	// Inner MCP error code; never an ACP error code.
	Code int32 `json:"code"`
	// Inner MCP error message.
	Message string `json:"message"`
	// Optional error data; explicit null is retained.
	Data                 jsontext.Value            `json:"data,omitzero"`
	AdditionalProperties map[string]jsontext.Value `json:",embed"`
}

// CancelSessionNotification is a notification to cancel ongoing operations for a session.
//
// See protocol docs: [Cancellation]
//
// [Cancellation]: https://agentclientprotocol.com/protocol/v2/draft/prompt-lifecycle#cancellation
type CancelSessionNotification struct {
	// The ID of the session to cancel operations for.
	SessionID SessionID `json:"sessionId"`
	Meta      Meta      `json:"_meta,omitzero"`
}

// Notification sent when a file is opened in the editor.
type DidOpenDocumentNotification struct {
	// The session ID for this notification.
	SessionID SessionID `json:"sessionId"`
	// The URI of the opened document.
	URI string `json:"uri"`
	// The language identifier of the document (e.g., "rust", "python").
	LanguageID string `json:"languageId"`
	// The version number of the document.
	Version int64 `json:"version"`
	// The full text content of the document.
	Text string `json:"text"`
	Meta Meta   `json:"_meta,omitzero"`
}

// Notification sent when a file is edited.
type DidChangeDocumentNotification struct {
	// The session ID for this notification.
	SessionID SessionID `json:"sessionId"`
	// The URI of the changed document.
	URI string `json:"uri"`
	// The new version number of the document.
	Version int64 `json:"version"`
	// The content changes.
	ContentChanges []TextDocumentContentChangeEvent `json:"contentChanges"`
	Meta           Meta                             `json:"_meta,omitzero"`
}

// TextDocumentContentChangeEvent is a content change event for a document.
//
// When `range` is `None`, `text` is the full content of the document.
// When `range` is `Some`, `text` replaces the given range.
type TextDocumentContentChangeEvent struct {
	// The range of the document that changed. If `None`, the entire content is replaced.
	Range *Range `json:"range,omitzero"`
	// The new text for the range, or the full document content if `range` is `None`.
	Text string `json:"text"`
	Meta Meta   `json:"_meta,omitzero"`
}

// Notification sent when a file is closed.
type DidCloseDocumentNotification struct {
	// The session ID for this notification.
	SessionID SessionID `json:"sessionId"`
	// The URI of the closed document.
	URI  string `json:"uri"`
	Meta Meta   `json:"_meta,omitzero"`
}

// Notification sent when a file is saved.
type DidSaveDocumentNotification struct {
	// The session ID for this notification.
	SessionID SessionID `json:"sessionId"`
	// The URI of the saved document.
	URI  string `json:"uri"`
	Meta Meta   `json:"_meta,omitzero"`
}

// DidFocusDocumentNotification is a notification sent when a file becomes the active editor tab.
type DidFocusDocumentNotification struct {
	// The session ID for this notification.
	SessionID SessionID `json:"sessionId"`
	// The URI of the focused document.
	URI string `json:"uri"`
	// The version number of the document.
	Version int64 `json:"version"`
	// The current cursor position.
	Position Position `json:"position"`
	// The portion of the file currently visible in the editor viewport.
	VisibleRange Range `json:"visibleRange"`
	Meta         Meta  `json:"_meta,omitzero"`
}

// Notification sent when a suggestion is accepted.
type AcceptNesNotification struct {
	// The session ID for this notification.
	SessionID SessionID `json:"sessionId"`
	// The ID of the accepted suggestion.
	SuggestionID NesSuggestionID `json:"suggestionId"`
	Meta         Meta            `json:"_meta,omitzero"`
}

// Notification sent when a suggestion is rejected.
type RejectNesNotification struct {
	// The session ID for this notification.
	SessionID SessionID `json:"sessionId"`
	// The ID of the rejected suggestion.
	SuggestionID NesSuggestionID `json:"suggestionId"`
	// The reason for rejection.
	Reason *NesRejectReason `json:"reason,omitzero"`
	Meta   Meta             `json:"_meta,omitzero"`
}

// MessageMCPNotification is a notification for an active request, sent from provider to consumer.
// Includes subscription acknowledgements and updates.
//
// Experimental: not part of the spec yet; it may change or be removed.
type MessageMCPNotification struct {
	// The declared ACP MCP server handling the associated request.
	ServerID MCPServerACPID `json:"serverId"`
	// The identifier of the active inner MCP request.
	RequestID MCPRequestID `json:"requestId"`
	// The inner MCP method name.
	Method string `json:"method"`
	// Optional inner MCP params; null is equivalent to omission.
	Params map[string]jsontext.Value `json:"params,omitzero"`
	// ACP extension metadata (not inner MCP params._meta); null is equivalent to omission.
	Meta Meta `json:"_meta,omitzero"`
}

// CancelRequestNotification is a notification to cancel an ongoing request.
//
// See protocol docs: [Cancellation]
//
// [Cancellation]: https://agentclientprotocol.com/protocol/v2/draft/cancellation
type CancelRequestNotification struct {
	// The ID of the request to cancel.
	RequestID RequestID `json:"requestId"`
	Meta      Meta      `json:"_meta,omitzero"`
}

type CreateElicitationRequestFormSession struct {
	// The session this elicitation is tied to.
	SessionID SessionID `json:"sessionId"`
	// Optional tool call within the session.
	//
	// Optional. Omitted and `null` are equivalent and mean the elicitation is scoped to the
	// session without a specific tool call.
	ToolCallID *ToolCallID `json:"toolCallId,omitzero"`
	// A JSON Schema describing the form fields to present to the user.
	RequestedSchema ElicitationSchema `json:"requestedSchema"`
	// Always "form": MarshalJSONTo writes it whatever the field holds.
	Mode string `json:"mode"`
	// A human-readable message describing what input is needed.
	Message string `json:"message"`
	// Optional. Omitted and `null` are equivalent and mean no metadata.
	Meta Meta `json:"_meta,omitzero"`
}

// MarshalJSONTo encodes v with its literal members fixed.
func (v CreateElicitationRequestFormSession) MarshalJSONTo(enc *jsontext.Encoder) error {
	v.Mode = "form"
	type plain CreateElicitationRequestFormSession
	return json.MarshalEncode(enc, plain(v))
}

type CreateElicitationRequestFormRequest struct {
	// The request this elicitation is tied to.
	RequestID RequestID `json:"requestId"`
	// A JSON Schema describing the form fields to present to the user.
	RequestedSchema ElicitationSchema `json:"requestedSchema"`
	// Always "form": MarshalJSONTo writes it whatever the field holds.
	Mode string `json:"mode"`
	// A human-readable message describing what input is needed.
	Message string `json:"message"`
	// Optional. Omitted and `null` are equivalent and mean no metadata.
	Meta Meta `json:"_meta,omitzero"`
}

// MarshalJSONTo encodes v with its literal members fixed.
func (v CreateElicitationRequestFormRequest) MarshalJSONTo(enc *jsontext.Encoder) error {
	v.Mode = "form"
	type plain CreateElicitationRequestFormRequest
	return json.MarshalEncode(enc, plain(v))
}

type CreateElicitationRequestURLSession struct {
	// The session this elicitation is tied to.
	SessionID SessionID `json:"sessionId"`
	// Optional tool call within the session.
	//
	// Optional. Omitted and `null` are equivalent and mean the elicitation is scoped to the
	// session without a specific tool call.
	ToolCallID *ToolCallID `json:"toolCallId,omitzero"`
	// The unique identifier for this elicitation.
	ElicitationID ElicitationID `json:"elicitationId"`
	// The URL to direct the user to.
	URL string `json:"url"`
	// Always "url": MarshalJSONTo writes it whatever the field holds.
	Mode string `json:"mode"`
	// A human-readable message describing what input is needed.
	Message string `json:"message"`
	// Optional. Omitted and `null` are equivalent and mean no metadata.
	Meta Meta `json:"_meta,omitzero"`
}

// MarshalJSONTo encodes v with its literal members fixed.
func (v CreateElicitationRequestURLSession) MarshalJSONTo(enc *jsontext.Encoder) error {
	v.Mode = "url"
	type plain CreateElicitationRequestURLSession
	return json.MarshalEncode(enc, plain(v))
}

type CreateElicitationRequestURLRequest struct {
	// The request this elicitation is tied to.
	RequestID RequestID `json:"requestId"`
	// The unique identifier for this elicitation.
	ElicitationID ElicitationID `json:"elicitationId"`
	// The URL to direct the user to.
	URL string `json:"url"`
	// Always "url": MarshalJSONTo writes it whatever the field holds.
	Mode string `json:"mode"`
	// A human-readable message describing what input is needed.
	Message string `json:"message"`
	// Optional. Omitted and `null` are equivalent and mean no metadata.
	Meta Meta `json:"_meta,omitzero"`
}

// MarshalJSONTo encodes v with its literal members fixed.
func (v CreateElicitationRequestURLRequest) MarshalJSONTo(enc *jsontext.Encoder) error {
	v.Mode = "url"
	type plain CreateElicitationRequestURLRequest
	return json.MarshalEncode(enc, plain(v))
}

type CreateElicitationRequestCustomSession struct {
	// The session this elicitation is tied to.
	SessionID SessionID `json:"sessionId"`
	// Optional tool call within the session.
	//
	// Optional. Omitted and `null` are equivalent and mean the elicitation is scoped to the
	// session without a specific tool call.
	ToolCallID *ToolCallID `json:"toolCallId,omitzero"`
	// Custom or future elicitation mode.
	//
	// Values beginning with `_` are reserved for implementation-specific
	// extensions. Unknown values that do not begin with `_` are reserved for
	// future ACP variants.
	Mode string `json:"mode"`
	// A human-readable message describing what input is needed.
	Message string `json:"message"`
	// Optional. Omitted and `null` are equivalent and mean no metadata.
	Meta                 Meta                      `json:"_meta,omitzero"`
	AdditionalProperties map[string]jsontext.Value `json:",embed"`
}

type CreateElicitationRequestCustomRequest struct {
	// The request this elicitation is tied to.
	RequestID RequestID `json:"requestId"`
	// Custom or future elicitation mode.
	//
	// Values beginning with `_` are reserved for implementation-specific
	// extensions. Unknown values that do not begin with `_` are reserved for
	// future ACP variants.
	Mode string `json:"mode"`
	// A human-readable message describing what input is needed.
	Message string `json:"message"`
	// Optional. Omitted and `null` are equivalent and mean no metadata.
	Meta                 Meta                      `json:"_meta,omitzero"`
	AdditionalProperties map[string]jsontext.Value `json:",embed"`
}

type ElicitationFormModeSession struct {
	// The session this elicitation is tied to.
	SessionID SessionID `json:"sessionId"`
	// Optional tool call within the session.
	//
	// Optional. Omitted and `null` are equivalent and mean the elicitation is scoped to the
	// session without a specific tool call.
	ToolCallID *ToolCallID `json:"toolCallId,omitzero"`
	// A JSON Schema describing the form fields to present to the user.
	RequestedSchema ElicitationSchema `json:"requestedSchema"`
}

type ElicitationFormModeRequest struct {
	// The request this elicitation is tied to.
	RequestID RequestID `json:"requestId"`
	// A JSON Schema describing the form fields to present to the user.
	RequestedSchema ElicitationSchema `json:"requestedSchema"`
}

type ElicitationURLModeSession struct {
	// The session this elicitation is tied to.
	SessionID SessionID `json:"sessionId"`
	// Optional tool call within the session.
	//
	// Optional. Omitted and `null` are equivalent and mean the elicitation is scoped to the
	// session without a specific tool call.
	ToolCallID *ToolCallID `json:"toolCallId,omitzero"`
	// The unique identifier for this elicitation.
	ElicitationID ElicitationID `json:"elicitationId"`
	// The URL to direct the user to.
	URL string `json:"url"`
}

type ElicitationURLModeRequest struct {
	// The request this elicitation is tied to.
	RequestID RequestID `json:"requestId"`
	// The unique identifier for this elicitation.
	ElicitationID ElicitationID `json:"elicitationId"`
	// The URL to direct the user to.
	URL string `json:"url"`
}

type MessageMCPResponseResult struct {
	// Required, even if JSON null.
	Result jsontext.Value `json:"result"`
	// Optional ACP carrier metadata.
	Meta Meta `json:"_meta,omitzero"`
}

type MessageMCPResponseError struct {
	// Required, non-null MCP error object.
	Error MCPError `json:"error"`
	// Optional ACP carrier metadata.
	Meta Meta `json:"_meta,omitzero"`
}

// Meta is the _meta extension object reserved on protocol messages.
type Meta = meta.Meta
