// Code generated by acp-schema from the TypeScript SDK; DO NOT EDIT.

package schema

// SessionID is a unique identifier for a conversation session between a client and agent.
//
// Sessions maintain their own context, conversation history, and state,
// allowing multiple independent interactions with the same agent.
//
// See protocol docs: [Session ID]
//
// [Session ID]: https://agentclientprotocol.com/protocol/session-setup#session-id
type SessionID string

// ToolCallID is a unique identifier for a tool call within a session.
type ToolCallID string

// Categories of tools that can be invoked.
//
// Tool kinds help clients choose appropriate icons and optimize how they
// display tool execution progress.
//
// See protocol docs: [Creating]
//
// [Creating]: https://agentclientprotocol.com/protocol/tool-calls#creating
type ToolKind string

const (
	ToolKindRead       ToolKind = "read"
	ToolKindEdit       ToolKind = "edit"
	ToolKindDelete     ToolKind = "delete"
	ToolKindMove       ToolKind = "move"
	ToolKindSearch     ToolKind = "search"
	ToolKindExecute    ToolKind = "execute"
	ToolKindThink      ToolKind = "think"
	ToolKindFetch      ToolKind = "fetch"
	ToolKindSwitchMode ToolKind = "switch_mode"
	ToolKindOther      ToolKind = "other"
)

// Execution status of a tool call.
//
// Tool calls progress through different statuses during their lifecycle.
//
// See protocol docs: [Status]
//
// [Status]: https://agentclientprotocol.com/protocol/tool-calls#status
type ToolCallStatus string

const (
	ToolCallStatusPending    ToolCallStatus = "pending"
	ToolCallStatusInProgress ToolCallStatus = "in_progress"
	ToolCallStatusCompleted  ToolCallStatus = "completed"
	ToolCallStatusFailed     ToolCallStatus = "failed"
)

// Role is the sender or recipient of messages and data in a conversation.
type Role string

const (
	RoleAssistant Role = "assistant"
	RoleUser      Role = "user"
)

// Typed identifier used for terminal values on the wire.
type TerminalID string

// PermissionOptionID is a unique identifier for a permission option.
type PermissionOptionID string

// PermissionOptionKind is the type of permission option being presented to the user.
//
// Helps clients choose appropriate icons and UI treatment.
type PermissionOptionKind string

const (
	PermissionOptionKindAllowOnce    PermissionOptionKind = "allow_once"
	PermissionOptionKindAllowAlways  PermissionOptionKind = "allow_always"
	PermissionOptionKindRejectOnce   PermissionOptionKind = "reject_once"
	PermissionOptionKindRejectAlways PermissionOptionKind = "reject_always"
)

// Object schema type.
type ElicitationSchemaType string

const (
	ElicitationSchemaTypeObject ElicitationSchemaType = "object"
)

// String format types for string properties in elicitation schemas.
type StringFormat string

const (
	StringFormatEmail    StringFormat = "email"
	StringFormatURI      StringFormat = "uri"
	StringFormatDate     StringFormat = "date"
	StringFormatDateTime StringFormat = "date-time"
)

// ElicitationID is a unique identifier for an elicitation.
type ElicitationID string

// MCPServerACPID is a unique identifier for an MCP server using the ACP transport.
//
// The value is opaque and generated by the ACP component providing the MCP server. It is
// used by `mcp/message` to route requests to the component that declared the server.
//
// Experimental: not part of the spec yet; it may change or be removed.
type MCPServerACPID string

// Identifies an inner MCP request active against a server on this ACP connection.
//
// Generated by the caller and preserved unchanged by proxies. This is distinct
// from the outer ACP JSON-RPC request ID.
//
// Experimental: not part of the spec yet; it may change or be removed.
type MCPRequestID string

// Protocol version identifier.
//
// This version is only bumped for breaking changes.
// Non-breaking changes should be introduced via capabilities.
type ProtocolVersion uint16

// How the agent wants document changes delivered.
type TextDocumentSyncKind string

const (
	TextDocumentSyncKindFull        TextDocumentSyncKind = "full"
	TextDocumentSyncKindIncremental TextDocumentSyncKind = "incremental"
)

// PositionEncodingKind is the encoding used for character offsets in positions.
//
// Follows the same conventions as LSP 3.17. The default is UTF-16.
type PositionEncodingKind string

const (
	PositionEncodingKindUTF16 PositionEncodingKind = "utf-16"
	PositionEncodingKindUTF32 PositionEncodingKind = "utf-32"
	PositionEncodingKindUTF8  PositionEncodingKind = "utf-8"
)

// Typed identifier used for auth method values on the wire.
type AuthMethodID string

// ProviderID is a unique identifier for a configurable LLM provider.
//
// Experimental: not part of the spec yet; it may change or be removed.
type ProviderID string

// LLMProtocol also accepts values outside the listed constants; use [LLMProtocol.Known] to check.
//
// Well-known API protocol identifiers for LLM providers.
//
// Agents and clients MUST handle unknown protocol identifiers gracefully.
//
// Protocol names beginning with `_` are free for custom use, like other ACP extension methods.
// Protocol names that do not begin with `_` are reserved for the ACP spec.
//
// Experimental: not part of the spec yet; it may change or be removed.
type LLMProtocol string

const (
	LLMProtocolAnthropic LLMProtocol = "anthropic"
	LLMProtocolOpenAI    LLMProtocol = "openai"
	LLMProtocolAzure     LLMProtocol = "azure"
	LLMProtocolVertex    LLMProtocol = "vertex"
	LLMProtocolBedrock   LLMProtocol = "bedrock"
)

// Known reports whether v is one of the protocol-defined constants.
func (v LLMProtocol) Known() bool {
	switch v {
	case LLMProtocolAnthropic, LLMProtocolOpenAI, LLMProtocolAzure, LLMProtocolVertex, LLMProtocolBedrock:
		return true
	}
	return false
}

// SessionModeID is a unique identifier for a Session Mode.
type SessionModeID string

// SessionConfigID is a unique identifier for a session configuration option.
type SessionConfigID string

// SessionConfigOptionCategory also accepts values outside the listed constants; use [SessionConfigOptionCategory.Known] to check.
//
// Semantic category for a session configuration option.
//
// This is intended to help Clients distinguish broadly common selectors (e.g. model selector vs
// session mode selector vs thought/reasoning level) for UX purposes (keyboard shortcuts, icons,
// placement). It MUST NOT be required for correctness. Clients MUST handle missing or unknown
// categories gracefully.
//
// Category names beginning with `_` are free for custom use, like other ACP extension methods.
// Category names that do not begin with `_` are reserved for the ACP spec.
type SessionConfigOptionCategory string

const (
	SessionConfigOptionCategoryMode         SessionConfigOptionCategory = "mode"
	SessionConfigOptionCategoryModel        SessionConfigOptionCategory = "model"
	SessionConfigOptionCategoryModelConfig  SessionConfigOptionCategory = "model_config"
	SessionConfigOptionCategoryThoughtLevel SessionConfigOptionCategory = "thought_level"
)

// Known reports whether v is one of the protocol-defined constants.
func (v SessionConfigOptionCategory) Known() bool {
	switch v {
	case SessionConfigOptionCategoryMode, SessionConfigOptionCategoryModel, SessionConfigOptionCategoryModelConfig, SessionConfigOptionCategoryThoughtLevel:
		return true
	}
	return false
}

// SessionConfigValueID is a unique identifier for a session configuration option value.
type SessionConfigValueID string

// SessionConfigGroupID is a unique identifier for a session configuration option value group.
type SessionConfigGroupID string

// Reasons why an agent stops processing a prompt turn.
//
// See protocol docs: [Stop Reasons]
//
// [Stop Reasons]: https://agentclientprotocol.com/protocol/prompt-turn#stop-reasons
type StopReason string

const (
	StopReasonEndTurn         StopReason = "end_turn"
	StopReasonMaxTokens       StopReason = "max_tokens"
	StopReasonMaxTurnRequests StopReason = "max_turn_requests"
	StopReasonRefusal         StopReason = "refusal"
	StopReasonCancelled       StopReason = "cancelled"
)

// NesSuggestionID is a unique identifier for a next edit suggestion.
type NesSuggestionID string

// ErrorCode also accepts values outside the listed constants; use [ErrorCode.Known] to check.
//
// Predefined error codes for common JSON-RPC and ACP-specific errors.
//
// These codes follow the JSON-RPC 2.0 specification for standard errors
// and use the reserved range (-32000 to -32099) for protocol-specific errors.
type ErrorCode int32

const (
	ErrorCodeParseError             ErrorCode = -32700
	ErrorCodeInvalidRequest         ErrorCode = -32600
	ErrorCodeMethodNotFound         ErrorCode = -32601
	ErrorCodeInvalidParams          ErrorCode = -32602
	ErrorCodeInternalError          ErrorCode = -32603
	ErrorCodeRequestCancelled       ErrorCode = -32800
	ErrorCodeAuthenticationRequired ErrorCode = -32000
	ErrorCodeResourceNotFound       ErrorCode = -32002
)

// Known reports whether v is one of the protocol-defined constants.
func (v ErrorCode) Known() bool {
	switch v {
	case ErrorCodeParseError, ErrorCodeInvalidRequest, ErrorCodeMethodNotFound, ErrorCodeInvalidParams, ErrorCodeInternalError, ErrorCodeRequestCancelled, ErrorCodeAuthenticationRequired, ErrorCodeResourceNotFound:
		return true
	}
	return false
}

// MessageID is a unique identifier for a message within a session.
type MessageID string

// Priority levels for plan entries.
//
// Used to indicate the relative importance or urgency of different
// tasks in the execution plan.
// See protocol docs: [Plan Entries]
//
// [Plan Entries]: https://agentclientprotocol.com/protocol/agent-plan#plan-entries
type PlanEntryPriority string

const (
	PlanEntryPriorityHigh   PlanEntryPriority = "high"
	PlanEntryPriorityMedium PlanEntryPriority = "medium"
	PlanEntryPriorityLow    PlanEntryPriority = "low"
)

// Status of a plan entry in the execution flow.
//
// Tracks the lifecycle of each task from planning through completion.
// See protocol docs: [Plan Entries]
//
// [Plan Entries]: https://agentclientprotocol.com/protocol/agent-plan#plan-entries
type PlanEntryStatus string

const (
	PlanEntryStatusPending    PlanEntryStatus = "pending"
	PlanEntryStatusInProgress PlanEntryStatus = "in_progress"
	PlanEntryStatusCompleted  PlanEntryStatus = "completed"
)

// PlanID is a unique identifier for a plan within a session.
//
// Experimental: not part of the spec yet; it may change or be removed.
type PlanID string

// NoticeSeverity also accepts values outside the listed constants; use [NoticeSeverity.Known] to check.
//
// Severity hint for a session notice.
//
// Experimental: not part of the spec yet; it may change or be removed.
type NoticeSeverity string

const (
	NoticeSeverityInfo    NoticeSeverity = "info"
	NoticeSeverityWarning NoticeSeverity = "warning"
	NoticeSeverityError   NoticeSeverity = "error"
)

// Known reports whether v is one of the protocol-defined constants.
func (v NoticeSeverity) Known() bool {
	switch v {
	case NoticeSeverityInfo, NoticeSeverityWarning, NoticeSeverityError:
		return true
	}
	return false
}

// CompactionID is a unique identifier for a context compaction within a session.
//
// Experimental: not part of the spec yet; it may change or be removed.
type CompactionID string

// CompactionStatus also accepts values outside the listed constants; use [CompactionStatus.Known] to check.
//
// Lifecycle state of a context compaction.
//
// Experimental: not part of the spec yet; it may change or be removed.
type CompactionStatus string

const (
	CompactionStatusInProgress CompactionStatus = "in_progress"
	CompactionStatusCompleted  CompactionStatus = "completed"
	CompactionStatusFailed     CompactionStatus = "failed"
	CompactionStatusCancelled  CompactionStatus = "cancelled"
)

// Known reports whether v is one of the protocol-defined constants.
func (v CompactionStatus) Known() bool {
	switch v {
	case CompactionStatusInProgress, CompactionStatusCompleted, CompactionStatusFailed, CompactionStatusCancelled:
		return true
	}
	return false
}

// What triggered the suggestion request.
type NesTriggerKind string

const (
	NesTriggerKindAutomatic  NesTriggerKind = "automatic"
	NesTriggerKindDiagnostic NesTriggerKind = "diagnostic"
	NesTriggerKindManual     NesTriggerKind = "manual"
)

// Severity of a diagnostic.
type NesDiagnosticSeverity string

const (
	NesDiagnosticSeverityError       NesDiagnosticSeverity = "error"
	NesDiagnosticSeverityWarning     NesDiagnosticSeverity = "warning"
	NesDiagnosticSeverityInformation NesDiagnosticSeverity = "information"
	NesDiagnosticSeverityHint        NesDiagnosticSeverity = "hint"
)

// The reason a suggestion was rejected.
type NesRejectReason string

const (
	NesRejectReasonRejected  NesRejectReason = "rejected"
	NesRejectReasonIgnored   NesRejectReason = "ignored"
	NesRejectReasonReplaced  NesRejectReason = "replaced"
	NesRejectReasonCancelled NesRejectReason = "cancelled"
)
