// Code generated by acp-schema from the TypeScript SDK; DO NOT EDIT.

package schema

import (
	"encoding/json/jsontext"
	"encoding/json/v2"

	"github.com/ironpark/acp-go/schema/meta"
)

// WriteTextFileRequest is a request to write content to a text file.
//
// Only available if the client supports the `fs.writeTextFile` capability.
type WriteTextFileRequest struct {
	// The session ID for this request.
	SessionID SessionID `json:"sessionId"`
	// Absolute path to the file to write.
	Path string `json:"path"`
	// The text content to write to the file.
	Content string `json:"content"`
	Meta    Meta   `json:"_meta,omitzero"`
}

// ReadTextFileRequest is a request to read content from a text file.
//
// Only available if the client supports the `fs.readTextFile` capability.
type ReadTextFileRequest struct {
	// The session ID for this request.
	SessionID SessionID `json:"sessionId"`
	// Absolute path to the file to read.
	Path string `json:"path"`
	// Line number to start reading from (1-based).
	Line *uint32 `json:"line,omitzero"`
	// Maximum number of lines to read.
	Limit *uint32 `json:"limit,omitzero"`
	Meta  Meta    `json:"_meta,omitzero"`
}

// RequestPermissionRequest is a request for user permission to execute a tool call.
//
// Sent when the agent needs authorization before performing a sensitive operation.
//
// See protocol docs: [Requesting Permission]
//
// [Requesting Permission]: https://agentclientprotocol.com/protocol/tool-calls#requesting-permission
type RequestPermissionRequest struct {
	// The session ID for this request.
	SessionID SessionID `json:"sessionId"`
	// Details about the tool call requiring permission.
	ToolCall ToolCallUpdate `json:"toolCall"`
	// Available permission options for the user to choose from.
	Options []PermissionOption `json:"options"`
	Meta    Meta               `json:"_meta,omitzero"`
}

// ToolCallUpdate is an update to an existing tool call.
//
// Used to report progress and results as tools execute. All fields except
// the tool call ID are optional - only changed fields need to be included.
//
// See protocol docs: [Updating]
//
// [Updating]: https://agentclientprotocol.com/protocol/tool-calls#updating
type ToolCallUpdate struct {
	// The ID of the tool call being updated.
	ToolCallID ToolCallID `json:"toolCallId"`
	// Update the tool kind.
	Kind *ToolKind `json:"kind,omitzero"`
	// Update the execution status.
	Status *ToolCallStatus `json:"status,omitzero"`
	// Update the human-readable title.
	Title *string `json:"title,omitzero"`
	// Update the programmatic name of the tool being invoked.
	//
	// This field is optional. Omitting it or sending `null` both mean that
	// the existing name is left unchanged.
	Name *string `json:"name,omitzero"`
	// Replace the content collection.
	Content []ToolCallContent `json:"content,omitzero"`
	// Replace the locations collection.
	Locations []ToolCallLocation `json:"locations,omitzero"`
	// Update the raw input.
	RawInput jsontext.Value `json:"rawInput,omitzero"`
	// Update the raw output.
	RawOutput jsontext.Value `json:"rawOutput,omitzero"`
	Meta      Meta           `json:"_meta,omitzero"`
}

// Optional annotations for the client. The client can use annotations to inform how objects are used or displayed
type Annotations struct {
	// Intended recipients for this content, such as the user or assistant.
	Audience []Role `json:"audience,omitzero"`
	// Timestamp indicating when the underlying resource was last modified.
	LastModified *string `json:"lastModified,omitzero"`
	// Relative importance of this content when clients choose what to surface.
	Priority *float64 `json:"priority,omitzero"`
	Meta     Meta     `json:"_meta,omitzero"`
}

// Text-based resource contents.
type TextResourceContents struct {
	// MIME type describing the encoded media payload.
	MIMEType *string `json:"mimeType,omitzero"`
	// Text payload carried by this content block.
	Text string `json:"text"`
	// URI associated with this resource or media payload.
	URI  string `json:"uri"`
	Meta Meta   `json:"_meta,omitzero"`
}

// Binary resource contents.
type BlobResourceContents struct {
	// Base64-encoded bytes for a binary resource payload.
	Blob string `json:"blob"`
	// MIME type describing the encoded media payload.
	MIMEType *string `json:"mimeType,omitzero"`
	// URI associated with this resource or media payload.
	URI  string `json:"uri"`
	Meta Meta   `json:"_meta,omitzero"`
}

// ToolCallLocation is a file location being accessed or modified by a tool.
//
// Enables clients to implement "follow-along" features that track
// which files the agent is working with in real-time.
//
// See protocol docs: [Following the Agent]
//
// [Following the Agent]: https://agentclientprotocol.com/protocol/tool-calls#following-the-agent
type ToolCallLocation struct {
	// The absolute file path being accessed or modified.
	Path string `json:"path"`
	// Optional line number within the file.
	Line *uint32 `json:"line,omitzero"`
	Meta Meta    `json:"_meta,omitzero"`
}

// PermissionOption is an option presented to the user when requesting permission.
type PermissionOption struct {
	// Unique identifier for this permission option.
	OptionID PermissionOptionID `json:"optionId"`
	// Human-readable label to display to the user.
	Name string `json:"name"`
	// Hint about the nature of this permission option.
	Kind PermissionOptionKind `json:"kind"`
	Meta Meta                 `json:"_meta,omitzero"`
}

// CreateTerminalRequest is a request to create a new terminal and execute a command.
type CreateTerminalRequest struct {
	// The session ID for this request.
	SessionID SessionID `json:"sessionId"`
	// The command to execute.
	Command string `json:"command"`
	// Array of command arguments.
	Args []string `json:"args,omitzero"`
	// Environment variables for the command.
	Env []EnvVariable `json:"env,omitzero"`
	// Working directory for the command. Must be an absolute path.
	Cwd *string `json:"cwd,omitzero"`
	// Maximum number of output bytes to retain.
	//
	// When the limit is exceeded, the Client truncates from the beginning of the output
	// to stay within the limit.
	//
	// The Client MUST ensure truncation happens at a character boundary to maintain valid
	// string output, even if this means the retained output is slightly less than the
	// specified limit.
	OutputByteLimit *uint64 `json:"outputByteLimit,omitzero"`
	Meta            Meta    `json:"_meta,omitzero"`
}

// EnvVariable is an environment variable to set when launching an MCP server.
type EnvVariable struct {
	// The name of the environment variable.
	Name string `json:"name"`
	// The value to set for the environment variable.
	Value string `json:"value"`
	Meta  Meta   `json:"_meta,omitzero"`
}

// TerminalOutputRequest is a request to get the current output and status of a terminal.
type TerminalOutputRequest struct {
	// The session ID for this request.
	SessionID SessionID `json:"sessionId"`
	// The ID of the terminal to get output from.
	TerminalID TerminalID `json:"terminalId"`
	Meta       Meta       `json:"_meta,omitzero"`
}

// ReleaseTerminalRequest is a request to release a terminal and free its resources.
type ReleaseTerminalRequest struct {
	// The session ID for this request.
	SessionID SessionID `json:"sessionId"`
	// The ID of the terminal to release.
	TerminalID TerminalID `json:"terminalId"`
	Meta       Meta       `json:"_meta,omitzero"`
}

// WaitForTerminalExitRequest is a request to wait for a terminal command to exit.
type WaitForTerminalExitRequest struct {
	// The session ID for this request.
	SessionID SessionID `json:"sessionId"`
	// The ID of the terminal to wait for.
	TerminalID TerminalID `json:"terminalId"`
	Meta       Meta       `json:"_meta,omitzero"`
}

// KillTerminalRequest is a request to kill a terminal without releasing it.
type KillTerminalRequest struct {
	// The session ID for this request.
	SessionID SessionID `json:"sessionId"`
	// The ID of the terminal to kill.
	TerminalID TerminalID `json:"terminalId"`
	Meta       Meta       `json:"_meta,omitzero"`
}

// Session-scoped elicitation, optionally tied to a specific tool call.
//
// When `tool_call_id` is set, the elicitation is tied to a specific tool call.
// This is useful when an agent receives an elicitation from an MCP server
// during a tool call and needs to redirect it to the user.
type ElicitationSessionScope struct {
	// The session this elicitation is tied to.
	SessionID SessionID `json:"sessionId"`
	// Optional tool call within the session.
	//
	// Optional. Omitted and `null` are equivalent and mean the elicitation is scoped to the
	// session without a specific tool call.
	ToolCallID *ToolCallID `json:"toolCallId,omitzero"`
}

// Request-scoped elicitation, tied to a specific JSON-RPC request outside of a session
// (e.g., during auth/configuration phases before any session is started).
type ElicitationRequestScope struct {
	// The request this elicitation is tied to.
	RequestID RequestID `json:"requestId"`
}

// Type-safe elicitation schema for requesting structured user input.
//
// This represents a JSON Schema object with primitive-typed properties,
// as required by the elicitation specification.
type ElicitationSchema struct {
	// Type discriminator. Always `"object"`.
	Type *ElicitationSchemaType `json:"type,omitzero"`
	// Optional title for the schema.
	//
	// Optional. Omitted and `null` are equivalent and mean no title is provided.
	Title *string `json:"title,omitzero"`
	// Property definitions (must be primitive types).
	Properties map[string]ElicitationPropertySchema `json:"properties,omitzero"`
	// List of required property names.
	//
	// Optional. Omitted and `null` are equivalent and mean no property names are required.
	Required []string `json:"required,omitzero"`
	// Optional description of what this schema represents.
	//
	// Optional. Omitted and `null` are equivalent and mean no schema description is provided.
	Description *string `json:"description,omitzero"`
	// Optional. Omitted and `null` are equivalent and mean no metadata.
	Meta Meta `json:"_meta,omitzero"`
}

// EnumOption is a titled enum option with a const value, human-readable title, and optional description.
type EnumOption struct {
	// The constant value for this option.
	Const string `json:"const"`
	// Human-readable title for this option.
	Title string `json:"title"`
	// Human-readable description.
	//
	// Optional. Omitted and `null` are equivalent and mean no description is provided.
	Description *string `json:"description,omitzero"`
	// Optional. Omitted and `null` are equivalent and mean no metadata.
	Meta Meta `json:"_meta,omitzero"`
}

// Items definition for titled multi-select enum properties.
type TitledMultiSelectItems struct {
	// Titled enum options.
	AnyOf []EnumOption `json:"anyOf"`
	// Optional. Omitted and `null` are equivalent and mean no metadata.
	Meta Meta `json:"_meta,omitzero"`
}

// Request parameters for `mcp/message`.
//
// Experimental: not part of the spec yet; it may change or be removed.
type MessageMCPRequest struct {
	// The declared ACP MCP server receiving this request.
	ServerID MCPServerACPID `json:"serverId"`
	// The caller-generated identifier for the inner MCP request.
	RequestID MCPRequestID `json:"requestId"`
	// The inner MCP method name.
	Method string `json:"method"`
	// Optional inner MCP params.
	//
	// If omitted or set to `null`, the inner MCP message has no params.
	Params map[string]jsontext.Value `json:"params,omitzero"`
	Meta   Meta                      `json:"_meta,omitzero"`
}

// Allows for sending an arbitrary request that is not part of the ACP spec.
// Extension methods provide a way to add custom functionality while maintaining
// protocol compatibility.
//
// See protocol docs: [Extensibility]
//
// [Extensibility]: https://agentclientprotocol.com/protocol/extensibility
type ExtRequest = jsontext.Value

// InitializeResponse is a response to the `initialize` method.
//
// Contains the negotiated protocol version and agent capabilities.
//
// See protocol docs: [Initialization]
//
// [Initialization]: https://agentclientprotocol.com/protocol/initialization
type InitializeResponse struct {
	// The protocol version the client specified if supported by the agent,
	// or the latest protocol version supported by the agent.
	//
	// The client should disconnect, if it doesn't support this version.
	ProtocolVersion ProtocolVersion `json:"protocolVersion"`
	// Capabilities supported by the agent.
	AgentCapabilities *AgentCapabilities `json:"agentCapabilities,omitzero"`
	// Authentication methods supported by the agent.
	AuthMethods []AuthMethod `json:"authMethods,omitzero"`
	// Information about the Agent name and version sent to the Client.
	//
	// Note: in future versions of the protocol, this will be required.
	AgentInfo *Implementation `json:"agentInfo,omitzero"`
	Meta      Meta            `json:"_meta,omitzero"`
}

// Capabilities supported by the agent.
//
// Advertised during initialization to inform the client about
// available features and content types.
//
// See protocol docs: [Agent Capabilities]
//
// [Agent Capabilities]: https://agentclientprotocol.com/protocol/initialization#agent-capabilities
type AgentCapabilities struct {
	// Whether the agent supports `session/load`.
	LoadSession *bool `json:"loadSession,omitzero"`
	// Prompt capabilities supported by the agent.
	PromptCapabilities *PromptCapabilities `json:"promptCapabilities,omitzero"`
	// MCP capabilities supported by the agent.
	MCPCapabilities *MCPCapabilities `json:"mcpCapabilities,omitzero"`
	// Session lifecycle and prompt capabilities advertised by the agent.
	SessionCapabilities *SessionCapabilities `json:"sessionCapabilities,omitzero"`
	// Authentication-related capabilities supported by the agent.
	Auth *AgentAuthCapabilities `json:"auth,omitzero"`
	// Provider configuration capabilities supported by the agent.
	//
	// Optional. Omitted or `null` both mean the agent does not advertise support.
	// Supplying `{}` means the agent supports provider configuration methods.
	//
	// Experimental: not part of the spec yet; it may change or be removed.
	Providers *ProvidersCapabilities `json:"providers,omitzero"`
	// NES (Next Edit Suggestions) capabilities supported by the agent.
	//
	// Optional. Omitted or `null` both mean the agent does not advertise support
	// for NES methods.
	//
	// Experimental: not part of the spec yet; it may change or be removed.
	Nes *NesCapabilities `json:"nes,omitzero"`
	// The position encoding selected by the agent from the client's supported encodings.
	//
	// Experimental: not part of the spec yet; it may change or be removed.
	PositionEncoding *PositionEncodingKind `json:"positionEncoding,omitzero"`
	Meta             Meta                  `json:"_meta,omitzero"`
}

// Prompt capabilities supported by the agent in `session/prompt` requests.
//
// Baseline agent functionality requires support for [ContentBlockText]
// and [ContentBlockResourceLink] in prompt requests.
//
// Other variants must be explicitly opted in to.
// Capabilities for different types of content in prompt requests.
//
// Indicates which content types beyond the baseline (text and resource links)
// the agent can process.
//
// See protocol docs: [Prompt Capabilities]
//
// [Prompt Capabilities]: https://agentclientprotocol.com/protocol/initialization#prompt-capabilities
type PromptCapabilities struct {
	// Agent supports [ContentBlockImage].
	Image *bool `json:"image,omitzero"`
	// Agent supports [ContentBlockAudio].
	Audio *bool `json:"audio,omitzero"`
	// Agent supports embedded context in `session/prompt` requests.
	//
	// When enabled, the Client is allowed to include [ContentBlockResource]
	// in prompt requests for pieces of context that are referenced in the message.
	EmbeddedContext *bool `json:"embeddedContext,omitzero"`
	Meta            Meta  `json:"_meta,omitzero"`
}

// MCP capabilities supported by the agent
type MCPCapabilities struct {
	// Agent supports [MCPServerHTTP].
	HTTP *bool `json:"http,omitzero"`
	// Agent supports [MCPServerSSE].
	SSE *bool `json:"sse,omitzero"`
	// Agent supports [MCPServerACP].
	//
	// Experimental: not part of the spec yet; it may change or be removed.
	ACP  *bool `json:"acp,omitzero"`
	Meta Meta  `json:"_meta,omitzero"`
}

// Session capabilities supported by the agent.
//
// As a baseline, all Agents **MUST** support `session/new`, `session/prompt`, `session/cancel`, and `session/update`.
//
// Optionally, they **MAY** support other session methods and notifications by specifying additional capabilities.
//
// Note: `session/load` is still handled by the top-level `load_session` capability. This will be unified in future versions of the protocol.
//
// See protocol docs: [Session Capabilities]
//
// [Session Capabilities]: https://agentclientprotocol.com/protocol/initialization#session-capabilities
type SessionCapabilities struct {
	// Whether the agent supports `session/list`.
	//
	// Optional. Omitted or `null` both mean the agent does not advertise support.
	// Supplying `{}` means the agent supports listing sessions.
	List *SessionListCapabilities `json:"list,omitzero"`
	// Whether the agent supports `session/delete`.
	//
	// Optional. Omitted or `null` both mean the agent does not advertise support.
	// Supplying `{}` means the agent supports deleting sessions from `session/list`.
	Delete *SessionDeleteCapabilities `json:"delete,omitzero"`
	// Whether the agent supports `additionalDirectories` on supported session lifecycle requests.
	//
	// Optional. Omitted or `null` both mean the agent does not advertise support.
	// Supplying `{}` means the agent supports `additionalDirectories` on
	// supported session lifecycle requests.
	//
	// Agents that also support `session/list` may return
	// `SessionInfo.additionalDirectories` to report the complete ordered
	// additional-root list associated with a listed session.
	AdditionalDirectories *SessionAdditionalDirectoriesCapabilities `json:"additionalDirectories,omitzero"`
	// Whether the agent supports `session/fork`.
	//
	// Optional. Omitted or `null` both mean the agent does not advertise support.
	// Supplying `{}` means the agent supports forking sessions.
	//
	// Experimental: not part of the spec yet; it may change or be removed.
	Fork *SessionForkCapabilities `json:"fork,omitzero"`
	// Whether the agent supports `session/resume`.
	//
	// Optional. Omitted or `null` both mean the agent does not advertise support.
	// Supplying `{}` means the agent supports resuming sessions.
	Resume *SessionResumeCapabilities `json:"resume,omitzero"`
	// Whether the agent supports `session/close`.
	//
	// Optional. Omitted or `null` both mean the agent does not advertise support.
	// Supplying `{}` means the agent supports closing sessions.
	Close *SessionCloseCapabilities `json:"close,omitzero"`
	Meta  Meta                      `json:"_meta,omitzero"`
}

// Capabilities for the `session/list` method.
//
// Supplying `{}` means the agent supports listing sessions.
type SessionListCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Capabilities for the `session/delete` method.
//
// Supplying `{}` means the agent supports deleting sessions from `session/list`.
type SessionDeleteCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Capabilities for additional session directories support.
//
// Supplying `{}` means the agent supports the `additionalDirectories` field on
// supported session lifecycle requests. Agents that also support
// `session/list` may return `SessionInfo.additionalDirectories` to report the
// complete ordered additional-root list associated with a listed session.
type SessionAdditionalDirectoriesCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Capabilities for the `session/fork` method.
//
// Supplying `{}` means the agent supports forking sessions.
//
// Experimental: not part of the spec yet; it may change or be removed.
type SessionForkCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Capabilities for the `session/resume` method.
//
// Supplying `{}` means the agent supports resuming sessions.
type SessionResumeCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Capabilities for the `session/close` method.
//
// Supplying `{}` means the agent supports closing sessions.
type SessionCloseCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Authentication-related capabilities supported by the agent.
type AgentAuthCapabilities struct {
	// Whether the agent supports the logout method.
	//
	// Optional. Omitted or `null` both mean the agent does not advertise support.
	// Supplying `{}` means the agent supports the logout method.
	Logout *LogoutCapabilities `json:"logout,omitzero"`
	Meta   Meta                `json:"_meta,omitzero"`
}

// Logout capabilities supported by the agent.
//
// Supplying `{}` means the agent supports the logout method.
type LogoutCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Provider configuration capabilities supported by the agent.
//
// Supplying `{}` means the agent supports provider configuration methods.
//
// Experimental: not part of the spec yet; it may change or be removed.
type ProvidersCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// NES capabilities advertised by the agent during initialization.
type NesCapabilities struct {
	// Events the agent wants to receive.
	Events *NesEventCapabilities `json:"events,omitzero"`
	// Context the agent wants attached to each suggestion request.
	Context *NesContextCapabilities `json:"context,omitzero"`
	Meta    Meta                    `json:"_meta,omitzero"`
}

// Event capabilities the agent can consume.
type NesEventCapabilities struct {
	// Document event capabilities.
	Document *NesDocumentEventCapabilities `json:"document,omitzero"`
	Meta     Meta                          `json:"_meta,omitzero"`
}

// Document event capabilities the agent wants to receive.
type NesDocumentEventCapabilities struct {
	// Whether the agent wants `document/didOpen` events.
	DidOpen *NesDocumentDidOpenCapabilities `json:"didOpen,omitzero"`
	// Whether the agent wants `document/didChange` events, and the sync kind.
	DidChange *NesDocumentDidChangeCapabilities `json:"didChange,omitzero"`
	// Whether the agent wants `document/didClose` events.
	DidClose *NesDocumentDidCloseCapabilities `json:"didClose,omitzero"`
	// Whether the agent wants `document/didSave` events.
	DidSave *NesDocumentDidSaveCapabilities `json:"didSave,omitzero"`
	// Whether the agent wants `document/didFocus` events.
	DidFocus *NesDocumentDidFocusCapabilities `json:"didFocus,omitzero"`
	Meta     Meta                             `json:"_meta,omitzero"`
}

// NesDocumentDidOpenCapabilities is a marker for `document/didOpen` capability support.
type NesDocumentDidOpenCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Capabilities for `document/didChange` events.
type NesDocumentDidChangeCapabilities struct {
	// The sync kind the agent wants: `"full"` or `"incremental"`.
	SyncKind TextDocumentSyncKind `json:"syncKind"`
	Meta     Meta                 `json:"_meta,omitzero"`
}

// NesDocumentDidCloseCapabilities is a marker for `document/didClose` capability support.
type NesDocumentDidCloseCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// NesDocumentDidSaveCapabilities is a marker for `document/didSave` capability support.
type NesDocumentDidSaveCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// NesDocumentDidFocusCapabilities is a marker for `document/didFocus` capability support.
type NesDocumentDidFocusCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Context capabilities the agent wants attached to each suggestion request.
type NesContextCapabilities struct {
	// Whether the agent wants recent files context.
	RecentFiles *NesRecentFilesCapabilities `json:"recentFiles,omitzero"`
	// Whether the agent wants related snippets context.
	RelatedSnippets *NesRelatedSnippetsCapabilities `json:"relatedSnippets,omitzero"`
	// Whether the agent wants edit history context.
	EditHistory *NesEditHistoryCapabilities `json:"editHistory,omitzero"`
	// Whether the agent wants user actions context.
	UserActions *NesUserActionsCapabilities `json:"userActions,omitzero"`
	// Whether the agent wants open files context.
	OpenFiles *NesOpenFilesCapabilities `json:"openFiles,omitzero"`
	// Whether the agent wants diagnostics context.
	Diagnostics *NesDiagnosticsCapabilities `json:"diagnostics,omitzero"`
	Meta        Meta                        `json:"_meta,omitzero"`
}

// Capabilities for recent files context.
type NesRecentFilesCapabilities struct {
	// Maximum number of recent files the agent can use.
	MaxCount *uint32 `json:"maxCount,omitzero"`
	Meta     Meta    `json:"_meta,omitzero"`
}

// Capabilities for related snippets context.
type NesRelatedSnippetsCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Capabilities for edit history context.
type NesEditHistoryCapabilities struct {
	// Maximum number of edit history entries the agent can use.
	MaxCount *uint32 `json:"maxCount,omitzero"`
	Meta     Meta    `json:"_meta,omitzero"`
}

// Capabilities for user actions context.
type NesUserActionsCapabilities struct {
	// Maximum number of user actions the agent can use.
	MaxCount *uint32 `json:"maxCount,omitzero"`
	Meta     Meta    `json:"_meta,omitzero"`
}

// Capabilities for open files context.
type NesOpenFilesCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Capabilities for diagnostics context.
type NesDiagnosticsCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Agent handles authentication itself through `authenticate`.
//
// This is the default authentication method type.
type AuthMethodAgent struct {
	// Unique identifier for this authentication method.
	ID AuthMethodID `json:"id"`
	// Human-readable name of the authentication method.
	Name string `json:"name"`
	// Optional description providing more details about this authentication method.
	Description *string `json:"description,omitzero"`
	Meta        Meta    `json:"_meta,omitzero"`
}

// Metadata about the implementation of the client or agent.
// Describes the name and version of an ACP implementation, with an optional
// title for UI representation.
type Implementation struct {
	// Intended for programmatic or logical use, but can be used as a display
	// name fallback if title isn’t present.
	Name string `json:"name"`
	// Intended for UI and end-user contexts — optimized to be human-readable
	// and easily understood.
	//
	// If not provided, the name should be used for display.
	Title *string `json:"title,omitzero"`
	// Version of the implementation. Can be displayed to the user or used
	// for debugging or metrics purposes. (e.g. "1.0.0").
	Version string `json:"version"`
	Meta    Meta   `json:"_meta,omitzero"`
}

// AuthenticateResponse is a response to the `authenticate` method.
type AuthenticateResponse struct {
	Meta Meta `json:"_meta,omitzero"`
}

// ListProvidersResponse is a response to `providers/list`.
//
// Experimental: not part of the spec yet; it may change or be removed.
type ListProvidersResponse struct {
	// Configurable providers with current routing info suitable for UI display.
	Providers []ProviderInfo `json:"providers"`
	Meta      Meta           `json:"_meta,omitzero"`
}

// Information about a configurable LLM provider.
//
// Experimental: not part of the spec yet; it may change or be removed.
type ProviderInfo struct {
	// Provider identifier, for example "main" or "openai".
	ProviderID ProviderID `json:"providerId"`
	// Supported protocol types for this provider.
	Supported []LLMProtocol `json:"supported"`
	// Whether this provider is mandatory and cannot be disabled via `providers/disable`.
	// If true, clients must not call `providers/disable` for this provider ID.
	Required bool `json:"required"`
	// Current effective non-secret routing config.
	// Null or omitted means provider is disabled.
	Current *ProviderCurrentConfig `json:"current,omitzero"`
	Meta    Meta                   `json:"_meta,omitzero"`
}

// Current effective non-secret routing configuration for a provider.
//
// Experimental: not part of the spec yet; it may change or be removed.
type ProviderCurrentConfig struct {
	// Protocol currently used by this provider.
	APIType LLMProtocol `json:"apiType"`
	// Base URL currently used by this provider.
	BaseURL string `json:"baseUrl"`
	Meta    Meta   `json:"_meta,omitzero"`
}

// SetProviderResponse is a response to `providers/set`.
//
// Experimental: not part of the spec yet; it may change or be removed.
type SetProviderResponse struct {
	Meta Meta `json:"_meta,omitzero"`
}

// DisableProviderResponse is a response to `providers/disable`.
//
// Experimental: not part of the spec yet; it may change or be removed.
type DisableProviderResponse struct {
	Meta Meta `json:"_meta,omitzero"`
}

// LogoutResponse is a response to the `logout` method.
type LogoutResponse struct {
	Meta Meta `json:"_meta,omitzero"`
}

// NewSessionResponse is a response from creating a new session.
//
// See protocol docs: [Creating a Session]
//
// [Creating a Session]: https://agentclientprotocol.com/protocol/session-setup#creating-a-session
type NewSessionResponse struct {
	// Unique identifier for the created session.
	//
	// Used in all subsequent requests for this conversation.
	SessionID SessionID `json:"sessionId"`
	// Initial mode state if supported by the Agent
	//
	// See protocol docs: [Session Modes](https://agentclientprotocol.com/protocol/session-modes)
	Modes *SessionModeState `json:"modes,omitzero"`
	// Initial session configuration options if supported by the Agent.
	ConfigOptions []SessionConfigOption `json:"configOptions,omitzero"`
	Meta          Meta                  `json:"_meta,omitzero"`
}

// SessionModeState is the set of modes and the one currently active.
type SessionModeState struct {
	// The current mode the Agent is in.
	CurrentModeID SessionModeID `json:"currentModeId"`
	// The set of modes that the Agent can operate in
	AvailableModes []SessionMode `json:"availableModes"`
	Meta           Meta          `json:"_meta,omitzero"`
}

// A mode the agent can operate in.
//
// See protocol docs: [Session Modes]
//
// [Session Modes]: https://agentclientprotocol.com/protocol/session-modes
type SessionMode struct {
	// Stable identifier used to refer to this protocol object in later messages.
	ID SessionModeID `json:"id"`
	// Human-readable name shown for this protocol object.
	Name string `json:"name"`
	// Optional human-readable details shown with this protocol object.
	Description *string `json:"description,omitzero"`
	Meta        Meta    `json:"_meta,omitzero"`
}

// SessionConfigSelectOption is a possible value for a session configuration option.
type SessionConfigSelectOption struct {
	// Unique identifier for this option value.
	Value SessionConfigValueID `json:"value"`
	// Human-readable label for this option value.
	Name string `json:"name"`
	// Optional description for this option value.
	Description *string `json:"description,omitzero"`
	Meta        Meta    `json:"_meta,omitzero"`
}

// SessionConfigSelectGroup is a group of possible values for a session configuration option.
type SessionConfigSelectGroup struct {
	// Unique identifier for this group.
	Group SessionConfigGroupID `json:"group"`
	// Human-readable label for this group.
	Name string `json:"name"`
	// The set of option values in this group.
	Options []SessionConfigSelectOption `json:"options"`
	Meta    Meta                        `json:"_meta,omitzero"`
}

// SessionConfigSelect is a single-value selector (dropdown) session configuration option payload.
type SessionConfigSelect struct {
	// The currently selected value.
	CurrentValue SessionConfigValueID `json:"currentValue"`
	// The set of selectable options.
	Options SessionConfigSelectOptions `json:"options"`
}

// SessionConfigBoolean is a boolean on/off toggle session configuration option payload.
type SessionConfigBoolean struct {
	// The current value of the boolean option.
	CurrentValue bool `json:"currentValue"`
}

// LoadSessionResponse is a response from loading an existing session.
type LoadSessionResponse struct {
	// Initial mode state if supported by the Agent
	//
	// See protocol docs: [Session Modes](https://agentclientprotocol.com/protocol/session-modes)
	Modes *SessionModeState `json:"modes,omitzero"`
	// Initial session configuration options if supported by the Agent.
	ConfigOptions []SessionConfigOption `json:"configOptions,omitzero"`
	Meta          Meta                  `json:"_meta,omitzero"`
}

// ListSessionsResponse is a response from listing sessions.
type ListSessionsResponse struct {
	// Array of session information objects
	Sessions []SessionInfo `json:"sessions"`
	// Opaque cursor token. If present, pass this in the next request's cursor parameter
	// to fetch the next page. If absent, there are no more results.
	NextCursor *string `json:"nextCursor,omitzero"`
	Meta       Meta    `json:"_meta,omitzero"`
}

// Information about a session returned by session/list
type SessionInfo struct {
	// Unique identifier for the session
	SessionID SessionID `json:"sessionId"`
	// The working directory for this session. Must be an absolute path.
	Cwd string `json:"cwd"`
	// Additional workspace roots reported for this session. Each path must be absolute.
	//
	// When present, this is the complete ordered additional-root list reported
	// by the Agent. Omitted and empty values are equivalent: the response
	// reports no additional roots.
	AdditionalDirectories []string `json:"additionalDirectories,omitzero"`
	// Human-readable title for the session
	Title *string `json:"title,omitzero"`
	// ISO 8601 timestamp of last activity
	UpdatedAt *string `json:"updatedAt,omitzero"`
	Meta      Meta    `json:"_meta,omitzero"`
}

// DeleteSessionResponse is a response from deleting a session.
type DeleteSessionResponse struct {
	Meta Meta `json:"_meta,omitzero"`
}

// ForkSessionResponse is a response from forking an existing session.
//
// Experimental: not part of the spec yet; it may change or be removed.
type ForkSessionResponse struct {
	// Unique identifier for the newly created forked session.
	SessionID SessionID `json:"sessionId"`
	// Initial mode state if supported by the Agent
	//
	// See protocol docs: [Session Modes](https://agentclientprotocol.com/protocol/session-modes)
	Modes *SessionModeState `json:"modes,omitzero"`
	// Initial session configuration options if supported by the Agent.
	ConfigOptions []SessionConfigOption `json:"configOptions,omitzero"`
	Meta          Meta                  `json:"_meta,omitzero"`
}

// ResumeSessionResponse is a response from resuming an existing session.
type ResumeSessionResponse struct {
	// Initial mode state if supported by the Agent
	//
	// See protocol docs: [Session Modes](https://agentclientprotocol.com/protocol/session-modes)
	Modes *SessionModeState `json:"modes,omitzero"`
	// Initial session configuration options if supported by the Agent.
	ConfigOptions []SessionConfigOption `json:"configOptions,omitzero"`
	Meta          Meta                  `json:"_meta,omitzero"`
}

// CloseSessionResponse is a response from closing a session.
type CloseSessionResponse struct {
	Meta Meta `json:"_meta,omitzero"`
}

// SetSessionModeResponse is a response to `session/set_mode` method.
type SetSessionModeResponse struct {
	Meta Meta `json:"_meta,omitzero"`
}

// SetSessionConfigOptionResponse is a response to `session/set_config_option` method.
type SetSessionConfigOptionResponse struct {
	// The full set of configuration options and their current values.
	ConfigOptions []SessionConfigOption `json:"configOptions"`
	Meta          Meta                  `json:"_meta,omitzero"`
}

// PromptResponse is a response from processing a user prompt.
//
// See protocol docs: [Check for Completion]
//
// [Check for Completion]: https://agentclientprotocol.com/protocol/prompt-turn#4-check-for-completion
type PromptResponse struct {
	// Indicates why the agent stopped processing the turn.
	StopReason StopReason `json:"stopReason"`
	// Token usage for this turn (optional).
	//
	// Experimental: not part of the spec yet; it may change or be removed.
	Usage *Usage `json:"usage,omitzero"`
	Meta  Meta   `json:"_meta,omitzero"`
}

// Token usage information for a prompt turn.
//
// Experimental: not part of the spec yet; it may change or be removed.
type Usage struct {
	// Sum of all token types across session.
	TotalTokens uint64 `json:"totalTokens"`
	// Total input tokens across all turns.
	InputTokens uint64 `json:"inputTokens"`
	// Total output tokens across all turns.
	OutputTokens uint64 `json:"outputTokens"`
	// Total thought/reasoning tokens
	ThoughtTokens *uint64 `json:"thoughtTokens,omitzero"`
	// Total cache read tokens.
	CachedReadTokens *uint64 `json:"cachedReadTokens,omitzero"`
	// Total cache write tokens.
	CachedWriteTokens *uint64 `json:"cachedWriteTokens,omitzero"`
	Meta              Meta    `json:"_meta,omitzero"`
}

// StartNesResponse is a response to `nes/start`.
type StartNesResponse struct {
	// The session ID for the newly started NES session.
	SessionID SessionID `json:"sessionId"`
	Meta      Meta      `json:"_meta,omitzero"`
}

// SuggestNesResponse is a response to `nes/suggest`.
type SuggestNesResponse struct {
	// The list of suggestions.
	Suggestions []NesSuggestion `json:"suggestions"`
	Meta        Meta            `json:"_meta,omitzero"`
}

// NesTextEdit is a text edit within a suggestion.
type NesTextEdit struct {
	// The range to replace.
	Range Range `json:"range"`
	// The replacement text.
	NewText string `json:"newText"`
	Meta    Meta   `json:"_meta,omitzero"`
}

// Range is a range in a text document, expressed as start and end positions.
type Range struct {
	// The start position (inclusive).
	Start Position `json:"start"`
	// The end position (exclusive).
	End  Position `json:"end"`
	Meta Meta     `json:"_meta,omitzero"`
}

// Position is a zero-based position in a text document.
//
// The meaning of `character` depends on the negotiated position encoding.
type Position struct {
	// Zero-based line number.
	Line uint32 `json:"line"`
	// Zero-based character offset (encoding-dependent).
	Character uint32 `json:"character"`
	Meta      Meta   `json:"_meta,omitzero"`
}

// CloseNesResponse is a response from closing an NES session.
type CloseNesResponse struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Allows for sending an arbitrary response to an [ExtRequest] that is not part of the ACP spec.
// Extension methods provide a way to add custom functionality while maintaining
// protocol compatibility.
//
// See protocol docs: [Extensibility]
//
// [Extensibility]: https://agentclientprotocol.com/protocol/extensibility
type ExtResponse = jsontext.Value

// Notification containing a session update from the agent.
//
// Used to stream real-time progress and results during prompt processing.
//
// See protocol docs: [Agent Reports Output]
//
// [Agent Reports Output]: https://agentclientprotocol.com/protocol/prompt-turn#3-agent-reports-output
type SessionNotification struct {
	// The ID of the session this update pertains to.
	SessionID SessionID `json:"sessionId"`
	// The actual update content.
	Update SessionUpdate `json:"update"`
	Meta   Meta          `json:"_meta,omitzero"`
}

// ContentChunk is a streamed item of content
type ContentChunk struct {
	// A single item of content
	Content ContentBlock `json:"content"`
	// A unique identifier for the message this chunk belongs to.
	//
	// All chunks belonging to the same message share the same `messageId`.
	// A change in `messageId` indicates a new message has started.
	MessageID *MessageID `json:"messageId,omitzero"`
	Meta      Meta       `json:"_meta,omitzero"`
}

// PlanEntry is a single entry in the execution plan.
//
// Represents a task or goal that the assistant intends to accomplish
// as part of fulfilling the user's request.
// See protocol docs: [Plan Entries]
//
// [Plan Entries]: https://agentclientprotocol.com/protocol/agent-plan#plan-entries
type PlanEntry struct {
	// Human-readable description of what this task aims to accomplish.
	Content string `json:"content"`
	// The relative importance of this task.
	// Used to indicate which tasks are most critical to the overall goal.
	Priority PlanEntryPriority `json:"priority"`
	// Current execution status of this task.
	Status PlanEntryStatus `json:"status"`
	Meta   Meta            `json:"_meta,omitzero"`
}

// Information about a command.
type AvailableCommand struct {
	// Command name (e.g., `create_plan`, `research_codebase`).
	Name string `json:"name"`
	// Human-readable description of what the command does.
	Description string `json:"description"`
	// Input for the command if required
	Input *AvailableCommandInput `json:"input,omitzero"`
	Meta  Meta                   `json:"_meta,omitzero"`
}

// unstructured
//
// All text that was typed after the command name is provided as input.
type AvailableCommandInput = UnstructuredCommandInput

// All text that was typed after the command name is provided as input.
type UnstructuredCommandInput struct {
	// A hint to display when the input hasn't been provided yet
	Hint string `json:"hint"`
	Meta Meta   `json:"_meta,omitzero"`
}

// Cost information for a session.
type Cost struct {
	// Total cumulative cost for session.
	Amount float64 `json:"amount"`
	// ISO 4217 currency code (e.g., "USD", "EUR").
	Currency string `json:"currency"`
	Meta     Meta   `json:"_meta,omitzero"`
}

// Client-initiated session mutations permitted for a specific subagent session.
//
// A mutation requires an explicit per-child capability; support for the method
// on ordinary sessions does not grant support on a child.
//
// Experimental: not part of the spec yet; it may change or be removed.
type SubagentSessionCapabilities struct {
	// Permits the client to cancel this child's current work without ending
	// the session. Omitted or `null` means unsupported; an object (including
	// `{}`) means supported.
	Cancel *SessionCancelCapabilities `json:"cancel,omitzero"`
	Meta   Meta                       `json:"_meta,omitzero"`
}

// Capability to cancel work in a subagent session without ending that session.
//
// Supplying `{}` advertises support; an omitted or `null` `cancel` does not.
//
// Experimental: not part of the spec yet; it may change or be removed.
type SessionCancelCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Notification sent by the agent when a URL-based elicitation is complete.
type CompleteElicitationNotification struct {
	// The ID of the elicitation that completed.
	ElicitationID ElicitationID `json:"elicitationId"`
	// Optional. Omitted and `null` are equivalent and mean no metadata.
	Meta Meta `json:"_meta,omitzero"`
}

// Allows the Agent to send an arbitrary notification that is not part of the ACP spec.
// Extension notifications provide a way to send one-way messages for custom functionality
// while maintaining protocol compatibility.
//
// See protocol docs: [Extensibility]
//
// [Extensibility]: https://agentclientprotocol.com/protocol/extensibility
type ExtNotification = jsontext.Value

// Request parameters for the initialize method.
//
// Sent by the client to establish connection and negotiate capabilities.
//
// See protocol docs: [Initialization]
//
// [Initialization]: https://agentclientprotocol.com/protocol/initialization
type InitializeRequest struct {
	// The latest protocol version supported by the client.
	ProtocolVersion ProtocolVersion `json:"protocolVersion"`
	// Capabilities supported by the client.
	ClientCapabilities *ClientCapabilities `json:"clientCapabilities,omitzero"`
	// Information about the Client name and version sent to the Agent.
	//
	// Note: in future versions of the protocol, this will be required.
	ClientInfo *Implementation `json:"clientInfo,omitzero"`
	Meta       Meta            `json:"_meta,omitzero"`
}

// Capabilities supported by the client.
//
// Advertised during initialization to inform the agent about
// available features and methods.
//
// See protocol docs: [Client Capabilities]
//
// [Client Capabilities]: https://agentclientprotocol.com/protocol/initialization#client-capabilities
type ClientCapabilities struct {
	// File system capabilities supported by the client.
	// Determines which file operations the agent can request.
	FS *FileSystemCapabilities `json:"fs,omitzero"`
	// Whether the Client support all `terminal*` methods.
	Terminal *bool `json:"terminal,omitzero"`
	// Session-related capabilities supported by the client.
	//
	// Optional. Omitted or `null` both mean the client does not advertise any
	// session-related extensions.
	Session *ClientSessionCapabilities `json:"session,omitzero"`
	// Whether the client understands exposed subagent sessions.
	//
	// Optional and nullable. Omitted or `null` both mean the client does not
	// advertise support.
	// Supplying `{}` means the client understands child associations, work-state
	// snapshots, session-directed messages, and restricted-session semantics.
	//
	// Experimental: not part of the spec yet; it may change or be removed.
	Subagents *SubagentCapabilities `json:"subagents,omitzero"`
	// Whether the client supports `plan_update` and `plan_removed` session updates.
	//
	// Optional. Omitted or `null` both mean the client does not advertise support.
	// Supplying `{}` means the client can receive both update types.
	//
	// Experimental: not part of the spec yet; it may change or be removed.
	Plan *PlanCapabilities `json:"plan,omitzero"`
	// Authentication capabilities supported by the client.
	// Determines which authentication method types the agent may include
	// in its `InitializeResponse`.
	Auth *AuthCapabilities `json:"auth,omitzero"`
	// Elicitation capabilities supported by the client.
	// Determines which elicitation modes the agent may use.
	//
	// Optional. Omitted or `null` both mean the client does not advertise
	// elicitation support.
	Elicitation *ElicitationCapabilities `json:"elicitation,omitzero"`
	// NES (Next Edit Suggestions) capabilities supported by the client.
	//
	// Optional. Omitted or `null` both mean the client does not advertise any
	// NES suggestion-kind extensions.
	//
	// Experimental: not part of the spec yet; it may change or be removed.
	Nes *ClientNesCapabilities `json:"nes,omitzero"`
	// The position encodings supported by the client, in order of preference.
	//
	// Experimental: not part of the spec yet; it may change or be removed.
	PositionEncodings []PositionEncodingKind `json:"positionEncodings,omitzero"`
	Meta              Meta                   `json:"_meta,omitzero"`
}

// File system capabilities that a client may support.
//
// See protocol docs: [FileSystem]
//
// [FileSystem]: https://agentclientprotocol.com/protocol/initialization#filesystem
type FileSystemCapabilities struct {
	// Whether the Client supports `fs/read_text_file` requests.
	ReadTextFile *bool `json:"readTextFile,omitzero"`
	// Whether the Client supports `fs/write_text_file` requests.
	WriteTextFile *bool `json:"writeTextFile,omitzero"`
	Meta          Meta  `json:"_meta,omitzero"`
}

// Session-related capabilities supported by the client.
type ClientSessionCapabilities struct {
	// Support for ID-addressed context compaction updates. Omitted or `null`
	// means unsupported; `{}` advertises the complete compaction contract.
	//
	// Experimental: not part of the spec yet; it may change or be removed.
	Compaction *CompactionCapabilities `json:"compaction,omitzero"`
	// Config option capabilities supported by the client.
	//
	// Omitted or `null` both mean the client does not advertise support for any
	// config option extensions.
	ConfigOptions *SessionConfigOptionsCapabilities `json:"configOptions,omitzero"`
	// Support for live advisory `notice` session updates.
	//
	// Optional. Omitted or `null` both mean the client does not advertise support.
	// Supplying `{}` means the client can present notices to the user.
	//
	// Experimental: not part of the spec yet; it may change or be removed.
	Notices *NoticeCapabilities `json:"notices,omitzero"`
	Meta    Meta                `json:"_meta,omitzero"`
}

// Client support for ID-addressed context compaction updates.
//
// Experimental: not part of the spec yet; it may change or be removed.
type CompactionCapabilities = map[string]jsontext.Value

// Session configuration option capabilities supported by the client.
type SessionConfigOptionsCapabilities struct {
	// Whether the client supports boolean session configuration options.
	//
	// Optional. Omitted or `null` both mean the client does not advertise support.
	// Supplying `{}` means agents may include `type: "boolean"` entries in
	// `configOptions`, and the client may send `session/set_config_option`
	// requests with `type: "boolean"` and a boolean `value`.
	Boolean *BooleanConfigOptionCapabilities `json:"boolean,omitzero"`
	Meta    Meta                             `json:"_meta,omitzero"`
}

// Capabilities for boolean session configuration options.
//
// Supplying `{}` means the client supports boolean session configuration options.
type BooleanConfigOptionCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Client support for presenting live advisory notices to the user.
//
// Experimental: not part of the spec yet; it may change or be removed.
type NoticeCapabilities = map[string]jsontext.Value

// Capability marker for exposing reusable child sessions as restricted ACP sessions.
//
// Supplying `{}` advertises support for child association and state updates,
// session-directed messages, and restricted-session semantics. The client
// must advertise this capability before the agent sends subagent updates or
// session-directed messages.
//
// Experimental: not part of the spec yet; it may change or be removed.
type SubagentCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Capabilities for receiving `plan_update` and `plan_removed` session updates.
//
// Experimental: not part of the spec yet; it may change or be removed.
type PlanCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Authentication capabilities supported by the client.
//
// Advertised during initialization to inform the agent which authentication
// method types the client can handle. This governs opt-in types that require
// additional client-side support.
type AuthCapabilities struct {
	// Whether the client supports `terminal` authentication methods.
	//
	// The client should set this to `true` only when it can reproduce the
	// configured agent invocation in an interactive terminal. When `true`, the
	// agent may include `terminal` entries in its authentication methods.
	Terminal *bool `json:"terminal,omitzero"`
	Meta     Meta  `json:"_meta,omitzero"`
}

// Elicitation capabilities supported by the client.
type ElicitationCapabilities struct {
	// Whether the client supports form-based elicitation.
	//
	// Optional. Omitted and `null` are equivalent and mean form support is not advertised.
	// Supplying `{}` explicitly advertises form support.
	Form *ElicitationFormCapabilities `json:"form,omitzero"`
	// Whether the client supports URL-based elicitation.
	//
	// Optional. Omitted or `null` both mean the client does not advertise support.
	// Supplying `{}` means the client supports URL-based elicitation.
	URL *ElicitationURLCapabilities `json:"url,omitzero"`
	// Optional. Omitted and `null` are equivalent and mean no metadata.
	Meta Meta `json:"_meta,omitzero"`
}

// Form-based elicitation capabilities.
//
// Supplying `{}` means the client supports form-based elicitation.
type ElicitationFormCapabilities struct {
	// Optional. Omitted and `null` are equivalent and mean no metadata.
	Meta Meta `json:"_meta,omitzero"`
}

// URL-based elicitation capabilities.
//
// Supplying `{}` means the client supports URL-based elicitation.
type ElicitationURLCapabilities struct {
	// Optional. Omitted and `null` are equivalent and mean no metadata.
	Meta Meta `json:"_meta,omitzero"`
}

// NES capabilities advertised by the client during initialization.
type ClientNesCapabilities struct {
	// Whether the client supports the `jump` suggestion kind.
	Jump *NesJumpCapabilities `json:"jump,omitzero"`
	// Whether the client supports the `rename` suggestion kind.
	Rename *NesRenameCapabilities `json:"rename,omitzero"`
	// Whether the client supports the `searchAndReplace` suggestion kind.
	SearchAndReplace *NesSearchAndReplaceCapabilities `json:"searchAndReplace,omitzero"`
	Meta             Meta                             `json:"_meta,omitzero"`
}

// NesJumpCapabilities is a marker for jump suggestion support.
type NesJumpCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// NesRenameCapabilities is a marker for rename suggestion support.
type NesRenameCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// NesSearchAndReplaceCapabilities is a marker for search and replace suggestion support.
type NesSearchAndReplaceCapabilities struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Request parameters for the authenticate method.
//
// Specifies which authentication method to use.
type AuthenticateRequest struct {
	// The ID of the authentication method to use.
	// Must be one of the methods advertised in the initialize response.
	MethodID AuthMethodID `json:"methodId"`
	Meta     Meta         `json:"_meta,omitzero"`
}

// Request parameters for `providers/list`.
//
// Experimental: not part of the spec yet; it may change or be removed.
type ListProvidersRequest struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Request parameters for `providers/set`.
//
// Replaces the full configuration for one provider ID.
//
// Experimental: not part of the spec yet; it may change or be removed.
type SetProviderRequest struct {
	// Provider ID to configure.
	ProviderID ProviderID `json:"providerId"`
	// Protocol type for this provider.
	APIType LLMProtocol `json:"apiType"`
	// Base URL for requests sent through this provider.
	BaseURL string `json:"baseUrl"`
	// Full headers map for this provider.
	// May include authorization, routing, or other integration-specific headers.
	Headers map[string]string `json:"headers,omitzero"`
	Meta    Meta              `json:"_meta,omitzero"`
}

// Request parameters for `providers/disable`.
//
// Experimental: not part of the spec yet; it may change or be removed.
type DisableProviderRequest struct {
	// Provider ID to disable.
	ProviderID ProviderID `json:"providerId"`
	Meta       Meta       `json:"_meta,omitzero"`
}

// Request parameters for the logout method.
//
// Terminates the current authenticated session.
type LogoutRequest struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Request parameters for creating a new session.
//
// See protocol docs: [Creating a Session]
//
// [Creating a Session]: https://agentclientprotocol.com/protocol/session-setup#creating-a-session
type NewSessionRequest struct {
	// The working directory for this session. Must be an absolute path.
	Cwd string `json:"cwd"`
	// Additional workspace roots for this session. Each path must be absolute.
	//
	// These expand the session's filesystem scope without changing `cwd`, which
	// remains the base for relative paths. When omitted or empty, no
	// additional roots are activated for the new session.
	AdditionalDirectories []string `json:"additionalDirectories,omitzero"`
	// List of MCP (Model Context Protocol) servers the agent should connect to.
	MCPServers []MCPServer `json:"mcpServers"`
	Meta       Meta        `json:"_meta,omitzero"`
}

// HTTPHeader is an HTTP header to set when making requests to the MCP server.
type HTTPHeader struct {
	// The name of the HTTP header.
	Name string `json:"name"`
	// The value to set for the HTTP header.
	Value string `json:"value"`
	Meta  Meta   `json:"_meta,omitzero"`
}

// Stdio transport configuration for MCP.
type MCPServerStdio struct {
	// Human-readable name identifying this MCP server.
	Name string `json:"name"`
	// Absolute path to the MCP server executable.
	Command string `json:"command"`
	// Command-line arguments to pass to the MCP server.
	Args []string `json:"args"`
	// Environment variables to set when launching the MCP server.
	Env  []EnvVariable `json:"env"`
	Meta Meta          `json:"_meta,omitzero"`
}

// Request parameters for loading an existing session.
//
// Only available if the Agent supports the `loadSession` capability.
//
// See protocol docs: [Loading Sessions]
//
// [Loading Sessions]: https://agentclientprotocol.com/protocol/session-setup#loading-sessions
type LoadSessionRequest struct {
	// List of MCP servers to connect to for this session.
	MCPServers []MCPServer `json:"mcpServers"`
	// The working directory for this session. Must be an absolute path.
	Cwd string `json:"cwd"`
	// Additional workspace roots to activate for this session. Each path must be absolute.
	//
	// When omitted or empty, no additional roots are activated. When non-empty,
	// this is the complete resulting additional-root list for the loaded
	// session. It may differ from any previously used or reported list as long as
	// the request `cwd` matches the session's `cwd`.
	AdditionalDirectories []string `json:"additionalDirectories,omitzero"`
	// The ID of the session to load.
	SessionID SessionID `json:"sessionId"`
	Meta      Meta      `json:"_meta,omitzero"`
}

// Request parameters for listing existing sessions.
//
// Only available if the Agent supports the `sessionCapabilities.list` capability.
type ListSessionsRequest struct {
	// Filter sessions by working directory. Must be an absolute path.
	Cwd *string `json:"cwd,omitzero"`
	// Opaque cursor token from a previous response's nextCursor field for cursor-based pagination
	Cursor *string `json:"cursor,omitzero"`
	Meta   Meta    `json:"_meta,omitzero"`
}

// Request parameters for deleting an existing session from `session/list`.
//
// Only available if the Agent supports the `sessionCapabilities.delete` capability.
type DeleteSessionRequest struct {
	// The ID of the session to delete.
	SessionID SessionID `json:"sessionId"`
	Meta      Meta      `json:"_meta,omitzero"`
}

// Request parameters for forking an existing session.
//
// Creates a new session based on the context of an existing one, allowing
// operations like generating summaries without affecting the original session's history.
//
// Only available if the Agent supports the `session.fork` capability.
//
// Experimental: not part of the spec yet; it may change or be removed.
type ForkSessionRequest struct {
	// The ID of the session to fork.
	SessionID SessionID `json:"sessionId"`
	// The working directory for this session. Must be an absolute path.
	Cwd string `json:"cwd"`
	// Additional workspace roots to activate for this session. Each path must be absolute.
	//
	// When omitted or empty, no additional roots are activated. When non-empty,
	// this is the complete resulting additional-root list for the forked
	// session.
	AdditionalDirectories []string `json:"additionalDirectories,omitzero"`
	// List of MCP servers to connect to for this session.
	MCPServers []MCPServer `json:"mcpServers,omitzero"`
	Meta       Meta        `json:"_meta,omitzero"`
}

// Request parameters for resuming an existing session.
//
// Resumes an existing session without returning previous messages (unlike `session/load`).
// This is useful for agents that can resume sessions but don't implement full session loading.
//
// Only available if the Agent supports the `sessionCapabilities.resume` capability.
type ResumeSessionRequest struct {
	// The ID of the session to resume.
	SessionID SessionID `json:"sessionId"`
	// The working directory for this session. Must be an absolute path.
	Cwd string `json:"cwd"`
	// Additional workspace roots to activate for this session. Each path must be absolute.
	//
	// When omitted or empty, no additional roots are activated. When non-empty,
	// this is the complete resulting additional-root list for the resumed
	// session. It may differ from any previously used or reported list as long as
	// the request `cwd` matches the session's `cwd`.
	AdditionalDirectories []string `json:"additionalDirectories,omitzero"`
	// List of MCP servers to connect to for this session.
	MCPServers []MCPServer `json:"mcpServers,omitzero"`
	Meta       Meta        `json:"_meta,omitzero"`
}

// Request parameters for closing an active session.
//
// If supported, the agent **must** cancel any ongoing work related to the session
// (treat it as if `session/cancel` was called) and then free up any resources
// associated with the session.
//
// Only available if the Agent supports the `sessionCapabilities.close` capability.
type CloseSessionRequest struct {
	// The ID of the session to close.
	SessionID SessionID `json:"sessionId"`
	Meta      Meta      `json:"_meta,omitzero"`
}

// Request parameters for setting a session mode.
type SetSessionModeRequest struct {
	// The ID of the session to set the mode for.
	SessionID SessionID `json:"sessionId"`
	// The ID of the mode to set.
	ModeID SessionModeID `json:"modeId"`
	Meta   Meta          `json:"_meta,omitzero"`
}

// Request parameters for sending a user prompt to the agent.
//
// Contains the user's message and any additional context.
//
// See protocol docs: [User Message]
//
// [User Message]: https://agentclientprotocol.com/protocol/prompt-turn#1-user-message
type PromptRequest struct {
	// The ID of the session to send this user message to
	SessionID SessionID `json:"sessionId"`
	// The blocks of content that compose the user's message.
	//
	// As a baseline, the Agent MUST support [ContentBlockText] and [ContentBlockResourceLink],
	// while other variants are optionally enabled via [PromptCapabilities].
	//
	// The Client MUST adapt its interface according to [PromptCapabilities].
	//
	// The client MAY include referenced pieces of context as either
	// [ContentBlockResource] or [ContentBlockResourceLink].
	//
	// When available, [ContentBlockResource] is preferred
	// as it avoids extra round-trips and allows the message to include
	// pieces of context from sources the agent may not have access to.
	Prompt []ContentBlock `json:"prompt"`
	Meta   Meta           `json:"_meta,omitzero"`
}

// StartNesRequest is a request to start an NES session.
type StartNesRequest struct {
	// The root URI of the workspace.
	WorkspaceURI *string `json:"workspaceUri,omitzero"`
	// The workspace folders.
	WorkspaceFolders []WorkspaceFolder `json:"workspaceFolders,omitzero"`
	// Repository metadata, if the workspace is a git repository.
	Repository *NesRepository `json:"repository,omitzero"`
	Meta       Meta           `json:"_meta,omitzero"`
}

// WorkspaceFolder is a workspace folder.
type WorkspaceFolder struct {
	// The URI of the folder.
	URI string `json:"uri"`
	// The display name of the folder.
	Name string `json:"name"`
	Meta Meta   `json:"_meta,omitzero"`
}

// Repository metadata for an NES session.
type NesRepository struct {
	// The repository name.
	Name string `json:"name"`
	// The repository owner.
	Owner string `json:"owner"`
	// The remote URL of the repository.
	RemoteURL string `json:"remoteUrl"`
	Meta      Meta   `json:"_meta,omitzero"`
}

// SuggestNesRequest is a request for a code suggestion.
type SuggestNesRequest struct {
	// The session ID for this request.
	SessionID SessionID `json:"sessionId"`
	// The URI of the document to suggest for.
	URI string `json:"uri"`
	// The version number of the document.
	Version int64 `json:"version"`
	// The current cursor position.
	Position Position `json:"position"`
	// The current text selection range, if any.
	Selection *Range `json:"selection,omitzero"`
	// What triggered this suggestion request.
	TriggerKind NesTriggerKind `json:"triggerKind"`
	// Context for the suggestion, included based on agent capabilities.
	Context *NesSuggestContext `json:"context,omitzero"`
	Meta    Meta               `json:"_meta,omitzero"`
}

// Context attached to a suggestion request.
type NesSuggestContext struct {
	// Recently accessed files.
	RecentFiles []NesRecentFile `json:"recentFiles,omitzero"`
	// Related code snippets.
	RelatedSnippets []NesRelatedSnippet `json:"relatedSnippets,omitzero"`
	// Recent edit history.
	EditHistory []NesEditHistoryEntry `json:"editHistory,omitzero"`
	// Recent user actions (typing, navigation, etc.).
	UserActions []NesUserAction `json:"userActions,omitzero"`
	// Currently open files in the editor.
	OpenFiles []NesOpenFile `json:"openFiles,omitzero"`
	// Current diagnostics (errors, warnings).
	Diagnostics []NesDiagnostic `json:"diagnostics,omitzero"`
	Meta        Meta            `json:"_meta,omitzero"`
}

// NesRecentFile is a recently accessed file.
type NesRecentFile struct {
	// The URI of the file.
	URI string `json:"uri"`
	// The language identifier.
	LanguageID string `json:"languageId"`
	// The full text content of the file.
	Text string `json:"text"`
	Meta Meta   `json:"_meta,omitzero"`
}

// NesRelatedSnippet is a related code snippet from a file.
type NesRelatedSnippet struct {
	// The URI of the file containing the snippets.
	URI string `json:"uri"`
	// The code excerpts.
	Excerpts []NesExcerpt `json:"excerpts"`
	Meta     Meta         `json:"_meta,omitzero"`
}

// NesExcerpt is a code excerpt from a file.
type NesExcerpt struct {
	// The start line of the excerpt (zero-based).
	StartLine uint32 `json:"startLine"`
	// The end line of the excerpt (zero-based).
	EndLine uint32 `json:"endLine"`
	// The text content of the excerpt.
	Text string `json:"text"`
	Meta Meta   `json:"_meta,omitzero"`
}

// NesEditHistoryEntry is an entry in the edit history.
type NesEditHistoryEntry struct {
	// The URI of the edited file.
	URI string `json:"uri"`
	// A diff representing the edit.
	Diff string `json:"diff"`
	Meta Meta   `json:"_meta,omitzero"`
}

// NesUserAction is a user action (typing, cursor movement, etc.).
type NesUserAction struct {
	// The kind of action (e.g., "insertChar", "cursorMovement").
	Action string `json:"action"`
	// The URI of the file where the action occurred.
	URI string `json:"uri"`
	// The position where the action occurred.
	Position Position `json:"position"`
	// Timestamp in milliseconds since epoch.
	TimestampMs uint64 `json:"timestampMs"`
	Meta        Meta   `json:"_meta,omitzero"`
}

// NesOpenFile is an open file in the editor.
type NesOpenFile struct {
	// The URI of the file.
	URI string `json:"uri"`
	// The language identifier.
	LanguageID string `json:"languageId"`
	// The visible range in the editor, if any.
	VisibleRange *Range `json:"visibleRange,omitzero"`
	// Timestamp in milliseconds since epoch of when the file was last focused.
	LastFocusedMs *uint64 `json:"lastFocusedMs,omitzero"`
	Meta          Meta    `json:"_meta,omitzero"`
}

// NesDiagnostic is a diagnostic (error, warning, etc.).
type NesDiagnostic struct {
	// The URI of the file containing the diagnostic.
	URI string `json:"uri"`
	// The range of the diagnostic.
	Range Range `json:"range"`
	// The severity of the diagnostic.
	Severity NesDiagnosticSeverity `json:"severity"`
	// The diagnostic message.
	Message string `json:"message"`
	Meta    Meta   `json:"_meta,omitzero"`
}

// CloseNesRequest is a request to close an NES session.
//
// The agent **must** cancel any ongoing work related to the NES session
// and then free up any resources associated with the session.
type CloseNesRequest struct {
	// The ID of the NES session to close.
	SessionID SessionID `json:"sessionId"`
	Meta      Meta      `json:"_meta,omitzero"`
}

// WriteTextFileResponse is a response to `fs/write_text_file`
type WriteTextFileResponse struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Response containing the contents of a text file.
type ReadTextFileResponse struct {
	// Content payload returned by this response.
	Content string `json:"content"`
	Meta    Meta   `json:"_meta,omitzero"`
}

// RequestPermissionResponse is a response to a permission request.
type RequestPermissionResponse struct {
	// The user's decision on the permission request.
	Outcome RequestPermissionOutcome `json:"outcome"`
	Meta    Meta                     `json:"_meta,omitzero"`
}

// Response containing the ID of the created terminal.
type CreateTerminalResponse struct {
	// The unique identifier for the created terminal.
	TerminalID TerminalID `json:"terminalId"`
	Meta       Meta       `json:"_meta,omitzero"`
}

// Response containing the terminal output and exit status.
type TerminalOutputResponse struct {
	// The terminal output captured so far.
	Output string `json:"output"`
	// Whether the output was truncated due to byte limits.
	Truncated bool `json:"truncated"`
	// Exit status if the command has completed.
	ExitStatus *TerminalExitStatus `json:"exitStatus,omitzero"`
	Meta       Meta                `json:"_meta,omitzero"`
}

// Exit status of a terminal command.
type TerminalExitStatus struct {
	// The process exit code (may be null if terminated by signal).
	ExitCode *uint32 `json:"exitCode,omitzero"`
	// The signal that terminated the process (may be null if exited normally).
	Signal *string `json:"signal,omitzero"`
	Meta   Meta    `json:"_meta,omitzero"`
}

// ReleaseTerminalResponse is a response to terminal/release method
type ReleaseTerminalResponse struct {
	Meta Meta `json:"_meta,omitzero"`
}

// Response containing the exit status of a terminal command.
type WaitForTerminalExitResponse struct {
	// The process exit code (may be null if terminated by signal).
	ExitCode *uint32 `json:"exitCode,omitzero"`
	// The signal that terminated the process (may be null if exited normally).
	Signal *string `json:"signal,omitzero"`
	Meta   Meta    `json:"_meta,omitzero"`
}

// KillTerminalResponse is a response to `terminal/kill` method
type KillTerminalResponse struct {
	Meta Meta `json:"_meta,omitzero"`
}

// ElicitationAcceptAction is the user accepted the elicitation and provided content.
type ElicitationAcceptAction struct {
	// The user-provided content, if any, as an object matching the requested schema.
	Content map[string]ElicitationContentValue `json:"content,omitzero"`
}

// MCPError is an inner MCP error, distinct from an outer ACP binding or runtime error.
//
// `code` and `message` are required and non-null. `data` is optional;
// explicit `null` is preserved separately from an omitted key.
//
// Experimental: not part of the spec yet; it may change or be removed.
type MCPError struct {
	// Inner MCP error code; never an ACP error code.
	Code int32 `json:"code"`
	// Inner MCP error message.
	Message string `json:"message"`
	// Optional error data; explicit null is retained.
	Data                 jsontext.Value            `json:"data,omitzero"`
	AdditionalProperties map[string]jsontext.Value `json:",embed"`
}

// CancelNotification is a notification to cancel ongoing operations for a session.
//
// See protocol docs: [Cancellation]
//
// [Cancellation]: https://agentclientprotocol.com/protocol/prompt-turn#cancellation
type CancelNotification struct {
	// The ID of the session to cancel operations for.
	SessionID SessionID `json:"sessionId"`
	Meta      Meta      `json:"_meta,omitzero"`
}

// Notification sent when a file is opened in the editor.
type DidOpenDocumentNotification struct {
	// The session ID for this notification.
	SessionID SessionID `json:"sessionId"`
	// The URI of the opened document.
	URI string `json:"uri"`
	// The language identifier of the document (e.g., "rust", "python").
	LanguageID string `json:"languageId"`
	// The version number of the document.
	Version int64 `json:"version"`
	// The full text content of the document.
	Text string `json:"text"`
	Meta Meta   `json:"_meta,omitzero"`
}

// Notification sent when a file is edited.
type DidChangeDocumentNotification struct {
	// The session ID for this notification.
	SessionID SessionID `json:"sessionId"`
	// The URI of the changed document.
	URI string `json:"uri"`
	// The new version number of the document.
	Version int64 `json:"version"`
	// The content changes.
	ContentChanges []TextDocumentContentChangeEvent `json:"contentChanges"`
	Meta           Meta                             `json:"_meta,omitzero"`
}

// TextDocumentContentChangeEvent is a content change event for a document.
//
// When `range` is `None`, `text` is the full content of the document.
// When `range` is `Some`, `text` replaces the given range.
type TextDocumentContentChangeEvent struct {
	// The range of the document that changed. If `None`, the entire content is replaced.
	Range *Range `json:"range,omitzero"`
	// The new text for the range, or the full document content if `range` is `None`.
	Text string `json:"text"`
	Meta Meta   `json:"_meta,omitzero"`
}

// Notification sent when a file is closed.
type DidCloseDocumentNotification struct {
	// The session ID for this notification.
	SessionID SessionID `json:"sessionId"`
	// The URI of the closed document.
	URI  string `json:"uri"`
	Meta Meta   `json:"_meta,omitzero"`
}

// Notification sent when a file is saved.
type DidSaveDocumentNotification struct {
	// The session ID for this notification.
	SessionID SessionID `json:"sessionId"`
	// The URI of the saved document.
	URI  string `json:"uri"`
	Meta Meta   `json:"_meta,omitzero"`
}

// DidFocusDocumentNotification is a notification sent when a file becomes the active editor tab.
type DidFocusDocumentNotification struct {
	// The session ID for this notification.
	SessionID SessionID `json:"sessionId"`
	// The URI of the focused document.
	URI string `json:"uri"`
	// The version number of the document.
	Version int64 `json:"version"`
	// The current cursor position.
	Position Position `json:"position"`
	// The portion of the file currently visible in the editor viewport.
	VisibleRange Range `json:"visibleRange"`
	Meta         Meta  `json:"_meta,omitzero"`
}

// Notification sent when a suggestion is accepted.
type AcceptNesNotification struct {
	// The session ID for this notification.
	SessionID SessionID `json:"sessionId"`
	// The ID of the accepted suggestion.
	ID   NesSuggestionID `json:"id"`
	Meta Meta            `json:"_meta,omitzero"`
}

// Notification sent when a suggestion is rejected.
type RejectNesNotification struct {
	// The session ID for this notification.
	SessionID SessionID `json:"sessionId"`
	// The ID of the rejected suggestion.
	ID NesSuggestionID `json:"id"`
	// The reason for rejection.
	Reason *NesRejectReason `json:"reason,omitzero"`
	Meta   Meta             `json:"_meta,omitzero"`
}

// Notification parameters for `mcp/message`.
//
// Sent by the provider to the consumer for an active request (including
// subscription acknowledgements and updates); the outer envelope has no `id`.
//
// Experimental: not part of the spec yet; it may change or be removed.
type MessageMCPNotification struct {
	// The declared ACP MCP server handling the associated request.
	ServerID MCPServerACPID `json:"serverId"`
	// The identifier of the active inner MCP request.
	RequestID MCPRequestID `json:"requestId"`
	// The inner MCP method name.
	Method string `json:"method"`
	// Optional inner MCP params.
	//
	// If omitted or set to `null`, the inner MCP message has no params.
	Params map[string]jsontext.Value `json:"params,omitzero"`
	Meta   Meta                      `json:"_meta,omitzero"`
}

// CancelRequestNotification is a notification to cancel an ongoing request.
//
// See protocol docs: [Cancellation]
//
// [Cancellation]: https://agentclientprotocol.com/protocol/cancellation
type CancelRequestNotification struct {
	// The ID of the request to cancel.
	RequestID RequestID `json:"requestId"`
	Meta      Meta      `json:"_meta,omitzero"`
}

type CreateElicitationRequestFormSession struct {
	// The session this elicitation is tied to.
	SessionID SessionID `json:"sessionId"`
	// Optional tool call within the session.
	//
	// Optional. Omitted and `null` are equivalent and mean the elicitation is scoped to the
	// session without a specific tool call.
	ToolCallID *ToolCallID `json:"toolCallId,omitzero"`
	// A JSON Schema describing the form fields to present to the user.
	RequestedSchema ElicitationSchema `json:"requestedSchema"`
	// Always "form": MarshalJSONTo writes it whatever the field holds.
	Mode string `json:"mode"`
	// A human-readable message describing what input is needed.
	Message string `json:"message"`
	// Optional. Omitted and `null` are equivalent and mean no metadata.
	Meta Meta `json:"_meta,omitzero"`
}

// MarshalJSONTo encodes v with its literal members fixed.
func (v CreateElicitationRequestFormSession) MarshalJSONTo(enc *jsontext.Encoder) error {
	v.Mode = "form"
	type plain CreateElicitationRequestFormSession
	return json.MarshalEncode(enc, plain(v))
}

type CreateElicitationRequestFormRequest struct {
	// The request this elicitation is tied to.
	RequestID RequestID `json:"requestId"`
	// A JSON Schema describing the form fields to present to the user.
	RequestedSchema ElicitationSchema `json:"requestedSchema"`
	// Always "form": MarshalJSONTo writes it whatever the field holds.
	Mode string `json:"mode"`
	// A human-readable message describing what input is needed.
	Message string `json:"message"`
	// Optional. Omitted and `null` are equivalent and mean no metadata.
	Meta Meta `json:"_meta,omitzero"`
}

// MarshalJSONTo encodes v with its literal members fixed.
func (v CreateElicitationRequestFormRequest) MarshalJSONTo(enc *jsontext.Encoder) error {
	v.Mode = "form"
	type plain CreateElicitationRequestFormRequest
	return json.MarshalEncode(enc, plain(v))
}

type CreateElicitationRequestURLSession struct {
	// The session this elicitation is tied to.
	SessionID SessionID `json:"sessionId"`
	// Optional tool call within the session.
	//
	// Optional. Omitted and `null` are equivalent and mean the elicitation is scoped to the
	// session without a specific tool call.
	ToolCallID *ToolCallID `json:"toolCallId,omitzero"`
	// The unique identifier for this elicitation.
	ElicitationID ElicitationID `json:"elicitationId"`
	// The URL to direct the user to.
	URL string `json:"url"`
	// Always "url": MarshalJSONTo writes it whatever the field holds.
	Mode string `json:"mode"`
	// A human-readable message describing what input is needed.
	Message string `json:"message"`
	// Optional. Omitted and `null` are equivalent and mean no metadata.
	Meta Meta `json:"_meta,omitzero"`
}

// MarshalJSONTo encodes v with its literal members fixed.
func (v CreateElicitationRequestURLSession) MarshalJSONTo(enc *jsontext.Encoder) error {
	v.Mode = "url"
	type plain CreateElicitationRequestURLSession
	return json.MarshalEncode(enc, plain(v))
}

type CreateElicitationRequestURLRequest struct {
	// The request this elicitation is tied to.
	RequestID RequestID `json:"requestId"`
	// The unique identifier for this elicitation.
	ElicitationID ElicitationID `json:"elicitationId"`
	// The URL to direct the user to.
	URL string `json:"url"`
	// Always "url": MarshalJSONTo writes it whatever the field holds.
	Mode string `json:"mode"`
	// A human-readable message describing what input is needed.
	Message string `json:"message"`
	// Optional. Omitted and `null` are equivalent and mean no metadata.
	Meta Meta `json:"_meta,omitzero"`
}

// MarshalJSONTo encodes v with its literal members fixed.
func (v CreateElicitationRequestURLRequest) MarshalJSONTo(enc *jsontext.Encoder) error {
	v.Mode = "url"
	type plain CreateElicitationRequestURLRequest
	return json.MarshalEncode(enc, plain(v))
}

type CreateElicitationRequestCustomSession struct {
	// The session this elicitation is tied to.
	SessionID SessionID `json:"sessionId"`
	// Optional tool call within the session.
	//
	// Optional. Omitted and `null` are equivalent and mean the elicitation is scoped to the
	// session without a specific tool call.
	ToolCallID *ToolCallID `json:"toolCallId,omitzero"`
	// Custom or future elicitation mode.
	//
	// Values beginning with `_` are reserved for implementation-specific
	// extensions. Unknown values that do not begin with `_` are reserved for
	// future ACP variants.
	Mode string `json:"mode"`
	// A human-readable message describing what input is needed.
	Message string `json:"message"`
	// Optional. Omitted and `null` are equivalent and mean no metadata.
	Meta                 Meta                      `json:"_meta,omitzero"`
	AdditionalProperties map[string]jsontext.Value `json:",embed"`
}

type CreateElicitationRequestCustomRequest struct {
	// The request this elicitation is tied to.
	RequestID RequestID `json:"requestId"`
	// Custom or future elicitation mode.
	//
	// Values beginning with `_` are reserved for implementation-specific
	// extensions. Unknown values that do not begin with `_` are reserved for
	// future ACP variants.
	Mode string `json:"mode"`
	// A human-readable message describing what input is needed.
	Message string `json:"message"`
	// Optional. Omitted and `null` are equivalent and mean no metadata.
	Meta                 Meta                      `json:"_meta,omitzero"`
	AdditionalProperties map[string]jsontext.Value `json:",embed"`
}

type ElicitationFormModeSession struct {
	// The session this elicitation is tied to.
	SessionID SessionID `json:"sessionId"`
	// Optional tool call within the session.
	//
	// Optional. Omitted and `null` are equivalent and mean the elicitation is scoped to the
	// session without a specific tool call.
	ToolCallID *ToolCallID `json:"toolCallId,omitzero"`
	// A JSON Schema describing the form fields to present to the user.
	RequestedSchema ElicitationSchema `json:"requestedSchema"`
}

type ElicitationFormModeRequest struct {
	// The request this elicitation is tied to.
	RequestID RequestID `json:"requestId"`
	// A JSON Schema describing the form fields to present to the user.
	RequestedSchema ElicitationSchema `json:"requestedSchema"`
}

type ElicitationURLModeSession struct {
	// The session this elicitation is tied to.
	SessionID SessionID `json:"sessionId"`
	// Optional tool call within the session.
	//
	// Optional. Omitted and `null` are equivalent and mean the elicitation is scoped to the
	// session without a specific tool call.
	ToolCallID *ToolCallID `json:"toolCallId,omitzero"`
	// The unique identifier for this elicitation.
	ElicitationID ElicitationID `json:"elicitationId"`
	// The URL to direct the user to.
	URL string `json:"url"`
}

type ElicitationURLModeRequest struct {
	// The request this elicitation is tied to.
	RequestID RequestID `json:"requestId"`
	// The unique identifier for this elicitation.
	ElicitationID ElicitationID `json:"elicitationId"`
	// The URL to direct the user to.
	URL string `json:"url"`
}

type MessageMCPResponseResult struct {
	// Required, even if JSON null.
	Result jsontext.Value `json:"result"`
	// Optional ACP carrier metadata.
	Meta Meta `json:"_meta,omitzero"`
}

type MessageMCPResponseError struct {
	// Required, non-null MCP error object.
	Error MCPError `json:"error"`
	// Optional ACP carrier metadata.
	Meta Meta `json:"_meta,omitzero"`
}

// Meta is the _meta extension object reserved on protocol messages.
type Meta = meta.Meta
