// Code generated by acp-schema from the method table; DO NOT EDIT.

package acp1

// The hand-written half of each façade provides AgentSideConnection and
// ClientSideConnection with a conn *jsonrpc.Connection field and an agent or
// client field holding the served interface; the lifecycle and extension
// methods every connection shares, and everything routed by method name, are
// generated here.

import (
	"context"
	"encoding/json/jsontext"

	acp "github.com/ironpark/acp-go"
	"github.com/ironpark/acp-go/internal/acpconn"
	"github.com/ironpark/acp-go/internal/jsonrpc"
	schema "github.com/ironpark/acp-go/schema/v1"
)

// Agent is the set of methods every ACP agent must handle.
//
// Everything beyond these four methods is optional and gated by a capability
// the agent advertises from [Agent.Initialize]. Implement the matching optional
// interface and the connection routes the method to it; when it is not
// implemented the peer receives "method not found".
//
// See protocol docs: [Agent](https://agentclientprotocol.com/protocol/overview#agent)
type Agent interface {
	// Initialize negotiates the protocol version and exchanges capabilities.
	//
	// See protocol docs: [Initialization](https://agentclientprotocol.com/protocol/initialization)
	Initialize(ctx context.Context, params *InitializeRequest) (*InitializeResponse, error)

	// NewSession creates a conversation session with its own context.
	//
	// See protocol docs: [Session Setup](https://agentclientprotocol.com/protocol/session-setup)
	NewSession(ctx context.Context, params *NewSessionRequest) (*NewSessionResponse, error)

	// Prompt runs one prompt turn and returns once it stops.
	//
	// See protocol docs: [Prompt Turn](https://agentclientprotocol.com/protocol/prompt-turn)
	Prompt(ctx context.Context, params *PromptRequest) (*PromptResponse, error)

	// CancelSession is a notification asking the agent to abort the current turn.
	// The pending Prompt call should return with StopReasonCancelled.
	//
	// See protocol docs: [Cancellation](https://agentclientprotocol.com/protocol/prompt-turn#cancellation)
	CancelSession(ctx context.Context, params *CancelNotification) error
}

// Authenticator handles authenticate. Implement it when the agent lists
// `authMethods` in its Initialize response; an agent that needs no
// credentials leaves it out and the method answers "method not found".
//
// See protocol docs: [Authentication](https://agentclientprotocol.com/protocol/authentication)
type Authenticator interface {
	Authenticate(ctx context.Context, params *AuthenticateRequest) (*AuthenticateResponse, error)
}

// SessionLoader handles session/load. Loading replays the conversation,
// which only the agent knows, so [SessionManager] leaves it to the agent;
// [SessionManager.Lookup] finds the session to replay.
//
// [CapabilitiesOf] advertises it with the `loadSession` agent capability.
type SessionLoader interface {
	LoadSession(ctx context.Context, params *LoadSessionRequest) (*LoadSessionResponse, error)
}

// SessionLister handles session/list.
//
// [CapabilitiesOf] advertises it with the `sessionCapabilities.list` agent capability.
type SessionLister interface {
	ListSessions(ctx context.Context, params *ListSessionsRequest) (*ListSessionsResponse, error)
}

// SessionDeleter handles session/delete.
//
// [CapabilitiesOf] advertises it with the `sessionCapabilities.delete` agent capability.
type SessionDeleter interface {
	DeleteSession(ctx context.Context, params *DeleteSessionRequest) (*DeleteSessionResponse, error)
}

// SessionForker handles session/fork.
//
// [CapabilitiesOf] advertises it with the `sessionCapabilities.fork` agent capability.
//
// Experimental: not part of the spec yet; it may change or be removed.
type SessionForker interface {
	ForkSession(ctx context.Context, params *ForkSessionRequest) (*ForkSessionResponse, error)
}

// SessionResumer handles session/resume, continuing a session without
// replaying its history.
//
// [CapabilitiesOf] advertises it with the `sessionCapabilities.resume` agent capability.
type SessionResumer interface {
	ResumeSession(ctx context.Context, params *ResumeSessionRequest) (*ResumeSessionResponse, error)
}

// SessionCloser handles session/close.
//
// [CapabilitiesOf] advertises it with the `sessionCapabilities.close` agent capability.
type SessionCloser interface {
	CloseSession(ctx context.Context, params *CloseSessionRequest) (*CloseSessionResponse, error)
}

// SessionModeSetter handles session/set_mode.
//
// See protocol docs: [Session Modes](https://agentclientprotocol.com/protocol/session-modes)
type SessionModeSetter interface {
	SetSessionMode(ctx context.Context, params *SetSessionModeRequest) (*SetSessionModeResponse, error)
}

// SessionConfigOptionSetter handles session/set_config_option. The response
// carries every option and its current value, since changing one option may
// change the others.
type SessionConfigOptionSetter interface {
	SetSessionConfigOption(ctx context.Context, params *SetSessionConfigOptionRequest) (*SetSessionConfigOptionResponse, error)
}

// ProviderManager handles the providers/* methods.
//
// [CapabilitiesOf] advertises it with the `providers` agent capability.
//
// Experimental: not part of the spec yet; it may change or be removed.
type ProviderManager interface {
	ListProviders(ctx context.Context, params *ListProvidersRequest) (*ListProvidersResponse, error)

	SetProvider(ctx context.Context, params *SetProviderRequest) (*SetProviderResponse, error)

	DisableProvider(ctx context.Context, params *DisableProviderRequest) (*DisableProviderResponse, error)
}

// LogoutHandler handles the logout method, clearing stored credentials.
//
// [CapabilitiesOf] advertises it with the `auth.logout` agent capability.
type LogoutHandler interface {
	Logout(ctx context.Context, params *LogoutRequest) (*LogoutResponse, error)
}

// NesHandler handles the nes/* methods for Next Edit Suggestions. AcceptNes
// and RejectNes are notifications.
//
// [CapabilitiesOf] advertises it with the `nes` agent capability.
//
// Experimental: not part of the spec yet; it may change or be removed.
type NesHandler interface {
	StartNes(ctx context.Context, params *StartNesRequest) (*StartNesResponse, error)

	SuggestNes(ctx context.Context, params *SuggestNesRequest) (*SuggestNesResponse, error)

	CloseNes(ctx context.Context, params *CloseNesRequest) (*CloseNesResponse, error)

	AcceptNes(ctx context.Context, params *AcceptNesNotification) error

	RejectNes(ctx context.Context, params *RejectNesNotification) error
}

// DocumentHandler receives the document/did* notifications that mirror the
// client's open editors.
//
// Experimental: not part of the spec yet; it may change or be removed.
type DocumentHandler interface {
	DidOpenDocument(ctx context.Context, params *DidOpenDocumentNotification) error

	DidChangeDocument(ctx context.Context, params *DidChangeDocumentNotification) error

	DidCloseDocument(ctx context.Context, params *DidCloseDocumentNotification) error

	DidSaveDocument(ctx context.Context, params *DidSaveDocumentNotification) error

	DidFocusDocument(ctx context.Context, params *DidFocusDocumentNotification) error
}

// MCPMessageHandler receives the request-scoped MCP notifications, such as
// progress, that an MCP server the client provides sends over mcp/message
// while it works on a request the agent made.
//
// MCP-over-ACP is an RFD-stage draft; the wire format may still change.
//
// [CapabilitiesOf] advertises it with the `mcpCapabilities.acp` agent capability.
//
// Experimental: not part of the spec yet; it may change or be removed.
type MCPMessageHandler interface {
	NotifyMCP(ctx context.Context, params *MessageMCPNotification) error
}

// Client is the set of methods every ACP client must handle.
//
// File system, terminal and elicitation support are optional; implement the
// matching interface and advertise the capability from
// `InitializeRequest.ClientCapabilities`.
//
// See protocol docs: [Client](https://agentclientprotocol.com/protocol/overview#client)
type Client interface {
	// SessionUpdate is a notification streaming turn progress to the user.
	//
	// Notifications are handled one at a time, in order, off the loop that reads
	// the connection, so a slow handler holds back neither the agent's messages
	// nor $/cancel_request. Updates stay ahead of the prompt response, and a
	// request from the agent is handled only after the updates sent before it.
	// A handler may call the agent and wait for the answer, unless answering needs
	// a request back to the client: that request waits for the handler to return.
	// Hand such calls to a goroutine.
	//
	// See protocol docs: [Agent Reports Output](https://agentclientprotocol.com/protocol/prompt-turn#3-agent-reports-output)
	SessionUpdate(ctx context.Context, params *SessionNotification) error

	// RequestPermission asks the user to authorize a tool call.
	//
	// When the turn is cancelled the client MUST answer with the cancelled
	// outcome rather than leaving the request pending.
	//
	// See protocol docs: [Requesting Permission](https://agentclientprotocol.com/protocol/tool-calls#requesting-permission)
	RequestPermission(ctx context.Context, params *RequestPermissionRequest) (*RequestPermissionResponse, error)
}

// FileReader handles fs/read_text_file.
//
// [ClientCapabilitiesOf] advertises it with the `fs.readTextFile` client capability.
type FileReader interface {
	ReadTextFile(ctx context.Context, params *ReadTextFileRequest) (*ReadTextFileResponse, error)
}

// FileWriter handles fs/write_text_file.
//
// [ClientCapabilitiesOf] advertises it with the `fs.writeTextFile` client capability.
type FileWriter interface {
	WriteTextFile(ctx context.Context, params *WriteTextFileRequest) (*WriteTextFileResponse, error)
}

// TerminalHandler handles every terminal/* method; one capability covers all
// five.
//
// [ClientCapabilitiesOf] advertises it with the `terminal` client capability.
//
// See protocol docs: [Terminals](https://agentclientprotocol.com/protocol/terminals)
type TerminalHandler interface {
	CreateTerminal(ctx context.Context, params *CreateTerminalRequest) (*CreateTerminalResponse, error)

	TerminalOutput(ctx context.Context, params *TerminalOutputRequest) (*TerminalOutputResponse, error)

	ReleaseTerminal(ctx context.Context, params *ReleaseTerminalRequest) (*ReleaseTerminalResponse, error)

	WaitForTerminalExit(ctx context.Context, params *WaitForTerminalExitRequest) (*WaitForTerminalExitResponse, error)

	KillTerminal(ctx context.Context, params *KillTerminalRequest) (*KillTerminalResponse, error)
}

// MCPProvider serves the MCP servers the client lists with the "acp"
// transport in session/new. Each mcp/message request is one MCP operation for
// the server its serverId names, identified by its own requestId; there is no
// MCP connection or initialization handshake.
//
// MCP-over-ACP is an RFD-stage draft; the wire format may still change.
//
// Experimental: not part of the spec yet; it may change or be removed.
type MCPProvider interface {
	MessageMCP(ctx context.Context, params *MessageMCPRequest) (*MessageMCPResponse, error)
}

// ElicitationHandler handles elicitation/create and the elicitation/complete
// notification.
//
// [ClientCapabilitiesOf] advertises it with the `elicitation` client capability.
type ElicitationHandler interface {
	CreateElicitation(ctx context.Context, params *CreateElicitationRequest) (*CreateElicitationResponse, error)

	CompleteElicitation(ctx context.Context, params *CompleteElicitationNotification) error
}

var _ acp.Conn = (*AgentSideConnection)(nil)

// Start processes messages until the peer disconnects or ctx is cancelled.
func (c *AgentSideConnection) Start(ctx context.Context) error { return c.conn.Start(ctx) }

// Close shuts the connection down, waiting for in-flight handlers.
func (c *AgentSideConnection) Close() error { return c.conn.Close() }

// Done is closed once the connection stops.
func (c *AgentSideConnection) Done() <-chan struct{} { return c.conn.Done() }

// ExtMethod sends a request outside the spec and returns its raw result.
func (c *AgentSideConnection) ExtMethod(ctx context.Context, method string, params any) (jsontext.Value, error) {
	return c.conn.SendRequest(ctx, method, params)
}

// ExtNotification sends a notification outside the spec.
func (c *AgentSideConnection) ExtNotification(ctx context.Context, method string, params any) error {
	return c.conn.SendNotification(ctx, method, params)
}

var _ acp.Conn = (*ClientSideConnection)(nil)

// Start processes messages until the peer disconnects or ctx is cancelled.
func (c *ClientSideConnection) Start(ctx context.Context) error { return c.conn.Start(ctx) }

// Close shuts the connection down, waiting for in-flight handlers.
func (c *ClientSideConnection) Close() error { return c.conn.Close() }

// Done is closed once the connection stops.
func (c *ClientSideConnection) Done() <-chan struct{} { return c.conn.Done() }

// ExtMethod sends a request outside the spec and returns its raw result.
func (c *ClientSideConnection) ExtMethod(ctx context.Context, method string, params any) (jsontext.Value, error) {
	return c.conn.SendRequest(ctx, method, params)
}

// ExtNotification sends a notification outside the spec.
func (c *ClientSideConnection) ExtNotification(ctx context.Context, method string, params any) error {
	return c.conn.SendNotification(ctx, method, params)
}

// --- Outgoing calls from ClientSideConnection to the peer ---

// Initialize negotiates the protocol version and exchanges capabilities. It is
// the first call on every connection. A zero ProtocolVersion, or nil params, sends
// [ProtocolVersion].
func (c *ClientSideConnection) Initialize(ctx context.Context, params *InitializeRequest) (*InitializeResponse, error) {
	return c.initialize(ctx, params)
}

// NewSession creates a session. It may fail with an auth-required error.
func (c *ClientSideConnection) NewSession(ctx context.Context, params *NewSessionRequest) (*NewSessionResponse, error) {
	return acpconn.Call[NewSessionResponse](ctx, c.conn, schema.AgentMethodsSessionNew, params)
}

// Prompt runs one prompt turn and returns once the agent stops.
//
// Cancelling ctx cancels the JSON-RPC request; to cancel the turn itself with
// the protocol's own semantics, send [ClientSideConnection.CancelSession].
//
// See protocol docs: [Prompt Turn](https://agentclientprotocol.com/protocol/prompt-turn)
func (c *ClientSideConnection) Prompt(ctx context.Context, params *PromptRequest) (*PromptResponse, error) {
	return acpconn.CallUntimed[PromptResponse](ctx, c.conn, schema.AgentMethodsSessionPrompt, params)
}

// CancelSession asks the agent to end the current turn. The pending Prompt call
// returns with the cancelled stop reason.
//
// See protocol docs: [Cancellation](https://agentclientprotocol.com/protocol/prompt-turn#cancellation)
func (c *ClientSideConnection) CancelSession(ctx context.Context, params *CancelNotification) error {
	return c.conn.SendNotification(ctx, schema.AgentMethodsSessionCancel, params)
}

// Authenticate authenticates with one of the methods the agent advertised.
func (c *ClientSideConnection) Authenticate(ctx context.Context, params *AuthenticateRequest) (*AuthenticateResponse, error) {
	return acpconn.Call[AuthenticateResponse](ctx, c.conn, schema.AgentMethodsAuthenticate, params)
}

// LoadSession resumes a session and replays its history as notifications.
// Requires the agent's `loadSession` capability.
func (c *ClientSideConnection) LoadSession(ctx context.Context, params *LoadSessionRequest) (*LoadSessionResponse, error) {
	return acpconn.Call[LoadSessionResponse](ctx, c.conn, schema.AgentMethodsSessionLoad, params)
}

// ListSessions lists sessions, optionally filtered and paginated.
func (c *ClientSideConnection) ListSessions(ctx context.Context, params *ListSessionsRequest) (*ListSessionsResponse, error) {
	return acpconn.Call[ListSessionsResponse](ctx, c.conn, schema.AgentMethodsSessionList, params)
}

// DeleteSession deletes a session and its stored history.
func (c *ClientSideConnection) DeleteSession(ctx context.Context, params *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return acpconn.Call[DeleteSessionResponse](ctx, c.conn, schema.AgentMethodsSessionDelete, params)
}

// ForkSession branches a session so work continues without touching the
// original history.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) ForkSession(ctx context.Context, params *ForkSessionRequest) (*ForkSessionResponse, error) {
	return acpconn.Call[ForkSessionResponse](ctx, c.conn, schema.AgentMethodsSessionFork, params)
}

// ResumeSession continues a session without replaying its history.
func (c *ClientSideConnection) ResumeSession(ctx context.Context, params *ResumeSessionRequest) (*ResumeSessionResponse, error) {
	return acpconn.Call[ResumeSessionResponse](ctx, c.conn, schema.AgentMethodsSessionResume, params)
}

// CloseSession cancels any ongoing work and frees the session's resources.
func (c *ClientSideConnection) CloseSession(ctx context.Context, params *CloseSessionRequest) (*CloseSessionResponse, error) {
	return acpconn.Call[CloseSessionResponse](ctx, c.conn, schema.AgentMethodsSessionClose, params)
}

// SetSessionMode switches the session between the agent's advertised modes.
func (c *ClientSideConnection) SetSessionMode(ctx context.Context, params *SetSessionModeRequest) (*SetSessionModeResponse, error) {
	return acpconn.Call[SetSessionModeResponse](ctx, c.conn, schema.AgentMethodsSessionSetMode, params)
}

// SetSessionConfigOption sets one configuration option. The response returns
// every option, since one change may affect the others.
func (c *ClientSideConnection) SetSessionConfigOption(ctx context.Context, params *SetSessionConfigOptionRequest) (*SetSessionConfigOptionResponse, error) {
	return acpconn.Call[SetSessionConfigOptionResponse](ctx, c.conn, schema.AgentMethodsSessionSetConfigOption, params)
}

// ListProviders lists the model providers the agent can use.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) ListProviders(ctx context.Context, params *ListProvidersRequest) (*ListProvidersResponse, error) {
	return acpconn.Call[ListProvidersResponse](ctx, c.conn, schema.AgentMethodsProvidersList, params)
}

// SetProvider configures one provider.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) SetProvider(ctx context.Context, params *SetProviderRequest) (*SetProviderResponse, error) {
	return acpconn.Call[SetProviderResponse](ctx, c.conn, schema.AgentMethodsProvidersSet, params)
}

// DisableProvider turns one provider off.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) DisableProvider(ctx context.Context, params *DisableProviderRequest) (*DisableProviderResponse, error) {
	return acpconn.Call[DisableProviderResponse](ctx, c.conn, schema.AgentMethodsProvidersDisable, params)
}

// Logout clears the credentials the agent holds.
func (c *ClientSideConnection) Logout(ctx context.Context, params *LogoutRequest) (*LogoutResponse, error) {
	return acpconn.Call[LogoutResponse](ctx, c.conn, schema.AgentMethodsLogout, params)
}

// StartNes starts a Next Edit Suggestions stream.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) StartNes(ctx context.Context, params *StartNesRequest) (*StartNesResponse, error) {
	return acpconn.Call[StartNesResponse](ctx, c.conn, schema.AgentMethodsNesStart, params)
}

// SuggestNes asks for the next edit suggestion.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) SuggestNes(ctx context.Context, params *SuggestNesRequest) (*SuggestNesResponse, error) {
	return acpconn.Call[SuggestNesResponse](ctx, c.conn, schema.AgentMethodsNesSuggest, params)
}

// CloseNes ends a Next Edit Suggestions stream.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) CloseNes(ctx context.Context, params *CloseNesRequest) (*CloseNesResponse, error) {
	return acpconn.Call[CloseNesResponse](ctx, c.conn, schema.AgentMethodsNesClose, params)
}

// AcceptNes reports that the user accepted a suggestion.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) AcceptNes(ctx context.Context, params *AcceptNesNotification) error {
	return c.conn.SendNotification(ctx, schema.AgentMethodsNesAccept, params)
}

// RejectNes reports that the user rejected a suggestion.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) RejectNes(ctx context.Context, params *RejectNesNotification) error {
	return c.conn.SendNotification(ctx, schema.AgentMethodsNesReject, params)
}

// DidOpenDocument tells the agent a document was opened.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) DidOpenDocument(ctx context.Context, params *DidOpenDocumentNotification) error {
	return c.conn.SendNotification(ctx, schema.AgentMethodsDocumentDidOpen, params)
}

// DidChangeDocument tells the agent a document changed.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) DidChangeDocument(ctx context.Context, params *DidChangeDocumentNotification) error {
	return c.conn.SendNotification(ctx, schema.AgentMethodsDocumentDidChange, params)
}

// DidCloseDocument tells the agent a document was closed.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) DidCloseDocument(ctx context.Context, params *DidCloseDocumentNotification) error {
	return c.conn.SendNotification(ctx, schema.AgentMethodsDocumentDidClose, params)
}

// DidSaveDocument tells the agent a document was saved.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) DidSaveDocument(ctx context.Context, params *DidSaveDocumentNotification) error {
	return c.conn.SendNotification(ctx, schema.AgentMethodsDocumentDidSave, params)
}

// DidFocusDocument tells the agent a document was focused.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) DidFocusDocument(ctx context.Context, params *DidFocusDocumentNotification) error {
	return c.conn.SendNotification(ctx, schema.AgentMethodsDocumentDidFocus, params)
}

// NotifyMCP sends the agent a notification belonging to one of its MCP requests.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *ClientSideConnection) NotifyMCP(ctx context.Context, params *MessageMCPNotification) error {
	return c.conn.SendNotification(ctx, schema.AgentMethodsMCPMessage, params)
}

// --- Outgoing calls from AgentSideConnection to the peer ---

// SessionUpdate streams turn progress to the client.
func (c *AgentSideConnection) SessionUpdate(ctx context.Context, params *SessionNotification) error {
	return c.conn.SendNotification(ctx, schema.ClientMethodsSessionUpdate, params)
}

// RequestPermission asks the user to authorize a tool call.
func (c *AgentSideConnection) RequestPermission(ctx context.Context, params *RequestPermissionRequest) (*RequestPermissionResponse, error) {
	return acpconn.CallUntimed[RequestPermissionResponse](ctx, c.conn, schema.ClientMethodsSessionRequestPermission, params)
}

// ReadTextFile reads a text file through the client. Requires the client's
// `fs.readTextFile` capability.
func (c *AgentSideConnection) ReadTextFile(ctx context.Context, params *ReadTextFileRequest) (*ReadTextFileResponse, error) {
	return acpconn.Call[ReadTextFileResponse](ctx, c.conn, schema.ClientMethodsFSReadTextFile, params)
}

// WriteTextFile writes a text file through the client. Requires the client's
// `fs.writeTextFile` capability.
func (c *AgentSideConnection) WriteTextFile(ctx context.Context, params *WriteTextFileRequest) (*WriteTextFileResponse, error) {
	return acpconn.Call[WriteTextFileResponse](ctx, c.conn, schema.ClientMethodsFSWriteTextFile, params)
}

// CreateTerminal starts a command in a client-managed terminal. Requires the
// client's `terminal` capability. [AgentSideConnection.NewTerminal] also returns
// a handle bound to the new terminal.
func (c *AgentSideConnection) CreateTerminal(ctx context.Context, params *CreateTerminalRequest) (*CreateTerminalResponse, error) {
	return acpconn.Call[CreateTerminalResponse](ctx, c.conn, schema.ClientMethodsTerminalCreate, params)
}

// TerminalOutput returns a terminal's output so far without waiting for exit.
func (c *AgentSideConnection) TerminalOutput(ctx context.Context, params *TerminalOutputRequest) (*TerminalOutputResponse, error) {
	return acpconn.Call[TerminalOutputResponse](ctx, c.conn, schema.ClientMethodsTerminalOutput, params)
}

// ReleaseTerminal kills the command if needed and frees the terminal.
func (c *AgentSideConnection) ReleaseTerminal(ctx context.Context, params *ReleaseTerminalRequest) (*ReleaseTerminalResponse, error) {
	return acpconn.Call[ReleaseTerminalResponse](ctx, c.conn, schema.ClientMethodsTerminalRelease, params)
}

// WaitForTerminalExit blocks until the terminal's command exits.
func (c *AgentSideConnection) WaitForTerminalExit(ctx context.Context, params *WaitForTerminalExitRequest) (*WaitForTerminalExitResponse, error) {
	return acpconn.Call[WaitForTerminalExitResponse](ctx, c.conn, schema.ClientMethodsTerminalWaitForExit, params)
}

// KillTerminal kills the command but keeps the terminal id valid.
func (c *AgentSideConnection) KillTerminal(ctx context.Context, params *KillTerminalRequest) (*KillTerminalResponse, error) {
	return acpconn.Call[KillTerminalResponse](ctx, c.conn, schema.ClientMethodsTerminalKill, params)
}

// MessageMCP sends one MCP request to a server the client provides and returns
// its outcome: the MCP result, or the MCP error, which is not an ACP error.
//
// Experimental: not part of the spec yet; it may change or be removed.
func (c *AgentSideConnection) MessageMCP(ctx context.Context, params *MessageMCPRequest) (*MessageMCPResponse, error) {
	return acpconn.Call[MessageMCPResponse](ctx, c.conn, schema.ClientMethodsMCPMessage, params)
}

// CreateElicitation asks the client to collect input from the user. Requires
// the client's `elicitation` capability.
func (c *AgentSideConnection) CreateElicitation(ctx context.Context, params *CreateElicitationRequest) (*CreateElicitationResponse, error) {
	return acpconn.CallUntimed[CreateElicitationResponse](ctx, c.conn, schema.ClientMethodsElicitationCreate, params)
}

// CompleteElicitation tells the client an elicitation no longer needs an answer.
func (c *AgentSideConnection) CompleteElicitation(ctx context.Context, params *CompleteElicitationNotification) error {
	return c.conn.SendNotification(ctx, schema.ClientMethodsElicitationComplete, params)
}

func (c *AgentSideConnection) handleRequest(ctx context.Context, method string, params jsontext.Value) (any, error) {
	switch method {
	case schema.AgentMethodsInitialize:
		return acpconn.Request(ctx, schema.Validated(), params, c.initialize)
	case schema.AgentMethodsSessionNew:
		return acpconn.Request(ctx, schema.Validated(), params, c.agent.NewSession)
	case schema.AgentMethodsSessionPrompt:
		return acpconn.Request(ctx, schema.Validated(), params, c.agent.Prompt)
	case schema.AgentMethodsAuthenticate:
		if h, ok := c.agent.(Authenticator); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.Authenticate)
		}
	case schema.AgentMethodsSessionLoad:
		if h, ok := c.agent.(SessionLoader); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.LoadSession)
		}
	case schema.AgentMethodsSessionList:
		if h, ok := c.agent.(SessionLister); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.ListSessions)
		}
	case schema.AgentMethodsSessionDelete:
		if h, ok := c.agent.(SessionDeleter); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.DeleteSession)
		}
	case schema.AgentMethodsSessionFork:
		if h, ok := c.agent.(SessionForker); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.ForkSession)
		}
	case schema.AgentMethodsSessionResume:
		if h, ok := c.agent.(SessionResumer); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.ResumeSession)
		}
	case schema.AgentMethodsSessionClose:
		if h, ok := c.agent.(SessionCloser); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.CloseSession)
		}
	case schema.AgentMethodsSessionSetMode:
		if h, ok := c.agent.(SessionModeSetter); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.SetSessionMode)
		}
	case schema.AgentMethodsSessionSetConfigOption:
		if h, ok := c.agent.(SessionConfigOptionSetter); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.SetSessionConfigOption)
		}
	case schema.AgentMethodsProvidersList:
		if h, ok := c.agent.(ProviderManager); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.ListProviders)
		}
	case schema.AgentMethodsProvidersSet:
		if h, ok := c.agent.(ProviderManager); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.SetProvider)
		}
	case schema.AgentMethodsProvidersDisable:
		if h, ok := c.agent.(ProviderManager); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.DisableProvider)
		}
	case schema.AgentMethodsLogout:
		if h, ok := c.agent.(LogoutHandler); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.Logout)
		}
	case schema.AgentMethodsNesStart:
		if h, ok := c.agent.(NesHandler); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.StartNes)
		}
	case schema.AgentMethodsNesSuggest:
		if h, ok := c.agent.(NesHandler); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.SuggestNes)
		}
	case schema.AgentMethodsNesClose:
		if h, ok := c.agent.(NesHandler); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.CloseNes)
		}
	default:
		if h, ok := c.agent.(ExtMethodHandler); ok {
			return h.ServeExtMethod(ctx, method, params)
		}
	}
	return nil, jsonrpc.MethodNotFound(method)
}

func (c *AgentSideConnection) handleNotification(ctx context.Context, method string, params jsontext.Value) error {
	switch method {
	case schema.AgentMethodsSessionCancel:
		return acpconn.Notify(ctx, schema.Validated(), params, c.agent.CancelSession)
	case schema.AgentMethodsNesAccept:
		if h, ok := c.agent.(NesHandler); ok {
			return acpconn.Notify(ctx, schema.Validated(), params, h.AcceptNes)
		}
	case schema.AgentMethodsNesReject:
		if h, ok := c.agent.(NesHandler); ok {
			return acpconn.Notify(ctx, schema.Validated(), params, h.RejectNes)
		}
	case schema.AgentMethodsDocumentDidOpen:
		if h, ok := c.agent.(DocumentHandler); ok {
			return acpconn.Notify(ctx, schema.Validated(), params, h.DidOpenDocument)
		}
	case schema.AgentMethodsDocumentDidChange:
		if h, ok := c.agent.(DocumentHandler); ok {
			return acpconn.Notify(ctx, schema.Validated(), params, h.DidChangeDocument)
		}
	case schema.AgentMethodsDocumentDidClose:
		if h, ok := c.agent.(DocumentHandler); ok {
			return acpconn.Notify(ctx, schema.Validated(), params, h.DidCloseDocument)
		}
	case schema.AgentMethodsDocumentDidSave:
		if h, ok := c.agent.(DocumentHandler); ok {
			return acpconn.Notify(ctx, schema.Validated(), params, h.DidSaveDocument)
		}
	case schema.AgentMethodsDocumentDidFocus:
		if h, ok := c.agent.(DocumentHandler); ok {
			return acpconn.Notify(ctx, schema.Validated(), params, h.DidFocusDocument)
		}
	case schema.AgentMethodsMCPMessage:
		if h, ok := c.agent.(MCPMessageHandler); ok {
			return acpconn.Notify(ctx, schema.Validated(), params, h.NotifyMCP)
		}
	default:
		if h, ok := c.agent.(ExtNotificationHandler); ok {
			return h.ServeExtNotification(ctx, method, params)
		}
	}
	return jsonrpc.MethodNotFound(method)
}

func (c *ClientSideConnection) handleRequest(ctx context.Context, method string, params jsontext.Value) (any, error) {
	switch method {
	case schema.ClientMethodsSessionRequestPermission:
		return acpconn.Request(ctx, schema.Validated(), params, c.client.RequestPermission)
	case schema.ClientMethodsFSReadTextFile:
		if h, ok := c.client.(FileReader); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.ReadTextFile)
		}
	case schema.ClientMethodsFSWriteTextFile:
		if h, ok := c.client.(FileWriter); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.WriteTextFile)
		}
	case schema.ClientMethodsTerminalCreate:
		if h, ok := c.client.(TerminalHandler); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.CreateTerminal)
		}
	case schema.ClientMethodsTerminalOutput:
		if h, ok := c.client.(TerminalHandler); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.TerminalOutput)
		}
	case schema.ClientMethodsTerminalRelease:
		if h, ok := c.client.(TerminalHandler); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.ReleaseTerminal)
		}
	case schema.ClientMethodsTerminalWaitForExit:
		if h, ok := c.client.(TerminalHandler); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.WaitForTerminalExit)
		}
	case schema.ClientMethodsTerminalKill:
		if h, ok := c.client.(TerminalHandler); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.KillTerminal)
		}
	case schema.ClientMethodsMCPMessage:
		if h, ok := c.client.(MCPProvider); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.MessageMCP)
		}
	case schema.ClientMethodsElicitationCreate:
		if h, ok := c.client.(ElicitationHandler); ok {
			return acpconn.Request(ctx, schema.Validated(), params, h.CreateElicitation)
		}
	default:
		if h, ok := c.client.(ExtMethodHandler); ok {
			return h.ServeExtMethod(ctx, method, params)
		}
	}
	return nil, jsonrpc.MethodNotFound(method)
}

func (c *ClientSideConnection) handleNotification(ctx context.Context, method string, params jsontext.Value) error {
	switch method {
	case schema.ClientMethodsSessionUpdate:
		return acpconn.Notify(ctx, schema.Validated(), params, c.sessionUpdate)
	case schema.ClientMethodsElicitationComplete:
		if h, ok := c.client.(ElicitationHandler); ok {
			return acpconn.Notify(ctx, schema.Validated(), params, h.CompleteElicitation)
		}
	default:
		if h, ok := c.client.(ExtNotificationHandler); ok {
			return h.ServeExtNotification(ctx, method, params)
		}
	}
	return jsonrpc.MethodNotFound(method)
}

// capabilitiesOf sets in caps the capability of the Agent interface and of each
// optional interface agent implements.
func capabilitiesOf(agent Agent, caps *schema.AgentCapabilities) {
	if _, ok := agent.(SessionLoader); ok {
		caps.LoadSession = new(true)
	}
	if _, ok := agent.(SessionLister); ok {
		if caps.SessionCapabilities == nil {
			caps.SessionCapabilities = &schema.SessionCapabilities{}
		}
		caps.SessionCapabilities.List = &schema.SessionListCapabilities{}
	}
	if _, ok := agent.(SessionDeleter); ok {
		if caps.SessionCapabilities == nil {
			caps.SessionCapabilities = &schema.SessionCapabilities{}
		}
		caps.SessionCapabilities.Delete = &schema.SessionDeleteCapabilities{}
	}
	if _, ok := agent.(SessionForker); ok {
		if caps.SessionCapabilities == nil {
			caps.SessionCapabilities = &schema.SessionCapabilities{}
		}
		caps.SessionCapabilities.Fork = &schema.SessionForkCapabilities{}
	}
	if _, ok := agent.(SessionResumer); ok {
		if caps.SessionCapabilities == nil {
			caps.SessionCapabilities = &schema.SessionCapabilities{}
		}
		caps.SessionCapabilities.Resume = &schema.SessionResumeCapabilities{}
	}
	if _, ok := agent.(SessionCloser); ok {
		if caps.SessionCapabilities == nil {
			caps.SessionCapabilities = &schema.SessionCapabilities{}
		}
		caps.SessionCapabilities.Close = &schema.SessionCloseCapabilities{}
	}
	if _, ok := agent.(ProviderManager); ok {
		caps.Providers = &schema.ProvidersCapabilities{}
	}
	if _, ok := agent.(LogoutHandler); ok {
		if caps.Auth == nil {
			caps.Auth = &schema.AgentAuthCapabilities{}
		}
		caps.Auth.Logout = &schema.LogoutCapabilities{}
	}
	if _, ok := agent.(NesHandler); ok {
		caps.Nes = &schema.NesCapabilities{}
	}
	if _, ok := agent.(MCPMessageHandler); ok {
		if caps.MCPCapabilities == nil {
			caps.MCPCapabilities = &schema.MCPCapabilities{}
		}
		caps.MCPCapabilities.ACP = new(true)
	}
}

// clientCapabilitiesOf sets in caps the capability of the Client interface and of each
// optional interface client implements.
func clientCapabilitiesOf(client Client, caps *schema.ClientCapabilities) {
	if _, ok := client.(FileReader); ok {
		if caps.FS == nil {
			caps.FS = &schema.FileSystemCapabilities{}
		}
		caps.FS.ReadTextFile = new(true)
	}
	if _, ok := client.(FileWriter); ok {
		if caps.FS == nil {
			caps.FS = &schema.FileSystemCapabilities{}
		}
		caps.FS.WriteTextFile = new(true)
	}
	if _, ok := client.(TerminalHandler); ok {
		caps.Terminal = new(true)
	}
	if _, ok := client.(ElicitationHandler); ok {
		caps.Elicitation = &schema.ElicitationCapabilities{}
	}
}
