// Code generated by acp-schema from the method table; DO NOT EDIT.

package acp1

import schema "github.com/ironpark/acp-go/schema/v1"

// ProtocolVersion is the ACP protocol version implemented by this package.
const ProtocolVersion = schema.CurrentProtocolVersion

// Every request, response and notification payload, re-exported so that a
// caller implementing [Agent] or [Client] needs one import.

type (
	WriteTextFileRequest            = schema.WriteTextFileRequest
	ReadTextFileRequest             = schema.ReadTextFileRequest
	RequestPermissionRequest        = schema.RequestPermissionRequest
	CreateTerminalRequest           = schema.CreateTerminalRequest
	TerminalOutputRequest           = schema.TerminalOutputRequest
	ReleaseTerminalRequest          = schema.ReleaseTerminalRequest
	WaitForTerminalExitRequest      = schema.WaitForTerminalExitRequest
	KillTerminalRequest             = schema.KillTerminalRequest
	CreateElicitationRequest        = schema.CreateElicitationRequest
	MessageMCPRequest               = schema.MessageMCPRequest
	ExtRequest                      = schema.ExtRequest
	InitializeResponse              = schema.InitializeResponse
	AuthenticateResponse            = schema.AuthenticateResponse
	ListProvidersResponse           = schema.ListProvidersResponse
	SetProviderResponse             = schema.SetProviderResponse
	DisableProviderResponse         = schema.DisableProviderResponse
	LogoutResponse                  = schema.LogoutResponse
	NewSessionResponse              = schema.NewSessionResponse
	LoadSessionResponse             = schema.LoadSessionResponse
	ListSessionsResponse            = schema.ListSessionsResponse
	DeleteSessionResponse           = schema.DeleteSessionResponse
	ForkSessionResponse             = schema.ForkSessionResponse
	ResumeSessionResponse           = schema.ResumeSessionResponse
	CloseSessionResponse            = schema.CloseSessionResponse
	SetSessionModeResponse          = schema.SetSessionModeResponse
	SetSessionConfigOptionResponse  = schema.SetSessionConfigOptionResponse
	PromptResponse                  = schema.PromptResponse
	StartNesResponse                = schema.StartNesResponse
	SuggestNesResponse              = schema.SuggestNesResponse
	CloseNesResponse                = schema.CloseNesResponse
	ExtResponse                     = schema.ExtResponse
	SessionNotification             = schema.SessionNotification
	CompleteElicitationNotification = schema.CompleteElicitationNotification
	ExtNotification                 = schema.ExtNotification
	InitializeRequest               = schema.InitializeRequest
	AuthenticateRequest             = schema.AuthenticateRequest
	ListProvidersRequest            = schema.ListProvidersRequest
	SetProviderRequest              = schema.SetProviderRequest
	DisableProviderRequest          = schema.DisableProviderRequest
	LogoutRequest                   = schema.LogoutRequest
	NewSessionRequest               = schema.NewSessionRequest
	LoadSessionRequest              = schema.LoadSessionRequest
	ListSessionsRequest             = schema.ListSessionsRequest
	DeleteSessionRequest            = schema.DeleteSessionRequest
	ForkSessionRequest              = schema.ForkSessionRequest
	ResumeSessionRequest            = schema.ResumeSessionRequest
	CloseSessionRequest             = schema.CloseSessionRequest
	SetSessionModeRequest           = schema.SetSessionModeRequest
	SetSessionConfigOptionRequest   = schema.SetSessionConfigOptionRequest
	PromptRequest                   = schema.PromptRequest
	StartNesRequest                 = schema.StartNesRequest
	SuggestNesRequest               = schema.SuggestNesRequest
	CloseNesRequest                 = schema.CloseNesRequest
	WriteTextFileResponse           = schema.WriteTextFileResponse
	ReadTextFileResponse            = schema.ReadTextFileResponse
	RequestPermissionResponse       = schema.RequestPermissionResponse
	CreateTerminalResponse          = schema.CreateTerminalResponse
	TerminalOutputResponse          = schema.TerminalOutputResponse
	ReleaseTerminalResponse         = schema.ReleaseTerminalResponse
	WaitForTerminalExitResponse     = schema.WaitForTerminalExitResponse
	KillTerminalResponse            = schema.KillTerminalResponse
	CreateElicitationResponse       = schema.CreateElicitationResponse
	MessageMCPResponse              = schema.MessageMCPResponse
	CancelNotification              = schema.CancelNotification
	DidOpenDocumentNotification     = schema.DidOpenDocumentNotification
	DidChangeDocumentNotification   = schema.DidChangeDocumentNotification
	DidCloseDocumentNotification    = schema.DidCloseDocumentNotification
	DidSaveDocumentNotification     = schema.DidSaveDocumentNotification
	DidFocusDocumentNotification    = schema.DidFocusDocumentNotification
	AcceptNesNotification           = schema.AcceptNesNotification
	RejectNesNotification           = schema.RejectNesNotification
	MessageMCPNotification          = schema.MessageMCPNotification
	CancelRequestNotification       = schema.CancelRequestNotification
)

// Every type those payloads reach, with the constants and constructors
// that come with them.

type (
	AgentAuthCapabilities                    = schema.AgentAuthCapabilities
	AgentCapabilities                        = schema.AgentCapabilities
	Annotations                              = schema.Annotations
	AuthCapabilities                         = schema.AuthCapabilities
	AuthMethod                               = schema.AuthMethod
	AuthMethodAgent                          = schema.AuthMethodAgent
	AuthMethodID                             = schema.AuthMethodID
	AuthMethodTerminal                       = schema.AuthMethodTerminal
	AuthMethodVariant                        = schema.AuthMethodVariant
	AuthMethodVariants                       = schema.AuthMethodVariants
	AvailableCommand                         = schema.AvailableCommand
	AvailableCommandInput                    = schema.AvailableCommandInput
	BlobResourceContents                     = schema.BlobResourceContents
	BooleanConfigOptionCapabilities          = schema.BooleanConfigOptionCapabilities
	ClientCapabilities                       = schema.ClientCapabilities
	ClientNesCapabilities                    = schema.ClientNesCapabilities
	ClientSessionCapabilities                = schema.ClientSessionCapabilities
	CompactionCapabilities                   = schema.CompactionCapabilities
	CompactionID                             = schema.CompactionID
	CompactionStatus                         = schema.CompactionStatus
	ContentBlock                             = schema.ContentBlock
	ContentBlockAudio                        = schema.ContentBlockAudio
	ContentBlockImage                        = schema.ContentBlockImage
	ContentBlockResource                     = schema.ContentBlockResource
	ContentBlockResourceLink                 = schema.ContentBlockResourceLink
	ContentBlockText                         = schema.ContentBlockText
	ContentBlockUnknown                      = schema.ContentBlockUnknown
	ContentBlockVariant                      = schema.ContentBlockVariant
	ContentBlockVariants                     = schema.ContentBlockVariants
	Cost                                     = schema.Cost
	CreateElicitationRequestAlternative      = schema.CreateElicitationRequestAlternative
	CreateElicitationRequestCustomRequest    = schema.CreateElicitationRequestCustomRequest
	CreateElicitationRequestCustomSession    = schema.CreateElicitationRequestCustomSession
	CreateElicitationRequestFormRequest      = schema.CreateElicitationRequestFormRequest
	CreateElicitationRequestFormSession      = schema.CreateElicitationRequestFormSession
	CreateElicitationRequestURLRequest       = schema.CreateElicitationRequestURLRequest
	CreateElicitationRequestURLSession       = schema.CreateElicitationRequestURLSession
	CreateElicitationResponseAccept          = schema.CreateElicitationResponseAccept
	CreateElicitationResponseCancel          = schema.CreateElicitationResponseCancel
	CreateElicitationResponseCustom          = schema.CreateElicitationResponseCustom
	CreateElicitationResponseDecline         = schema.CreateElicitationResponseDecline
	CreateElicitationResponseVariant         = schema.CreateElicitationResponseVariant
	CreateElicitationResponseVariants        = schema.CreateElicitationResponseVariants
	ElicitationCapabilities                  = schema.ElicitationCapabilities
	ElicitationContentValue                  = schema.ElicitationContentValue
	ElicitationContentValueAlternative       = schema.ElicitationContentValueAlternative
	ElicitationFormCapabilities              = schema.ElicitationFormCapabilities
	ElicitationID                            = schema.ElicitationID
	ElicitationPropertySchema                = schema.ElicitationPropertySchema
	ElicitationPropertySchemaArray           = schema.ElicitationPropertySchemaArray
	ElicitationPropertySchemaBoolean         = schema.ElicitationPropertySchemaBoolean
	ElicitationPropertySchemaCustom          = schema.ElicitationPropertySchemaCustom
	ElicitationPropertySchemaInteger         = schema.ElicitationPropertySchemaInteger
	ElicitationPropertySchemaNumber          = schema.ElicitationPropertySchemaNumber
	ElicitationPropertySchemaString          = schema.ElicitationPropertySchemaString
	ElicitationPropertySchemaVariant         = schema.ElicitationPropertySchemaVariant
	ElicitationPropertySchemaVariants        = schema.ElicitationPropertySchemaVariants
	ElicitationSchema                        = schema.ElicitationSchema
	ElicitationSchemaType                    = schema.ElicitationSchemaType
	ElicitationURLCapabilities               = schema.ElicitationURLCapabilities
	EmbeddedResourceResource                 = schema.EmbeddedResourceResource
	EmbeddedResourceResourceAlternative      = schema.EmbeddedResourceResourceAlternative
	EnumOption                               = schema.EnumOption
	EnvVariable                              = schema.EnvVariable
	FileSystemCapabilities                   = schema.FileSystemCapabilities
	HTTPHeader                               = schema.HTTPHeader
	Implementation                           = schema.Implementation
	LLMProtocol                              = schema.LLMProtocol
	LogoutCapabilities                       = schema.LogoutCapabilities
	MCPCapabilities                          = schema.MCPCapabilities
	MCPError                                 = schema.MCPError
	MCPRequestID                             = schema.MCPRequestID
	MCPServer                                = schema.MCPServer
	MCPServerACP                             = schema.MCPServerACP
	MCPServerACPID                           = schema.MCPServerACPID
	MCPServerHTTP                            = schema.MCPServerHTTP
	MCPServerSSE                             = schema.MCPServerSSE
	MCPServerStdio                           = schema.MCPServerStdio
	MCPServerVariant                         = schema.MCPServerVariant
	MCPServerVariants                        = schema.MCPServerVariants
	MessageID                                = schema.MessageID
	MessageMCPResponseAlternative            = schema.MessageMCPResponseAlternative
	MessageMCPResponseError                  = schema.MessageMCPResponseError
	MessageMCPResponseResult                 = schema.MessageMCPResponseResult
	Meta                                     = schema.Meta
	MultiSelectItems                         = schema.MultiSelectItems
	MultiSelectItemsCustom                   = schema.MultiSelectItemsCustom
	MultiSelectItemsString                   = schema.MultiSelectItemsString
	MultiSelectItemsVariant                  = schema.MultiSelectItemsVariant
	MultiSelectItemsVariants                 = schema.MultiSelectItemsVariants
	NesCapabilities                          = schema.NesCapabilities
	NesContextCapabilities                   = schema.NesContextCapabilities
	NesDiagnostic                            = schema.NesDiagnostic
	NesDiagnosticSeverity                    = schema.NesDiagnosticSeverity
	NesDiagnosticsCapabilities               = schema.NesDiagnosticsCapabilities
	NesDocumentDidChangeCapabilities         = schema.NesDocumentDidChangeCapabilities
	NesDocumentDidCloseCapabilities          = schema.NesDocumentDidCloseCapabilities
	NesDocumentDidFocusCapabilities          = schema.NesDocumentDidFocusCapabilities
	NesDocumentDidOpenCapabilities           = schema.NesDocumentDidOpenCapabilities
	NesDocumentDidSaveCapabilities           = schema.NesDocumentDidSaveCapabilities
	NesDocumentEventCapabilities             = schema.NesDocumentEventCapabilities
	NesEditHistoryCapabilities               = schema.NesEditHistoryCapabilities
	NesEditHistoryEntry                      = schema.NesEditHistoryEntry
	NesEventCapabilities                     = schema.NesEventCapabilities
	NesExcerpt                               = schema.NesExcerpt
	NesJumpCapabilities                      = schema.NesJumpCapabilities
	NesOpenFile                              = schema.NesOpenFile
	NesOpenFilesCapabilities                 = schema.NesOpenFilesCapabilities
	NesRecentFile                            = schema.NesRecentFile
	NesRecentFilesCapabilities               = schema.NesRecentFilesCapabilities
	NesRejectReason                          = schema.NesRejectReason
	NesRelatedSnippet                        = schema.NesRelatedSnippet
	NesRelatedSnippetsCapabilities           = schema.NesRelatedSnippetsCapabilities
	NesRenameCapabilities                    = schema.NesRenameCapabilities
	NesRepository                            = schema.NesRepository
	NesSearchAndReplaceCapabilities          = schema.NesSearchAndReplaceCapabilities
	NesSuggestContext                        = schema.NesSuggestContext
	NesSuggestion                            = schema.NesSuggestion
	NesSuggestionEdit                        = schema.NesSuggestionEdit
	NesSuggestionID                          = schema.NesSuggestionID
	NesSuggestionJump                        = schema.NesSuggestionJump
	NesSuggestionRename                      = schema.NesSuggestionRename
	NesSuggestionSearchAndReplace            = schema.NesSuggestionSearchAndReplace
	NesSuggestionUnknown                     = schema.NesSuggestionUnknown
	NesSuggestionVariant                     = schema.NesSuggestionVariant
	NesSuggestionVariants                    = schema.NesSuggestionVariants
	NesTextEdit                              = schema.NesTextEdit
	NesTriggerKind                           = schema.NesTriggerKind
	NesUserAction                            = schema.NesUserAction
	NesUserActionsCapabilities               = schema.NesUserActionsCapabilities
	NoticeCapabilities                       = schema.NoticeCapabilities
	NoticeSeverity                           = schema.NoticeSeverity
	PermissionOption                         = schema.PermissionOption
	PermissionOptionID                       = schema.PermissionOptionID
	PermissionOptionKind                     = schema.PermissionOptionKind
	PlanCapabilities                         = schema.PlanCapabilities
	PlanEntry                                = schema.PlanEntry
	PlanEntryPriority                        = schema.PlanEntryPriority
	PlanEntryStatus                          = schema.PlanEntryStatus
	PlanID                                   = schema.PlanID
	PlanUpdateContent                        = schema.PlanUpdateContent
	PlanUpdateContentFile                    = schema.PlanUpdateContentFile
	PlanUpdateContentItems                   = schema.PlanUpdateContentItems
	PlanUpdateContentMarkdown                = schema.PlanUpdateContentMarkdown
	PlanUpdateContentUnknown                 = schema.PlanUpdateContentUnknown
	PlanUpdateContentVariant                 = schema.PlanUpdateContentVariant
	PlanUpdateContentVariants                = schema.PlanUpdateContentVariants
	Position                                 = schema.Position
	PositionEncodingKind                     = schema.PositionEncodingKind
	PromptCapabilities                       = schema.PromptCapabilities
	ProviderCurrentConfig                    = schema.ProviderCurrentConfig
	ProviderID                               = schema.ProviderID
	ProviderInfo                             = schema.ProviderInfo
	ProvidersCapabilities                    = schema.ProvidersCapabilities
	Range                                    = schema.Range
	RequestID                                = schema.RequestID
	RequestIDAlternative                     = schema.RequestIDAlternative
	RequestPermissionOutcome                 = schema.RequestPermissionOutcome
	RequestPermissionOutcomeCancelled        = schema.RequestPermissionOutcomeCancelled
	RequestPermissionOutcomeSelected         = schema.RequestPermissionOutcomeSelected
	RequestPermissionOutcomeUnknown          = schema.RequestPermissionOutcomeUnknown
	RequestPermissionOutcomeVariant          = schema.RequestPermissionOutcomeVariant
	RequestPermissionOutcomeVariants         = schema.RequestPermissionOutcomeVariants
	Role                                     = schema.Role
	SessionAdditionalDirectoriesCapabilities = schema.SessionAdditionalDirectoriesCapabilities
	SessionCancelCapabilities                = schema.SessionCancelCapabilities
	SessionCapabilities                      = schema.SessionCapabilities
	SessionCloseCapabilities                 = schema.SessionCloseCapabilities
	SessionConfigGroupID                     = schema.SessionConfigGroupID
	SessionConfigID                          = schema.SessionConfigID
	SessionConfigOption                      = schema.SessionConfigOption
	SessionConfigOptionBoolean               = schema.SessionConfigOptionBoolean
	SessionConfigOptionCategory              = schema.SessionConfigOptionCategory
	SessionConfigOptionSelect                = schema.SessionConfigOptionSelect
	SessionConfigOptionUnknown               = schema.SessionConfigOptionUnknown
	SessionConfigOptionVariant               = schema.SessionConfigOptionVariant
	SessionConfigOptionVariants              = schema.SessionConfigOptionVariants
	SessionConfigOptionsCapabilities         = schema.SessionConfigOptionsCapabilities
	SessionConfigSelectGroup                 = schema.SessionConfigSelectGroup
	SessionConfigSelectOption                = schema.SessionConfigSelectOption
	SessionConfigSelectOptions               = schema.SessionConfigSelectOptions
	SessionConfigSelectOptionsAlternative    = schema.SessionConfigSelectOptionsAlternative
	SessionConfigValueID                     = schema.SessionConfigValueID
	SessionDeleteCapabilities                = schema.SessionDeleteCapabilities
	SessionForkCapabilities                  = schema.SessionForkCapabilities
	SessionID                                = schema.SessionID
	SessionInfo                              = schema.SessionInfo
	SessionListCapabilities                  = schema.SessionListCapabilities
	SessionMode                              = schema.SessionMode
	SessionModeID                            = schema.SessionModeID
	SessionModeState                         = schema.SessionModeState
	SessionResumeCapabilities                = schema.SessionResumeCapabilities
	SessionUpdate                            = schema.SessionUpdate
	SessionUpdateAgentMessageChunk           = schema.SessionUpdateAgentMessageChunk
	SessionUpdateAgentThoughtChunk           = schema.SessionUpdateAgentThoughtChunk
	SessionUpdateAvailableCommandsUpdate     = schema.SessionUpdateAvailableCommandsUpdate
	SessionUpdateCompactionSummaryChunk      = schema.SessionUpdateCompactionSummaryChunk
	SessionUpdateCompactionUpdate            = schema.SessionUpdateCompactionUpdate
	SessionUpdateConfigOptionUpdate          = schema.SessionUpdateConfigOptionUpdate
	SessionUpdateCurrentModeUpdate           = schema.SessionUpdateCurrentModeUpdate
	SessionUpdateNotice                      = schema.SessionUpdateNotice
	SessionUpdatePlan                        = schema.SessionUpdatePlan
	SessionUpdatePlanRemoved                 = schema.SessionUpdatePlanRemoved
	SessionUpdatePlanUpdate                  = schema.SessionUpdatePlanUpdate
	SessionUpdateSessionInfoUpdate           = schema.SessionUpdateSessionInfoUpdate
	SessionUpdateSessionMessage              = schema.SessionUpdateSessionMessage
	SessionUpdateSessionMessageChunk         = schema.SessionUpdateSessionMessageChunk
	SessionUpdateSubagentUpdate              = schema.SessionUpdateSubagentUpdate
	SessionUpdateToolCall                    = schema.SessionUpdateToolCall
	SessionUpdateToolCallUpdate              = schema.SessionUpdateToolCallUpdate
	SessionUpdateUnknown                     = schema.SessionUpdateUnknown
	SessionUpdateUsageUpdate                 = schema.SessionUpdateUsageUpdate
	SessionUpdateUserMessageChunk            = schema.SessionUpdateUserMessageChunk
	SessionUpdateVariant                     = schema.SessionUpdateVariant
	SessionUpdateVariants                    = schema.SessionUpdateVariants
	SetSessionConfigOptionRequestBoolean     = schema.SetSessionConfigOptionRequestBoolean
	SetSessionConfigOptionRequestUntagged    = schema.SetSessionConfigOptionRequestUntagged
	SetSessionConfigOptionRequestVariant     = schema.SetSessionConfigOptionRequestVariant
	SetSessionConfigOptionRequestVariants    = schema.SetSessionConfigOptionRequestVariants
	StateUpdate                              = schema.StateUpdate
	StateUpdateCustom                        = schema.StateUpdateCustom
	StateUpdateIdle                          = schema.StateUpdateIdle
	StateUpdateRequiresAction                = schema.StateUpdateRequiresAction
	StateUpdateRunning                       = schema.StateUpdateRunning
	StateUpdateUnknown                       = schema.StateUpdateUnknown
	StateUpdateVariant                       = schema.StateUpdateVariant
	StateUpdateVariants                      = schema.StateUpdateVariants
	StopReason                               = schema.StopReason
	StringFormat                             = schema.StringFormat
	SubagentCapabilities                     = schema.SubagentCapabilities
	SubagentSessionCapabilities              = schema.SubagentSessionCapabilities
	TerminalExitStatus                       = schema.TerminalExitStatus
	TerminalID                               = schema.TerminalID
	TextDocumentContentChangeEvent           = schema.TextDocumentContentChangeEvent
	TextDocumentSyncKind                     = schema.TextDocumentSyncKind
	TextResourceContents                     = schema.TextResourceContents
	TitledMultiSelectItems                   = schema.TitledMultiSelectItems
	ToolCallContent                          = schema.ToolCallContent
	ToolCallContentContent                   = schema.ToolCallContentContent
	ToolCallContentDiff                      = schema.ToolCallContentDiff
	ToolCallContentTerminal                  = schema.ToolCallContentTerminal
	ToolCallContentUnknown                   = schema.ToolCallContentUnknown
	ToolCallContentVariant                   = schema.ToolCallContentVariant
	ToolCallContentVariants                  = schema.ToolCallContentVariants
	ToolCallID                               = schema.ToolCallID
	ToolCallLocation                         = schema.ToolCallLocation
	ToolCallStatus                           = schema.ToolCallStatus
	ToolCallUpdate                           = schema.ToolCallUpdate
	ToolKind                                 = schema.ToolKind
	UnstructuredCommandInput                 = schema.UnstructuredCommandInput
	Usage                                    = schema.Usage
	WorkspaceFolder                          = schema.WorkspaceFolder
)

const (
	CompactionStatusInProgress              = schema.CompactionStatusInProgress
	CompactionStatusCompleted               = schema.CompactionStatusCompleted
	CompactionStatusFailed                  = schema.CompactionStatusFailed
	CompactionStatusCancelled               = schema.CompactionStatusCancelled
	ElicitationSchemaTypeObject             = schema.ElicitationSchemaTypeObject
	LLMProtocolAnthropic                    = schema.LLMProtocolAnthropic
	LLMProtocolOpenAI                       = schema.LLMProtocolOpenAI
	LLMProtocolAzure                        = schema.LLMProtocolAzure
	LLMProtocolVertex                       = schema.LLMProtocolVertex
	LLMProtocolBedrock                      = schema.LLMProtocolBedrock
	NesDiagnosticSeverityError              = schema.NesDiagnosticSeverityError
	NesDiagnosticSeverityWarning            = schema.NesDiagnosticSeverityWarning
	NesDiagnosticSeverityInformation        = schema.NesDiagnosticSeverityInformation
	NesDiagnosticSeverityHint               = schema.NesDiagnosticSeverityHint
	NesRejectReasonRejected                 = schema.NesRejectReasonRejected
	NesRejectReasonIgnored                  = schema.NesRejectReasonIgnored
	NesRejectReasonReplaced                 = schema.NesRejectReasonReplaced
	NesRejectReasonCancelled                = schema.NesRejectReasonCancelled
	NesTriggerKindAutomatic                 = schema.NesTriggerKindAutomatic
	NesTriggerKindDiagnostic                = schema.NesTriggerKindDiagnostic
	NesTriggerKindManual                    = schema.NesTriggerKindManual
	NoticeSeverityInfo                      = schema.NoticeSeverityInfo
	NoticeSeverityWarning                   = schema.NoticeSeverityWarning
	NoticeSeverityError                     = schema.NoticeSeverityError
	PermissionOptionKindAllowOnce           = schema.PermissionOptionKindAllowOnce
	PermissionOptionKindAllowAlways         = schema.PermissionOptionKindAllowAlways
	PermissionOptionKindRejectOnce          = schema.PermissionOptionKindRejectOnce
	PermissionOptionKindRejectAlways        = schema.PermissionOptionKindRejectAlways
	PlanEntryPriorityHigh                   = schema.PlanEntryPriorityHigh
	PlanEntryPriorityMedium                 = schema.PlanEntryPriorityMedium
	PlanEntryPriorityLow                    = schema.PlanEntryPriorityLow
	PlanEntryStatusPending                  = schema.PlanEntryStatusPending
	PlanEntryStatusInProgress               = schema.PlanEntryStatusInProgress
	PlanEntryStatusCompleted                = schema.PlanEntryStatusCompleted
	PositionEncodingKindUTF16               = schema.PositionEncodingKindUTF16
	PositionEncodingKindUTF32               = schema.PositionEncodingKindUTF32
	PositionEncodingKindUTF8                = schema.PositionEncodingKindUTF8
	RoleAssistant                           = schema.RoleAssistant
	RoleUser                                = schema.RoleUser
	SessionConfigOptionCategoryMode         = schema.SessionConfigOptionCategoryMode
	SessionConfigOptionCategoryModel        = schema.SessionConfigOptionCategoryModel
	SessionConfigOptionCategoryModelConfig  = schema.SessionConfigOptionCategoryModelConfig
	SessionConfigOptionCategoryThoughtLevel = schema.SessionConfigOptionCategoryThoughtLevel
	StopReasonEndTurn                       = schema.StopReasonEndTurn
	StopReasonMaxTokens                     = schema.StopReasonMaxTokens
	StopReasonMaxTurnRequests               = schema.StopReasonMaxTurnRequests
	StopReasonRefusal                       = schema.StopReasonRefusal
	StopReasonCancelled                     = schema.StopReasonCancelled
	StringFormatEmail                       = schema.StringFormatEmail
	StringFormatURI                         = schema.StringFormatURI
	StringFormatDate                        = schema.StringFormatDate
	StringFormatDateTime                    = schema.StringFormatDateTime
	TextDocumentSyncKindFull                = schema.TextDocumentSyncKindFull
	TextDocumentSyncKindIncremental         = schema.TextDocumentSyncKindIncremental
	ToolCallStatusPending                   = schema.ToolCallStatusPending
	ToolCallStatusInProgress                = schema.ToolCallStatusInProgress
	ToolCallStatusCompleted                 = schema.ToolCallStatusCompleted
	ToolCallStatusFailed                    = schema.ToolCallStatusFailed
	ToolKindRead                            = schema.ToolKindRead
	ToolKindEdit                            = schema.ToolKindEdit
	ToolKindDelete                          = schema.ToolKindDelete
	ToolKindMove                            = schema.ToolKindMove
	ToolKindSearch                          = schema.ToolKindSearch
	ToolKindExecute                         = schema.ToolKindExecute
	ToolKindThink                           = schema.ToolKindThink
	ToolKindFetch                           = schema.ToolKindFetch
	ToolKindSwitchMode                      = schema.ToolKindSwitchMode
	ToolKindOther                           = schema.ToolKindOther
)

// NewAuthMethod wraps a variant.
func NewAuthMethod[T AuthMethodVariants](v T) AuthMethod { return schema.NewAuthMethod(v) }

// NewContentBlock wraps a variant.
func NewContentBlock[T ContentBlockVariants](v T) ContentBlock { return schema.NewContentBlock(v) }

// NewCreateElicitationRequest encodes value, one of the CreateElicitationRequestAlternative types.
func NewCreateElicitationRequest[T CreateElicitationRequestAlternative](value T) (CreateElicitationRequest, error) {
	return schema.NewCreateElicitationRequest(value)
}

// NewCreateElicitationResponse wraps a variant.
func NewCreateElicitationResponse[T CreateElicitationResponseVariants](v T) CreateElicitationResponse {
	return schema.NewCreateElicitationResponse(v)
}

// NewElicitationContentValue encodes value, one of the ElicitationContentValueAlternative types.
func NewElicitationContentValue[T ElicitationContentValueAlternative](value T) (ElicitationContentValue, error) {
	return schema.NewElicitationContentValue(value)
}

// NewElicitationPropertySchema wraps a variant.
func NewElicitationPropertySchema[T ElicitationPropertySchemaVariants](v T) ElicitationPropertySchema {
	return schema.NewElicitationPropertySchema(v)
}

// NewEmbeddedResourceResource encodes value, one of the EmbeddedResourceResourceAlternative types.
func NewEmbeddedResourceResource[T EmbeddedResourceResourceAlternative](value T) (EmbeddedResourceResource, error) {
	return schema.NewEmbeddedResourceResource(value)
}

// NewMCPServer wraps a variant.
func NewMCPServer[T MCPServerVariants](v T) MCPServer { return schema.NewMCPServer(v) }

// NewMessageMCPResponse encodes value, one of the MessageMCPResponseAlternative types.
func NewMessageMCPResponse[T MessageMCPResponseAlternative](value T) (MessageMCPResponse, error) {
	return schema.NewMessageMCPResponse(value)
}

// NewMultiSelectItems wraps a variant.
func NewMultiSelectItems[T MultiSelectItemsVariants](v T) MultiSelectItems {
	return schema.NewMultiSelectItems(v)
}

// NewNesSuggestion wraps a variant.
func NewNesSuggestion[T NesSuggestionVariants](v T) NesSuggestion { return schema.NewNesSuggestion(v) }

// NewPlanUpdateContent wraps a variant.
func NewPlanUpdateContent[T PlanUpdateContentVariants](v T) PlanUpdateContent {
	return schema.NewPlanUpdateContent(v)
}

// NewRequestID encodes value, one of the RequestIDAlternative types.
func NewRequestID[T RequestIDAlternative](value T) (RequestID, error) {
	return schema.NewRequestID(value)
}

// NewRequestPermissionOutcome wraps a variant.
func NewRequestPermissionOutcome[T RequestPermissionOutcomeVariants](v T) RequestPermissionOutcome {
	return schema.NewRequestPermissionOutcome(v)
}

// NewSessionConfigOption wraps a variant.
func NewSessionConfigOption[T SessionConfigOptionVariants](v T) SessionConfigOption {
	return schema.NewSessionConfigOption(v)
}

// NewSessionConfigSelectOptions encodes value, one of the SessionConfigSelectOptionsAlternative types.
func NewSessionConfigSelectOptions[T SessionConfigSelectOptionsAlternative](value T) (SessionConfigSelectOptions, error) {
	return schema.NewSessionConfigSelectOptions(value)
}

// NewSessionUpdate wraps a variant.
func NewSessionUpdate[T SessionUpdateVariants](v T) SessionUpdate { return schema.NewSessionUpdate(v) }

// NewSetSessionConfigOptionRequest wraps a variant.
func NewSetSessionConfigOptionRequest[T SetSessionConfigOptionRequestVariants](v T) SetSessionConfigOptionRequest {
	return schema.NewSetSessionConfigOptionRequest(v)
}

// NewStateUpdate wraps a variant.
func NewStateUpdate[T StateUpdateVariants](v T) StateUpdate { return schema.NewStateUpdate(v) }

// NewToolCallContent wraps a variant.
func NewToolCallContent[T ToolCallContentVariants](v T) ToolCallContent {
	return schema.NewToolCallContent(v)
}
